/**
 * This file is automatically generated from /utils/scripts/uploadIllustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const inferenceContent = `${BASE_URL}/products/inference/inference-content.webp`
const inferenceKeyvisual = `${BASE_URL}/products/inference/inference-keyvisual.webp`
const inferenceOriginal = `${BASE_URL}/products/inference/inference-original.webp`
const inferenceWire = `${BASE_URL}/products/inference/inference-wire.svg`

export {
  inferenceContent,
  inferenceKeyvisual,
  inferenceOriginal,
  inferenceWire,
}
