import './vanilla/globalStyle.css'

export type { ExtendedColor, TextStyleObject, TextVariant, UltravioletUITheme } from './constants'
export { textVariants } from './constants'
export { generateObjectStyleFromTheme, isColorMonochrome, isSize } from './helpers'
export { ThemeProvider, useTheme } from './ThemeProvider'
export { ThemesProvider, useThemes } from './ThemesProvider'
export type { ConsoleTheme } from './ThemesProvider'
export * from './themes'
export { darkThemeClass, darkerThemeClass, lightThemeClass, theme } from './vanilla/themes.css'
export { extendTheme } from './extendTheme'
