/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://scaleway-assets.s3.fr-par.scw.cloud/illustrations'

const instanceContent = `${BASE_URL}/products/instance/instance-content.webp`
const instanceCopContent = `${BASE_URL}/products/instance/instance-cop-content.webp`
const instanceCopKeyvisual = `${BASE_URL}/products/instance/instance-cop-keyvisual.webp`
const instanceCopOriginal = `${BASE_URL}/products/instance/instance-cop-original.webp`
const instanceCopWire = `${BASE_URL}/products/instance/instance-cop-wire.svg`
const instanceGpuContent = `${BASE_URL}/products/instance/instance-gpu-content.webp`
const instanceGpuKeyvisual = `${BASE_URL}/products/instance/instance-gpu-keyvisual.webp`
const instanceGpuOriginal = `${BASE_URL}/products/instance/instance-gpu-original.webp`
const instanceGpuWire = `${BASE_URL}/products/instance/instance-gpu-wire.svg`
const instanceKeyvisual = `${BASE_URL}/products/instance/instance-keyvisual.webp`
const instanceLearningContent = `${BASE_URL}/products/instance/instance-learning-content.webp`
const instanceLearningKeyvisual = `${BASE_URL}/products/instance/instance-learning-keyvisual.webp`
const instanceLearningOriginal = `${BASE_URL}/products/instance/instance-learning-original.webp`
const instanceLearningWire = `${BASE_URL}/products/instance/instance-learning-wire.svg`
const instanceOriginal = `${BASE_URL}/products/instance/instance-original.webp`
const instancePopContent = `${BASE_URL}/products/instance/instance-pop-content.webp`
const instancePopKeyvisual = `${BASE_URL}/products/instance/instance-pop-keyvisual.webp`
const instancePopOriginal = `${BASE_URL}/products/instance/instance-pop-original.webp`
const instancePopWire = `${BASE_URL}/products/instance/instance-pop-wire.svg`
const instanceWire = `${BASE_URL}/products/instance/instance-wire.svg`
const instanceWopContent = `${BASE_URL}/products/instance/instance-wop-content.webp`
const instanceWopKeyvisual = `${BASE_URL}/products/instance/instance-wop-keyvisual.webp`
const instanceWopOriginal = `${BASE_URL}/products/instance/instance-wop-original.webp`
const instanceWopWire = `${BASE_URL}/products/instance/instance-wop-wire.svg`

export {
  instanceContent,
  instanceCopContent,
  instanceCopKeyvisual,
  instanceCopOriginal,
  instanceCopWire,
  instanceGpuContent,
  instanceGpuKeyvisual,
  instanceGpuOriginal,
  instanceGpuWire,
  instanceKeyvisual,
  instanceLearningContent,
  instanceLearningKeyvisual,
  instanceLearningOriginal,
  instanceLearningWire,
  instanceOriginal,
  instancePopContent,
  instancePopKeyvisual,
  instancePopOriginal,
  instancePopWire,
  instanceWire,
  instanceWopContent,
  instanceWopKeyvisual,
  instanceWopOriginal,
  instanceWopWire,
}
