'use client'

import { useTheme } from '@ultraviolet/themes'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AndroidLogo = ({ ...props }: Omit<IconProps, 'children'>) => {
  const { theme } = useTheme()
  const isLight = theme === 'light'

  return (
    <Icon {...props}>
      {isLight ? (
        <>
          <path
            fill="#3ddb85"
            d="M14.493 12.718a.814.814 0 0 1 0-1.626.814.814 0 0 1 0 1.626m-8.986 0a.814.814 0 0 1 0-1.626.814.814 0 0 1 0 1.626m9.278-4.897 1.624-2.814a.338.338 0 0 0-.585-.338l-1.645 2.85A10 10 0 0 0 10 6.624c-1.508 0-2.92.32-4.179.893l-1.645-2.85a.338.338 0 0 0-.585.339L5.215 7.82C2.425 9.338.517 12.163.238 15.5h19.524c-.28-3.337-2.188-6.162-4.977-7.68"
          />
        </>
      ) : (
        <>
          <path
            fill="#fff"
            d="M14.493 12.718a.814.814 0 0 1 0-1.626.814.814 0 0 1 0 1.626m-8.986 0a.814.814 0 0 1 0-1.626.814.814 0 0 1 0 1.626m9.278-4.897 1.624-2.814a.338.338 0 0 0-.585-.338l-1.645 2.85A10 10 0 0 0 10 6.624c-1.508 0-2.92.32-4.179.893l-1.645-2.85a.338.338 0 0 0-.585.339L5.215 7.82C2.425 9.338.517 12.163.238 15.5h19.524c-.28-3.337-2.188-6.162-4.977-7.68"
          />
        </>
      )}
    </Icon>
  )
}

AndroidLogo.displayName = 'AndroidLogo'
