'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const GitlabLogo = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="GitlabLogo">
    <path
      d="M10.0001 19.4235L13.6827 8.08972H6.31743L10.0001 19.4235Z"
      fill="#E24329"
    />
    <path
      d="M10.0001 19.4235L6.31743 8.08972L1.15647 8.08963L10.0001 19.4235Z"
      fill="#FC6D26"
    />
    <path
      d="M1.15647 8.08963L0.0373228 11.5339C-0.0124342 11.6871 -0.0124411 11.852 0.0373032 12.0051C0.0870475 12.1583 0.183989 12.2917 0.314235 12.3863L10.0001 19.4235L1.15647 8.08963Z"
      fill="#FCA326"
    />
    <path
      d="M1.15647 8.08963L6.31743 8.08972L4.09955 1.26342C3.98541 0.912155 3.4885 0.912233 3.37443 1.26342L1.15647 8.08963Z"
      fill="#E24329"
    />
    <path
      d="M10.0001 19.4235L13.6827 8.08972L18.8438 8.08963L10.0001 19.4235Z"
      fill="#FC6D26"
    />
    <path
      d="M18.8438 8.08963L19.9627 11.5339C20.0124 11.6871 20.0124 11.852 19.9627 12.0051C19.9129 12.1583 19.816 12.2917 19.6857 12.3863L10.0001 19.4235L18.8438 8.08963Z"
      fill="#FCA326"
    />
    <path
      d="M18.8438 8.08963L13.6827 8.08972L15.9006 1.26342C16.0147 0.912155 16.5117 0.912233 16.6257 1.26342L18.8438 8.08963Z"
      fill="#E24329"
    />
  </Icon>
)
