'use client'

import { useTheme } from '@ultraviolet/themes'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const IstioLogo = (props: Omit<IconProps, 'children'>) => {
  const { theme } = useTheme()
  const isLight = theme === 'light'

  return (
    <Icon {...props}>
      {isLight ? (
        <>
          <path fill="#466bb0" d="m16.833 16.667-7.5-.834V0zm-13.333 0 5-.834V6.667zm0 .833h13.333L8.5 20z" />
        </>
      ) : (
        <>
          <path fill="#fff" d="m16.667 16.667-7.5-.834V0zm-13.334 0 5-.834V6.667zm0 .833h13.334L8.333 20z" />
        </>
      )}
    </Icon>
  )
}

IstioLogo.displayName = 'IstioLogo'
