'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const LogstashLogo: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="LogstashLogo">
    <path
      d="M10.3092 10.691H1.03639V0H3.8364C7.43641 0 10.3092 2.90911 10.3092 6.47277V10.691Z"
      fill="#F3BD19"
    />
    <path
      d="M10.3092 20C5.18185 20 1 15.8546 1 10.6909L10.3092 10.691L10.3092 20Z"
      fill="#231F20"
    />
    <path
      d="M10.3092 10.691L18.7819 10.6909V20H10.3092L10.3092 10.691Z"
      fill="#3EBEB0"
    />
    <path
      d="M10.3092 10.691L12.2728 10.6909V20H10.3092L10.3092 10.691Z"
      fill="#37A595"
    />
  </Icon>
)
