'use client'

import { useTheme } from '@ultraviolet/themes'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const LogstashLogo = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => {
  const { theme } = useTheme()
  const isLight = theme === 'light'

  return (
    <Icon {...props} title="LogstashLogo">
      {isLight ? (
        <>
          <path fill="#f3bd19" d="M10.3092 10.691H1.03639V0H3.8364C7.43641 0 10.3092 2.90911 10.3092 6.47277V10.691Z" />
          <path fill="#231f20" d="M10.3092 20C5.18185 20 1 15.8546 1 10.6909L10.3092 10.691L10.3092 20Z" />
          <path fill="#3ebeb0" d="M10.3092 10.691L18.7819 10.6909V20H10.3092L10.3092 10.691Z" />
          <path fill="#37a595" d="M10.3092 10.691L12.2728 10.6909V20H10.3092L10.3092 10.691Z" />
        </>
      ) : (
        <>
          <path
            fill="#f3bd19"
            d="M10.4182 10.691H1.14546V0H3.94547C7.54548 0 10.4182 2.90911 10.4182 6.47277V10.691Z"
          />
          <path fill="#fff" d="M10.4182 20C5.29092 20 1.10907 15.8546 1.10907 10.6909L10.4182 10.691L10.4182 20Z" />
          <path fill="#3ebeb0" d="M10.4182 10.691L18.8909 10.6909V20H10.4182L10.4182 10.691Z" />
          <path fill="#37a595" d="M10.4182 10.691L12.3819 10.6909V20H10.4182L10.4182 10.691Z" />
        </>
      )}
    </Icon>
  )
}
