'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const MetaLogo = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Meta">
    <g clipPath="url(#a)">
      <path
        d="M3.728 11.623c0 .611.134 1.079.31 1.362a1.06 1.06 0 0 0 .922.528c.45 0 .863-.111 1.657-1.21.637-.88 1.387-2.112 1.892-2.89L9.363 8.1c.594-.91 1.28-1.924 2.07-2.612.642-.559 1.336-.87 2.034-.87 1.172 0 2.289.679 3.144 1.952.935 1.394 1.39 3.15 1.39 4.963 0 1.077-.212 1.869-.574 2.494-.348.605-1.032 1.21-2.177 1.21v-1.724c.98 0 1.224-.9 1.224-1.931 0-1.47-.343-3.099-1.098-4.264-.536-.826-1.23-1.33-1.994-1.33-.826 0-1.491.622-2.239 1.732-.397.59-.805 1.309-1.263 2.12l-.504.89c-1.012 1.793-1.269 2.202-1.775 2.876-.886 1.186-1.644 1.63-2.641 1.63-1.184 0-1.932-.512-2.393-1.283C2.186 13.324 2 12.499 2 11.559z"
        fill="#0081FB"
      />
      <path
        d="M3.363 6.692c.792-1.22 1.935-2.074 3.247-2.074.76 0 1.514.223 2.303.868.862.703 1.78 1.861 2.928 3.77l.411.685c.993 1.652 1.558 2.501 1.888 2.903.425.514.723.667 1.11.667.98 0 1.224-.9 1.224-1.931l1.524-.048c0 1.077-.212 1.869-.574 2.494-.345.606-1.029 1.21-2.174 1.21-.713 0-1.344-.154-2.041-.812-.537-.505-1.164-1.401-1.646-2.207l-1.435-2.395c-.72-1.202-1.38-2.098-1.763-2.502-.411-.439-.94-.966-1.783-.966-.683 0-1.262.479-1.748 1.211z"
        fill="url(#b)"
      />
      <path
        d="M6.582 6.354c-.683 0-1.262.479-1.748 1.211-.686 1.035-1.106 2.576-1.106 4.058 0 .611.134 1.079.31 1.362l-1.474.968C2.186 13.324 2 12.499 2 11.559c0-1.71.47-3.491 1.363-4.867.792-1.22 1.935-2.074 3.247-2.074z"
        fill="url(#c)"
      />
    </g>
    <defs>
      <linearGradient
        gradientUnits="userSpaceOnUse"
        id="b"
        x1="5.469"
        x2="16.485"
        y1="9.652"
        y2="10.209"
      >
        <stop stopColor="#0064E1" />
        <stop offset=".4" stopColor="#0064E1" />
        <stop offset=".83" stopColor="#0073EE" />
        <stop offset="1" stopColor="#0082FB" />
      </linearGradient>
      <linearGradient
        gradientUnits="userSpaceOnUse"
        id="c"
        x1="4.305"
        x2="4.305"
        y1="12.345"
        y2="8.287"
      >
        <stop stopColor="#0082FB" />
        <stop offset="1" stopColor="#0064E0" />
      </linearGradient>
      <clipPath id="a">
        <path d="M2 2h16v16H2z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
