'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const MistralLogo = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <path
      fill="#000"
      d="M7.472 11.401h-2.69l.001-2.689h2.69zm2.689 2.689h-2.69l.001-2.689h2.691zm.002-2.689h-2.69V8.712h2.691z"
    />
    <path
      fill="#000"
      d="M12.853 11.401h-2.69l.001-2.689h2.691zm-5.38-2.689h-2.69l.001-2.689h2.691zm5.381 0h-2.69l.001-2.689h2.69zm-8.072 2.689h-2.69l.001-2.689h2.69z"
    />
    <path
      fill="#000"
      d="M4.783 8.712h-2.69l.001-2.689h2.69zm.001-2.689h-2.69l.001-2.689h2.69zm10.762 0h-2.69l.001-2.689h2.691zM4.781 14.09h-2.69l.001-2.689h2.69zm-.001 2.689H2.089l.001-2.689h2.691zm10.763-5.378h-2.69l.001-2.689h2.691zm.001-2.689h-2.69l.001-2.689h2.691zm-.002 5.378h-2.69l.001-2.689h2.69zm-.001 2.689H12.85l.002-2.689h2.69z"
    />
    <path fill="#ff7000" d="M8.59 11.4H5.9l.002-2.688h2.69z" />
    <path fill="#ff4900" d="M11.28 14.09H8.59l.001-2.69h2.69z" />
    <path fill="#ff7000" d="M11.281 11.4h-2.69V8.713h2.691zm2.691 0h-2.69V8.713h2.69z" />
    <path fill="#ffa300" d="M8.592 8.712h-2.69l.001-2.69h2.69zm5.381 0h-2.69l.001-2.69h2.691z" />
    <path fill="#ff7000" d="M5.9 11.4H3.21l.001-2.688h2.69z" />
    <path fill="#ffa300" d="M5.902 8.712h-2.69v-2.69h2.69z" />
    <path fill="#ffce00" d="M5.903 6.022h-2.69l.001-2.689h2.69zm10.762 0h-2.69l.001-2.689h2.691z" />
    <path fill="#ff4900" d="M5.9 14.09H3.208l.001-2.69H5.9z" />
    <path fill="#ff0107" d="M5.898 16.78h-2.69v-2.69H5.9z" />
    <path fill="#ff7000" d="M16.663 11.4h-2.69V8.713h2.69z" />
    <path fill="#ffa300" d="M16.664 8.712h-2.69v-2.69h2.691z" />
    <path fill="#ff4900" d="M16.66 14.09h-2.69l.002-2.69h2.69z" />
    <path fill="#ff0107" d="M16.66 16.78h-2.691l.001-2.69h2.69z" />
  </Icon>
)

MistralLogo.displayName = 'MistralLogo'
