'use client'

import { useTheme } from '@ultraviolet/themes'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const OpenVpnLogo = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => {
  const { theme } = useTheme()
  const isLight = theme === 'light'

  return (
    <Icon {...props} title="OpenVpnLogo">
      {isLight ? (
        <>
          <g>
            <path
              d="M18 10.1692C18 5.65966 14.3067 2.00391 9.74986 2.00391C5.19498 2.00391 1.5 5.65966 1.5 10.1692C1.5 13.1647 3.13533 15.7751 5.56398 17.1979L6.09286 13.6978C5.30917 12.8345 4.82818 11.6963 4.82818 10.4442C4.82818 7.75396 7.03229 5.57236 9.74986 5.57236C12.4694 5.57236 14.6718 7.75396 14.6718 10.4442C14.6718 11.7076 14.185 12.8537 13.3901 13.7168L13.9168 17.2094C16.3567 15.7902 18 13.174 18 10.1692V10.1692Z"
              fill="#FF7A24"
            />
            <path
              d="M10.6552 12.6387L11.6574 17.9962H7.78544L8.78376 12.6481C7.79672 12.2744 7.09119 11.3295 7.09119 10.2142C7.09119 8.77214 8.26286 7.60352 9.70612 7.60352C11.1516 7.60352 12.3211 8.77214 12.3211 10.2142C12.3211 11.3202 11.629 12.2591 10.6552 12.6387V12.6387Z"
              fill="#123467"
            />
          </g>
          <defs>
            <clipPath id="clip0_341_650">
              <rect fill="white" transform="translate(1.5 2)" />
            </clipPath>
          </defs>
        </>
      ) : (
        <>
          <g>
            <path
              d="M20 10.2049C20 4.73883 15.5232 0.307617 9.99983 0.307617C4.47876 0.307617 0 4.73883 0 10.2049C0 13.8358 1.98222 17 4.92604 18.7246L5.5671 14.482C4.61718 13.4356 4.03415 12.056 4.03415 10.5383C4.03415 7.27737 6.7058 4.63302 9.99983 4.63302C13.2962 4.63302 15.9658 7.27737 15.9658 10.5383C15.9658 12.0696 15.3758 13.4588 14.4122 14.505L15.0506 18.7386C18.0081 17.0183 20 13.8472 20 10.2049Z"
              fill="#FF7A24"
            />
            <path
              d="M11.0972 13.199L12.3119 19.6929H7.61868L8.82876 13.2103C7.63235 12.7574 6.77716 11.6121 6.77716 10.2601C6.77716 8.51221 8.19737 7.0957 9.94678 7.0957C11.6989 7.0957 13.1164 8.51221 13.1164 10.2601C13.1164 11.6008 12.2776 12.7388 11.0972 13.199Z"
              fill="white"
            />
          </g>
          <defs>
            <clipPath id="clip0_378_522">
              <rect fill="white" transform="translate(0 0.303223)" />
            </clipPath>
          </defs>
        </>
      )}
    </Icon>
  )
}

OpenVpnLogo.displayName = 'OpenVpnLogo'
