'use client'

import { useTheme } from '@ultraviolet/themes'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const OpenVpnLogo = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => {
  const { theme } = useTheme()
  const isLight = theme === 'light'

  return (
    <Icon {...props} title="OpenVpnLogo">
      {isLight ? (
        <>
          <path
            fill="#ff7a24"
            d="M18 10.17c0-4.51-3.693-8.166-8.25-8.166-4.555 0-8.25 3.656-8.25 8.165 0 2.996 1.635 5.606 4.064 7.029l.529-3.5a4.82 4.82 0 0 1-1.265-3.254c0-2.69 2.204-4.872 4.922-4.872 2.72 0 4.922 2.182 4.922 4.872a4.8 4.8 0 0 1-1.282 3.273l.527 3.492C16.357 15.79 18 13.174 18 10.17"
          />
          <path
            fill="#123467"
            d="m10.655 12.639 1.002 5.357H7.785l.999-5.348a2.61 2.61 0 0 1-1.693-2.434 2.613 2.613 0 0 1 2.615-2.61 2.61 2.61 0 0 1 2.615 2.61 2.6 2.6 0 0 1-1.666 2.425"
          />
        </>
      ) : (
        <>
          <path
            fill="#ff7a24"
            d="M20 10.205C20 4.739 15.523.308 10 .308c-5.521 0-10 4.43-10 9.897 0 3.63 1.982 6.795 4.926 8.52l.641-4.243a5.85 5.85 0 0 1-1.533-3.944c0-3.26 2.672-5.905 5.966-5.905 3.296 0 5.966 2.644 5.966 5.905 0 1.532-.59 2.92-1.554 3.967l.639 4.234C18.008 17.019 20 13.847 20 10.205"
          />
          <path
            fill="#fff"
            d="m11.097 13.199 1.215 6.494H7.619l1.21-6.483a3.16 3.16 0 0 1-2.052-2.95 3.17 3.17 0 0 1 3.17-3.164 3.166 3.166 0 0 1 3.17 3.164c0 1.34-.84 2.479-2.02 2.939"
          />
        </>
      )}
    </Icon>
  )
}

OpenVpnLogo.displayName = 'OpenVpnLogo'
