'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PowerBiLogo = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="PowerBiLogo">
    <g clipPath="url(#clip0_116_656025)">
      <path
        fill="url(#paint0_linear_116_656025)"
        d="M15.7404 2H11.4991C11.1344 2 10.8388 2.29563 10.8388 2.66032V17.3397C10.8388 17.7044 11.1344 18 11.4991 18H15.7404C16.1051 18 16.4007 17.7044 16.4007 17.3397V2.66032C16.4007 2.29563 16.1051 2 15.7404 2Z"
      />
      <g filter="url(#filter0_d_116_656025)">
        <path
          fill="#000"
          d="M13.1243 17.3397V18H12.464H8.22276C7.85807 18 7.56244 17.7044 7.56244 17.3397V6.64762C7.56244 6.28294 7.85807 5.9873 8.22276 5.9873H12.464C12.8287 5.9873 13.1243 6.28294 13.1243 6.64762V17.3397Z"
        />
      </g>
      <path
        fill="url(#paint1_linear_116_656025)"
        d="M13.1243 17.3397V18H12.464H8.22276C7.85807 18 7.56244 17.7044 7.56244 17.3397V6.64762C7.56244 6.28294 7.85807 5.9873 8.22276 5.9873H12.464C12.8287 5.9873 13.1243 6.28294 13.1243 6.64762V17.3397Z"
      />
      <path
        fill="url(#paint2_linear_116_656025)"
        fillRule="evenodd"
        d="M9.89906 17.3397V18H9.23875H4.99748C4.63279 18 4.33716 17.7044 4.33716 17.3397V10.6603C4.33716 10.2956 4.63279 10 4.99748 10H9.23875C9.60343 10 9.89906 10.2956 9.89906 10.6603V17.3397Z"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <linearGradient id="paint0_linear_116_656025" x1="13.62" x2="13.62" y1="2" y2="18" gradientUnits="userSpaceOnUse">
        <stop stopColor="#ebbb14" />
        <stop offset="1" stopColor="#b25400" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_116_656025"
        x1="10.343"
        x2="10.343"
        y1="5.987"
        y2="18"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#f9e583" />
        <stop offset="1" stopColor="#de9800" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_116_656025"
        x1="7.118"
        x2="7.118"
        y1="10"
        y2="18"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#f9e68b" />
        <stop offset="1" stopColor="#f3cd32" />
      </linearGradient>
      <filter
        id="filter0_d_116_656025"
        x="7.562"
        y="5.733"
        colorInterpolationFilters="sRGB"
        filterUnits="userSpaceOnUse"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" />
        <feOffset dx=".508" dy=".254" />
        <feGaussianBlur stdDeviation=".254" />
        <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.0530212 0" />
        <feBlend in2="BackgroundImageFix" result="effect1_dropShadow_116_656025" />
        <feBlend in="SourceGraphic" in2="effect1_dropShadow_116_656025" result="shape" />
      </filter>
    </defs>
  </Icon>
)
