/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://scaleway-assets.s3.fr-par.scw.cloud/illustrations'

const webHostingContent = `${BASE_URL}/products/webHosting/web-hosting-content.webp`
const webHostingKeyvisual = `${BASE_URL}/products/webHosting/web-hosting-keyvisual.webp`
const webHostingOriginal = `${BASE_URL}/products/webHosting/web-hosting-original.webp`
const webHostingWire = `${BASE_URL}/products/webHosting/web-hosting-wire.svg`

export {
  webHostingContent,
  webHostingKeyvisual,
  webHostingOriginal,
  webHostingWire,
}
