import { createTheme } from '../index'

const newTheme = {
  contrasts: {
    neutral: {
      100: '#ff0000',
      1000: '#ff0000',
    },
    primary: {
      100: '#ffffff',
      300: '#ffffff',
      500: '#ffffff',
      900: '#ffffff',
    },
  },
  radii: {
    default: '1px',
    large: '2px',
  },
  space: {
    0: '6px',
    9: '600px',
  },
}

describe('createTheme', () => {
  it('should give correct array of ids', () => {
    expect(createTheme(newTheme)).toEqual({
      /* eslint-disable sort-keys */
      colors: {
        danger: {
          background: '#ffe1e7',
          backgroundDisabled: '#ffe1e7',
          backgroundHover: '#ffe1e7',
          backgroundStrong: '#ef5774',
          backgroundStrongDisabled: '#ef5774',
          backgroundStrongHover: '#ef5774',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#ef5774',
          border: '#ef5774',
          borderDisabled: '#ef5774',
          borderHover: '#ef5774',
          borderStrong: '#ef5774',
          borderStrongDisabled: '#ef5774',
          borderStrongHover: '#ef5774',
          borderWeak: '#ef5774',
          borderWeakDisabled: '#ef5774',
          borderWeakHover: '#ef5774',
          text: '#ef5774',
          textDisabled: '#ef5774',
          textHover: '#ef5774',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#ef5774',
          textWeakDisabled: '#ef5774',
          textWeakHover: '#ffe1e7',
        },
        info: {
          background: '#e4edff',
          backgroundDisabled: '#e4edff',
          backgroundHover: '#e4edff',
          backgroundStrong: '#3f6ed8',
          backgroundStrongDisabled: '#3f6ed8',
          backgroundStrongHover: '#3f6ed8',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#3f6ed8',
          border: '#3f6ed8',
          borderDisabled: '#3f6ed8',
          borderHover: '#3f6ed8',
          borderStrong: '#3f6ed8',
          borderStrongDisabled: '#3f6ed8',
          borderStrongHover: '#3f6ed8',
          borderWeak: '#3f6ed8',
          borderWeakDisabled: '#3f6ed8',
          borderWeakHover: '#3f6ed8',
          text: '#3f6ed8',
          textDisabled: '#3f6ed8',
          textHover: '#3f6ed8',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#3f6ed8',
          textWeakDisabled: '#3f6ed8',
          textWeakHover: '#e4edff',
        },
        neutral: {
          background: '#f6f5f7',
          backgroundDisabled: '#f6f5f7',
          backgroundHover: '#f6f5f7',
          backgroundStrong: '#4a4f62',
          backgroundStrongDisabled: '#4a4f62',
          backgroundStrongHover: '#4a4f62',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#4a4f62',
          border: '#4a4f62',
          borderDisabled: '#4a4f62',
          borderHover: '#4a4f62',
          borderStrong: '#4a4f62',
          borderStrongDisabled: '#4a4f62',
          borderStrongHover: '#4a4f62',
          borderWeak: '#4a4f62',
          borderWeakDisabled: '#4a4f62',
          borderWeakHover: '#4a4f62',
          text: '#4a4f62',
          textDisabled: '#4a4f62',
          textHover: '#4a4f62',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#d4dae7',
          textWeakDisabled: '#d4dae7',
          textWeakHover: '#ff0000',
        },
        primary: {
          background: '#ffffff',
          backgroundDisabled: '#ffffff',
          backgroundHover: '#ffffff',
          backgroundStrong: '#4f0599',
          backgroundStrongDisabled: '#4f0599',
          backgroundStrongHover: '#4f0599',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#4f0599',
          border: '#4f0599',
          borderDisabled: '#4f0599',
          borderHover: '#4f0599',
          borderStrong: '#4f0599',
          borderStrongDisabled: '#4f0599',
          borderStrongHover: '#4f0599',
          borderWeak: '#4f0599',
          borderWeakDisabled: '#4f0599',
          borderWeakHover: '#4f0599',
          text: '#4f0599',
          textDisabled: '#4f0599',
          textHover: '#4f0599',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#4f0599',
          textWeakDisabled: '#4f0599',
          textWeakHover: '#ffffff',
        },
        secondary: {
          background: '#ae5df6',
          backgroundDisabled: '#ae5df6',
          backgroundHover: '#ae5df6',
          backgroundStrong: '#ae5df6',
          backgroundStrongDisabled: '#ae5df6',
          backgroundStrongHover: '#ae5df6',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#ae5df6',
          border: '#ae5df6',
          borderDisabled: '#ae5df6',
          borderHover: '#ae5df6',
          borderStrong: '#ae5df6',
          borderStrongDisabled: '#ae5df6',
          borderStrongHover: '#ae5df6',
          borderWeak: '#ae5df6',
          borderWeakDisabled: '#ae5df6',
          borderWeakHover: '#ae5df6',
          text: '#ae5df6',
          textDisabled: '#ae5df6',
          textHover: '#ae5df6',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#ae5df6',
          textWeakDisabled: '#ae5df6',
          textWeakHover: '#ae5df6',
        },
        success: {
          background: '#cdfcf1',
          backgroundDisabled: '#cdfcf1',
          backgroundHover: '#cdfcf1',
          backgroundStrong: '#45d6b5',
          backgroundStrongDisabled: '#45d6b5',
          backgroundStrongHover: '#45d6b5',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#45d6b5',
          border: '#45d6b5',
          borderDisabled: '#45d6b5',
          borderHover: '#45d6b5',
          borderStrong: '#45d6b5',
          borderStrongDisabled: '#45d6b5',
          borderStrongHover: '#45d6b5',
          borderWeak: '#45d6b5',
          borderWeakDisabled: '#45d6b5',
          borderWeakHover: '#45d6b5',
          text: '#45d6b5',
          textDisabled: '#45d6b5',
          textHover: '#45d6b5',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#45d6b5',
          textWeakDisabled: '#45d6b5',
          textWeakHover: '#cdfcf1',
        },
        warning: {
          background: '#ffefe6',
          backgroundDisabled: '#ffefe6',
          backgroundHover: '#ffefe6',
          backgroundStrong: '#ff8c69',
          backgroundStrongDisabled: '#ff8c69',
          backgroundStrongHover: '#ff8c69',
          backgroundWeak: '#ff0000',
          backgroundWeakDisabled: '#ff0000',
          backgroundWeakHover: '#ff8c69',
          border: '#ff8c69',
          borderDisabled: '#ff8c69',
          borderHover: '#ff8c69',
          borderStrong: '#ff8c69',
          borderStrongDisabled: '#ff8c69',
          borderStrongHover: '#ff8c69',
          borderWeak: '#ff8c69',
          borderWeakDisabled: '#ff8c69',
          borderWeakHover: '#ff8c69',
          text: '#ff8c69',
          textDisabled: '#ff8c69',
          textHover: '#ff8c69',
          textStrong: '#ff0000',
          textStrongDisabled: '#ff0000',
          textStrongHover: '#ff0000',
          textWeak: '#ff8c69',
          textWeakDisabled: '#ff8c69',
          textWeakHover: '#ffefe6',
        },
      },
      colorsDeprecated: {
        beta: '#ff8c69',
        black: '#000',
        blue: '#3f6ed8',
        chartGreen: '#33BBB3',
        chartNegativeRed: '#ef5774',
        chartPurple: '#9B83F9',
        crimson: '#cf0f34',
        darkBlue: '#2f52a1',
        foam: '#cdfcf1',
        gold: '#ffd536',
        gray100: '#f6f5f7',
        gray200: '#eeeeff',
        gray300: '#dce1eb',
        gray350: '#d4dae7',
        gray50: '#fafafb',
        gray550: '#b2b6c3',
        gray700: '#4a4f62',
        gray950: '#151a2d',
        green: '#45d6b5',
        info: '#3f6ed8',
        lightViolet: '#a365f6',
        ngray300: '#dbdbdf',
        orange: '#ff8c69',
        pippin: '#ffe1e7',
        primary: '#4f0599',
        red: '#ef5774',
        serenade: '#ffefe6',
        shadow: '#a5a5cd',
        success: '#45d6b5',
        transparent: 'transparent',
        violet: '#4f0599',
        warning: '#ef5774',
        white: '#fff',
        zumthor: '#e4edff',
      },
      fonts: {
        monospace:
          "'Lucida Console', Monaco, 'Courier New', Courier, monospace",
        sansSerif: 'Asap, System, sans-serif',
      },
      radii: {
        default: '1px',
        large: '2px',
      },
      screens: {
        large: 992,
        medium: 768,
        small: 576,
        xlarge: 1200,
        xsmall: 0,
      },
      space: {
        '0': '6px',
        '9': '600px',
      },
      /* eslint-enable sort-keys */
    })
  })
})
