import { extendTheme } from '../index'

describe('extendTheme', () => {
  it('should give correct merge theme values', () => {
    expect(
      extendTheme({
        extendedTheme: {
          colors: {
            danger: {
              background: '#ffffff',
            },
            neutral: {
              background: '#ffffff',
              backgroundStrong: '#ffffff',
            },
          },
        },
      }),
    ).toEqual(
      /* eslint-disable sort-keys */
      {
        colorsDeprecated: {
          beta: '#ff8c69',
          black: '#000',
          blue: '#3f6ed8',
          chartGreen: '#33BBB3',
          chartNegativeRed: '#ef5774',
          chartPurple: '#9B83F9',
          crimson: '#cf0f34',
          darkBlue: '#2f52a1',
          foam: '#cdfcf1',
          gold: '#ffd536',
          gray50: '#fafafb',
          gray100: '#f6f5f7',
          gray200: '#eeeeff',
          gray300: '#dce1eb',
          gray350: '#d4dae7',
          gray550: '#b2b6c3',
          gray700: '#4a4f62',
          gray950: '#151a2d',
          green: '#45d6b5',
          info: '#3f6ed8',
          lightViolet: '#a365f6',
          ngray300: '#dbdbdf',
          orange: '#ff8c69',
          pippin: '#ffe1e7',
          primary: '#4f0599',
          red: '#ef5774',
          serenade: '#ffefe6',
          shadow: '#a5a5cd',
          success: '#45d6b5',
          transparent: 'transparent',
          violet: '#4f0599',
          warning: '#ef5774',
          white: '#fff',
          zumthor: '#e4edff',
        },
        colors: {
          danger: {
            background: '#ffffff',
            backgroundStrong: '#DD3252',
            backgroundWeak: '#ffffff',
            border: '#DD3252',
            borderStrong: '#ffffff',
            borderWeak: '#DD3252',
            text: '#DD3252',
            textStrong: '#ffffff',
            textWeak: '#DD3252',
          },
          info: {
            background: '#E1EBFF',
            backgroundStrong: '#3F6ED8',
            backgroundWeak: '#ffffff',
            border: '#3F6ED8',
            borderStrong: '#ffffff',
            borderWeak: '#3F6ED8',
            text: '#3F6ED8',
            textStrong: '#ffffff',
            textWeak: '#3F6ED8',
          },
          neutral: {
            background: '#ffffff',
            backgroundStrong: '#ffffff',
            backgroundStronger: '#4a4f62',
            backgroundWeak: '#ffffff',
            border: '#e6e9f0',
            borderStrong: '#d4dae7',
            borderStronger: '#ffffff',
            borderWeak: '#d4dae7',
            text: '#4a4f62',
            textStrong: '#151a2d',
            textStronger: '#ffffff',
            textWeak: '#b2b6c3',
          },
          primary: {
            background: '#eeeeff',
            backgroundStrong: '#4f0599',
            backgroundWeak: '#ffffff',
            border: '#4f0599',
            borderStrong: '#ffffff',
            borderWeak: '#4f0599',
            text: '#4f0599',
            textStrong: '#ffffff',
            textWeak: '#4f0599',
          },
          secondary: { backgroundStrong: '#A365F6' },
          success: {
            background: '#EAFFFB',
            backgroundStrong: '#22C8A2',
            backgroundWeak: '#ffffff',
            border: '#22C8A2',
            borderStrong: '#ffffff',
            borderWeak: '#22C8A2',
            text: '#22C8A2',
            textStrong: '#ffffff',
            textWeak: '#22C8A2',
          },
          warning: {
            background: '#FFEFE6',
            backgroundStrong: '#FF8C69',
            backgroundWeak: '#ffffff',
            border: '#FF8C69',
            borderStrong: '#ffffff',
            borderWeak: '#FF8C69',
            text: '#FF8C69',
            textStrong: '#ffffff',
            textWeak: '#FF8C69',
          },
        },
        fonts: {
          monospace:
            "'Lucida Console', Monaco, 'Courier New', Courier, monospace",
          sansSerif: 'Asap, System, sans-serif',
        },
        space: {
          '0': '0',
          '1': '8px',
          '2': '16px',
          '3': '24px',
          '4': '32px',
          '5': '40px',
          '6': '48px',
          '7': '56px',
          '8': '64px',
          '9': '72px',
          '0.25': '2px',
          '0.5': '4px',
          '0.75': '6px',
          '2.25': '18px',
        },
        screens: {
          xsmall: 0,
          small: 576,
          medium: 768,
          large: 992,
          xlarge: 1200,
        },
        radii: { none: '0', default: '4px', large: '8px' },
      },
    )
    /* eslint-enable sort-keys */
  })
})
