/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const Labs = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="Labs">
      <path
        fill="#A365F6"
        d="M8.011 6c-.559.064-.99.528-1.011 1.09v3.69c0 .248.098.465.26.627.162.162.375.26.623.26.485 0 .883-.4.883-.886V8.438c0-.367.302-.67.669-.67h1.151a.862.862 0 0 0 .623-.259.896.896 0 0 0 .26-.635c0-.486-.418-.874-.904-.874zm3.947 8.419c.559-.065.99-.529 1.01-1.09v-3.69a.874.874 0 0 0-.259-.627.867.867 0 0 0-.623-.26c-.486 0-.883.4-.883.886v2.343a.673.673 0 0 1-.669.669H9.383a.862.862 0 0 0-.624.26.896.896 0 0 0-.26.635.904.904 0 0 0 .905.874z"
        className="fillStrong"
      />
      <path
        fill="#4F0599"
        d="M17 17.5a1 1 0 0 1-1 1H4a1 1 0 1 1 0-2h12a1 1 0 0 1 1 1M4 7.5a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1m12 0a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1"
        className="fill"
        clipRule="evenodd"
        fillRule="evenodd"
      />
      <path
        fill="#4F0599"
        d="M10 3.5a5 5 0 0 0-5 5H3a7 7 0 0 1 14 0h-2a5 5 0 0 0-5-5"
        className="fill"
        clipRule="evenodd"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
