FROM node:18.12 as builder
WORKDIR /app
RUN corepack enable

# Install scw-ui
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build
RUN pnpm install --frozen-lockfile

# Build website
RUN pnpm run build:website

# Serve website
FROM joseluisq/static-web-server:2

WORKDIR /workspace

COPY --from=builder /app/website/out ./public
