strictDepBuilds: true
engineStrict: true

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@scaleway/*'

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  msgpackr-extract: false
  sharp: false

trustPolicy: off

blockExoticSubdeps: true

autoInstallPeers: true
savePrefix: ''
strictPeerDependencies: false

packages:
  - 'packages/*'
  - 'utils/*'
  - 'examples/*'
  - 'e2e'

pmOnFail: error
# Needed as we run a pnpm install after building packages
optimisticRepeatInstall: false

overrides:
  vite: "catalog:"
  vitest: "catalog:"

catalog:
  vite: 8.1.5
  vitest: 4.1.10


peerDependencyRules:
  allowedVersions:
    '@types/react': 18 || 19

supportedArchitectures:
  cpu: [ arm64, current ]
  os: [ darwin, current ]
