/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const auditTrailContent = `${BASE_URL}/products/auditTrail/audit-trail-content.webp`
const auditTrailKeyvisual = `${BASE_URL}/products/auditTrail/audit-trail-keyvisual.webp`
const auditTrailOriginal = `${BASE_URL}/products/auditTrail/audit-trail-original.webp`
const auditTrailWire = `${BASE_URL}/products/auditTrail/audit-trail-wire.svg`

export {
  auditTrailContent,
  auditTrailKeyvisual,
  auditTrailOriginal,
  auditTrailWire,
}
