/* Generated file, please do not edit here */
export default {
  danger: {
    background: 'danger.200',
    backgroundStrong: 'danger.800',
    backgroundWeak: 'neutral.100',
    border: 'danger.800',
    borderStrong: 'neutral.100',
    borderWeak: 'danger.800',
    text: 'danger.800',
    textStrong: 'neutral.100',
    textWeak: 'danger.800',
  },
  info: {
    background: 'info.200',
    backgroundStrong: 'info.800',
    backgroundWeak: 'neutral.100',
    border: 'info.800',
    borderStrong: 'neutral.100',
    borderWeak: 'info.800',
    text: 'info.800',
    textStrong: 'neutral.100',
    textWeak: 'info.800',
  },
  neutral: {
    background: 'neutral.200',
    backgroundStrong: 'neutral.300',
    backgroundStronger: 'neutral.800',
    backgroundWeak: 'neutral.100',
    border: 'neutral.400',
    borderStrong: 'neutral.500',
    borderStronger: 'neutral.100',
    borderWeak: 'neutral.500',
    text: 'neutral.800',
    textStrong: 'neutral.900',
    textStronger: 'neutral.100',
    textWeak: 'neutral.700',
  },
  primary: {
    background: 'primary.200',
    backgroundStrong: 'primary.800',
    backgroundWeak: 'neutral.100',
    border: 'primary.800',
    borderStrong: 'neutral.100',
    borderWeak: 'primary.800',
    text: 'primary.800',
    textStrong: 'neutral.100',
    textWeak: 'primary.800',
  },
  secondary: {
    backgroundStrong: 'secondary.800',
  },
  success: {
    background: 'success.200',
    backgroundStrong: 'success.800',
    backgroundWeak: 'neutral.100',
    border: 'success.800',
    borderStrong: 'neutral.100',
    borderWeak: 'success.800',
    text: 'success.800',
    textStrong: 'neutral.100',
    textWeak: 'success.800',
  },
  warning: {
    background: 'warning.200',
    backgroundStrong: 'warning.800',
    backgroundWeak: 'neutral.100',
    border: 'warning.800',
    borderStrong: 'neutral.100',
    borderWeak: 'warning.800',
    text: 'warning.800',
    textStrong: 'neutral.100',
    textWeak: 'warning.800',
  },
}
