/**
 * This file is automatically generated from /utils/scripts/uploadIllustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const fileStorageContent = `${BASE_URL}/products/fileStorage/file-storage-content.webp`
const fileStorageKeyvisual = `${BASE_URL}/products/fileStorage/file-storage-keyvisual.webp`
const fileStorageOriginal = `${BASE_URL}/products/fileStorage/file-storage-original.webp`
const fileStorageWire = `${BASE_URL}/products/fileStorage/file-storage-wire.svg`

export {
  fileStorageContent,
  fileStorageKeyvisual,
  fileStorageOriginal,
  fileStorageWire,
}
