/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

import * as accountExperience from './accountExperience'
import * as apiGateway from './apiGateway'
import * as appleSilicon from './appleSilicon'
import * as auditTrail from './auditTrail'
import * as blockStorage from './blockStorage'
import * as cli from './cli'
import * as cloudEssentials from './cloudEssentials'
import * as cockpit from './cockpit'
import * as containerRegistry from './containerRegistry'
import * as containers from './containers'
import * as costManager from './costManager'
import * as dataWarehouse from './dataWarehouse'
import * as dedibox from './dedibox'
import * as dediboxVps from './dediboxVps'
import * as dedilink from './dedilink'
import * as distributedDataLab from './distributedDataLab'
import * as domainsAndDns from './domainsAndDns'
import * as edgeServices from './edgeServices'
import * as elasticMetal from './elasticMetal'
import * as environmentalFootprintCalculator from './environmentalFootprintCalculator'
import * as fileStorage from './fileStorage'
import * as functions from './functions'
import * as generativeApi from './generativeApi'
import * as iam from './iam'
import * as inference from './inference'
import * as instance from './instance'
import * as interlink from './interlink'
import * as iotHub from './iotHub'
import * as ipam from './ipam'
import * as ipfsNaming from './ipfsNaming'
import * as ipfsPinning from './ipfsPinning'
import * as jero from './jero'
import * as k8sKapsule from './k8sKapsule'
import * as k8sKosmos from './k8sKosmos'
import * as kafka from './kafka'
import * as kms from './kms'
import * as loadBalancers from './loadBalancers'
import * as localStorage from './localStorage'
import * as mailbox from './mailbox'
import * as managedDatabase from './managedDatabase'
import * as managedSearchDatabase from './managedSearchDatabase'
import * as mongoDB from './mongoDB'
import * as moshiInference from './moshiInference'
import * as nabu from './nabu'
import * as nats from './nats'
import * as objectStorage from './objectStorage'
import * as publicGateway from './publicGateway'
import * as quantum from './quantum'
import * as quantumApplication from './quantumApplication'
import * as redis from './redis'
import * as savingsPlan from './savingsPlan'
import * as secretManager from './secretManager'
import * as serverlessDB from './serverlessDB'
import * as serverlessJob from './serverlessJob'
import * as sns from './sns'
import * as sqs from './sqs'
import * as supportPlans from './supportPlans'
import * as terraform from './terraform'
import * as transactionalEmail from './transactionalEmail'
import * as vpc from './vpc'
import * as vpn from './vpn'
import * as waf from './waf'
import * as webHosting from './webHosting'
import * as webPlatform from './webPlatform'

export {
  accountExperience,
  apiGateway,
  appleSilicon,
  auditTrail,
  blockStorage,
  cli,
  cloudEssentials,
  cockpit,
  containerRegistry,
  containers,
  costManager,
  dataWarehouse,
  dedibox,
  dediboxVps,
  dedilink,
  distributedDataLab,
  domainsAndDns,
  edgeServices,
  elasticMetal,
  environmentalFootprintCalculator,
  fileStorage,
  functions,
  generativeApi,
  iam,
  inference,
  instance,
  interlink,
  iotHub,
  ipam,
  ipfsNaming,
  ipfsPinning,
  jero,
  k8sKapsule,
  k8sKosmos,
  kafka,
  kms,
  loadBalancers,
  localStorage,
  mailbox,
  managedDatabase,
  managedSearchDatabase,
  mongoDB,
  moshiInference,
  nabu,
  nats,
  objectStorage,
  publicGateway,
  quantum,
  quantumApplication,
  redis,
  savingsPlan,
  secretManager,
  serverlessDB,
  serverlessJob,
  sns,
  sqs,
  supportPlans,
  terraform,
  transactionalEmail,
  vpc,
  vpn,
  waf,
  webHosting,
  webPlatform,
}
