/* Generated tokens from figma. Please do not edit here. */
export default {
  colors: {
    danger: {
      background: '#FFE1E7',
      backgroundStrong: '#DD3252',
      backgroundWeak: '#ffffff',
      border: '#DD3252',
      borderStrong: '#ffffff',
      borderWeak: '#DD3252',
      text: '#DD3252',
      textStrong: '#ffffff',
      textWeak: '#DD3252',
    },
    info: {
      background: '#E1EBFF',
      backgroundStrong: '#3F6ED8',
      backgroundWeak: '#ffffff',
      border: '#3F6ED8',
      borderStrong: '#ffffff',
      borderWeak: '#3F6ED8',
      text: '#3F6ED8',
      textStrong: '#ffffff',
      textWeak: '#3F6ED8',
    },
    neutral: {
      background: '#fcfcfd',
      backgroundStrong: '#f6f6f8',
      backgroundStronger: '#4a4f62',
      backgroundWeak: '#ffffff',
      border: '#e6e9f0',
      borderStrong: '#d4dae7',
      borderStronger: '#ffffff',
      borderWeak: '#d4dae7',
      text: '#4a4f62',
      textStrong: '#151a2d',
      textStronger: '#ffffff',
      textWeak: '#b2b6c3',
    },
    primary: {
      background: '#eeeeff',
      backgroundStrong: '#4f0599',
      backgroundWeak: '#ffffff',
      border: '#4f0599',
      borderStrong: '#ffffff',
      borderWeak: '#4f0599',
      text: '#4f0599',
      textStrong: '#ffffff',
      textWeak: '#4f0599',
    },
    secondary: {
      backgroundStrong: '#A365F6',
    },
    success: {
      background: '#EAFFFB',
      backgroundStrong: '#22C8A2',
      backgroundWeak: '#ffffff',
      border: '#22C8A2',
      borderStrong: '#ffffff',
      borderWeak: '#22C8A2',
      text: '#22C8A2',
      textStrong: '#ffffff',
      textWeak: '#22C8A2',
    },
    warning: {
      background: '#FFEFE6',
      backgroundStrong: '#FF8C69',
      backgroundWeak: '#ffffff',
      border: '#FF8C69',
      borderStrong: '#ffffff',
      borderWeak: '#FF8C69',
      text: '#FF8C69',
      textStrong: '#ffffff',
      textWeak: '#FF8C69',
    },
  },
}
