/**
 * This file is automatically generated from /utils/scripts/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const serverlessDBContent = `${BASE_URL}/products/serverlessDB/serverlessDB-content.webp`
const serverlessDBKeyvisual = `${BASE_URL}/products/serverlessDB/serverlessDB-keyvisual.webp`
const serverlessDBOriginal = `${BASE_URL}/products/serverlessDB/serverlessDB-original.webp`
const serverlessDBWire = `${BASE_URL}/products/serverlessDB/serverlessDB-wire.svg`

export {
  serverlessDBContent,
  serverlessDBKeyvisual,
  serverlessDBOriginal,
  serverlessDBWire,
}
