import fs from 'node:fs'
import path from 'node:path'

const WIRE_ILLUSTRATIONS_DIR =
  'packages/illustrations/src/components/WireIllustration/__generated__'

const DYNAMIC_ILLUSTRATIONS_DIR =
  'packages/illustrations/src/components/DynamicIllustration/__generated__'
const WARNING = `/**
      * This file is automatically generated from /utils/scripts/update-illustration-components.tsx
      * PLEASE DO NOT EDIT HERE
      */`

export const updateWireIllustrations = (
  illustrations: { dir: string; category: string }[],
  baseUrl: string,
) => {
  // Delete everything inside the WIRE_ILLUSTRATIONS_DIR folder to clean
  fs.readdirSync(WIRE_ILLUSTRATIONS_DIR).forEach(file => {
    const fullPath = path.join(WIRE_ILLUSTRATIONS_DIR, file)
    if (fs.statSync(fullPath).isDirectory()) {
      fs.rmdirSync(fullPath, { recursive: true })
    } else {
      fs.unlinkSync(fullPath)
    }
  })
  const exports: string[] = []

  illustrations.forEach(element => {
    const { dir: directory, category: categorySnake } = element
    const categoryNotCapitalized = categorySnake.replace(/-./g, x =>
      x[1].toUpperCase(),
    )
    const category =
      categoryNotCapitalized.charAt(0).toUpperCase() +
      categoryNotCapitalized.slice(1)

    // Create a folder for the category
    const categoryDir = path.join(WIRE_ILLUSTRATIONS_DIR, category)
    fs.mkdirSync(categoryDir, { recursive: true })

    // Create an index.ts file for the category (if it doesn't exist)
    const indexPath = path.join(categoryDir, 'index.tsx')
    fs.writeFileSync(
      indexPath,
      `${WARNING}
      import { WireIllustration } from '../../WireIllustration'
      import type { IllustrationWireProp } from '../../WireIllustration'

      export const ${category}Wire = ({ ...props }: Omit<IllustrationWireProp, 'url'>) => (
        <WireIllustration 
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...props} 
        url="${baseUrl}/products/${directory}/${categorySnake}-wire.svg"/>
        )
      `,
    )

    exports.push(`export { ${category}Wire } from './${category}'`)
  })

  // Create the index.ts file for the WIRE_ILLUSTRATIONS_DIR folder
  const indexPath = path.join(WIRE_ILLUSTRATIONS_DIR, 'index.tsx')
  fs.writeFileSync(
    indexPath,
    `
    'use client' 
    
    ${WARNING}\n
`,
  )

  fs.appendFileSync(indexPath, exports.join('\n'))
}

const filterDynamicIllustrations = (
  dynamicIllustrations: { dir: string; category: string }[],
) => {
  // Remove -dark and -light from the names
  const bases = dynamicIllustrations.map(illustration =>
    illustration.category.replace(/-(dark|light)$/, ''),
  )

  // Keep the ones with dark & light version available
  const finalIllustrations = [...new Set(bases)].filter(
    base =>
      dynamicIllustrations.some(i => i.category === `${base}-dark`) &&
      dynamicIllustrations.some(i => i.category === `${base}-light`),
  )

  return finalIllustrations.map(base => {
    // On prend le premier dir trouvé pour cette base (dark ou light, peu importe)
    const dir =
      dynamicIllustrations.find(i => i.category.startsWith(base))?.dir ?? ''

    return { dir, category: base }
  })
}

export const updateDynamicIllustrations = (
  dynamicIllustrations: { dir: string; category: string }[],
  baseUrl: string,
) => {
  const indexPath = path.join(DYNAMIC_ILLUSTRATIONS_DIR, 'Illustrations.tsx')

  const filteredDynamicIllustrations =
    filterDynamicIllustrations(dynamicIllustrations)

  fs.writeFileSync(
    indexPath,
    `
    'use client' 
    
    ${WARNING}

    const BASE_URL = '${baseUrl}'

    ${filteredDynamicIllustrations
      .map(
        illustration => `
      const ${illustration.category}Light = \`\${BASE_URL}/various/${illustration.dir}/${illustration.category}-light.webp\`
      const ${illustration.category}Dark = \`\${BASE_URL}/various/${illustration.dir}/${illustration.category}-dark.webp\``,
      )
      .join('\n')}

    export type IllustrationsKeys = {
    ${filteredDynamicIllustrations
      .map(illustration => `${illustration.category}: string`)
      .join('\n')}
    }

    export const ILLUSTRATIONS = {
      light: {
       ${filteredDynamicIllustrations
         .map(
           illustration =>
             `${illustration.category}: ${illustration.category}Light,`,
         )
         .join('\n')}
      } satisfies IllustrationsKeys,

      dark: {
      ${filteredDynamicIllustrations
        .map(
          illustration =>
            `${illustration.category}: ${illustration.category}Dark,`,
        )
        .join('\n')}
      } satisfies IllustrationsKeys,
      }
`,
  )
}
