/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DedicatedServer = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="Dedicated-Server">
      <path
        fill="#A365F6"
        d="M10.25 14a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5H11a.75.75 0 0 1-.75-.75m0-7.7a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5H11a.75.75 0 0 1-.75-.75"
        className="fillStrong"
        clipRule="evenodd"
        fillRule="evenodd"
      />
      <path
        fill="#4F0599"
        d="M3 13.5a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v1a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1zM3 5.8a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v1a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1z"
        className="fill"
        clipRule="evenodd"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
