/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://scaleway-assets.s3.fr-par.scw.cloud/illustrations'

const snsContent = `${BASE_URL}/products/sns/sns-content.webp`
const snsKeyvisual = `${BASE_URL}/products/sns/sns-keyvisual.webp`
const snsOriginal = `${BASE_URL}/products/sns/sns-original.webp`
const snsWire = `${BASE_URL}/products/sns/sns-wire.svg`

export { snsContent, snsKeyvisual, snsOriginal, snsWire }
