/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AdjustmentsHorizontalOutlineIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M7 3.5A.75.75 0 1 0 7 5a.75.75 0 0 0 0-1.5m-2.122 0a2.25 2.25 0 0 1 4.244 0h9.128a.75.75 0 0 1 0 1.5H9.122a2.25 2.25 0 0 1-4.244 0H1.75a.75.75 0 0 1 0-1.5zM13 9.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5m-2.122 0a2.251 2.251 0 0 1 4.244 0h3.128a.75.75 0 0 1 0 1.5h-3.128a2.251 2.251 0 0 1-4.244 0H1.75a.75.75 0 0 1 0-1.5zM7 15.5A.75.75 0 1 0 7 17a.75.75 0 0 0 0-1.5m-2.122 0a2.25 2.25 0 0 1 4.244 0h9.128a.75.75 0 0 1 0 1.5H9.122a2.25 2.25 0 0 1-4.244 0H1.75a.75.75 0 0 1 0-1.5z" />
  </Icon>
)
