/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AdjustmentsHorizontalIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M10 3.94a1.94 1.94 0 1 0-3.879 0 1.94 1.94 0 0 0 3.879 0m7.03.727a.727.727 0 0 0 0-1.455h-5.333a.727.727 0 0 0 0 1.455zM5.151 3.94a.727.727 0 0 1-.727.727H2.969a.727.727 0 0 1 0-1.455h1.455c.402 0 .727.326.727.727m-.727 12.849a.727.727 0 0 0 0-1.455H2.969a.727.727 0 0 0 0 1.455zm12.606 0a.727.727 0 0 0 0-1.455h-5.333a.727.727 0 0 0 0 1.455zM9.03 10a.727.727 0 0 1-.727.727H2.969a.727.727 0 0 1 0-1.454h5.334c.401 0 .727.325.727.727m8 .727a.727.727 0 0 0 0-1.454h-1.455a.727.727 0 0 0 0 1.454zM13.879 10a1.94 1.94 0 1 0-3.88 0 1.94 1.94 0 0 0 3.88 0M10 16.06a1.94 1.94 0 1 0-3.879 0 1.94 1.94 0 0 0 3.879 0" />
  </Icon>
)
