/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ArrowUpIcon = ({ ...props }: Omit<IconProps, 'children'>) =>
  props.size === 'large' ? (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <Icon {...props}>
      <path
        fillRule="evenodd"
        d="M9.72 7.47a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 1 1-1.06 1.06l-3.72-3.72-3.72 3.72a.75.75 0 0 1-1.06-1.06z"
        clipRule="evenodd"
      />
    </Icon>
  ) : (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <Icon {...props}>
      <path
        fillRule="evenodd"
        d="M11.78 10.53a.75.75 0 0 1-1.06 0L8 7.81l-2.72 2.72a.75.75 0 1 1-1.06-1.06l3.25-3.25a.75.75 0 0 1 1.06 0l3.25 3.25a.75.75 0 0 1 0 1.06"
        clipRule="evenodd"
      />
    </Icon>
  )
