/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const BookOpenOutlineIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M10.75 16.9098C11.9579 16.0774 13.4212 15.5903 15 15.5903C15.7103 15.5903 16.3964 15.6889 17.0459 15.8726C17.272 15.9365 17.515 15.8908 17.7024 15.749C17.8899 15.6073 18 15.3859 18 15.1509V4.15088C18 3.81528 17.7771 3.52053 17.4541 3.42919C16.6731 3.20829 15.8497 3.09033 15 3.09033C13.4636 3.09033 12.016 3.47582 10.75 4.1552V16.9098Z" />
    <path d="M9.25 4.1552C7.98396 3.47582 6.5364 3.09033 5 3.09033C4.15029 3.09033 3.32689 3.20829 2.54588 3.42919C2.22295 3.52053 2 3.81528 2 4.15088V15.1509C2 15.3859 2.11014 15.6073 2.29756 15.749C2.48497 15.8908 2.728 15.9365 2.95412 15.8726C3.60361 15.6889 4.28967 15.5903 5 15.5903C6.57884 15.5903 8.04208 16.0774 9.25 16.9098V4.1552Z" />
  </Icon>
)
