/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ChatIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.15979 3.35446C6.06172 3.04807 8.01251 2.88892 10 2.88892C11.9875 2.88892 13.9383 3.04807 15.8402 3.35446C17.117 3.56014 18 4.67847 18 5.93415V10.5104C18 11.766 17.117 12.8844 15.8402 13.09C14.3331 13.3328 12.7953 13.4831 11.2328 13.5351C11.0517 13.5411 10.8847 13.6137 10.7639 13.7345L7.58252 16.9159C7.39185 17.1065 7.10511 17.1636 6.85599 17.0604C6.60687 16.9572 6.44444 16.7141 6.44444 16.4445V13.3843C5.6757 13.3099 4.9139 13.2115 4.15979 13.09C2.88302 12.8844 2 11.766 2 10.5104V5.93415C2 4.67847 2.88301 3.56014 4.15979 3.35446Z"
    />
  </Icon>
)
