/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ClockOutlineOutlineIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 3.5C6.41015 3.5 3.5 6.41015 3.5 10C3.5 13.5899 6.41015 16.5 10 16.5C13.5899 16.5 16.5 13.5899 16.5 10C16.5 6.41015 13.5899 3.5 10 3.5ZM2 10C2 5.58172 5.58172 2 10 2C14.4183 2 18 5.58172 18 10C18 14.4183 14.4183 18 10 18C5.58172 18 2 14.4183 2 10ZM10 4.41667C10.4142 4.41667 10.75 4.75245 10.75 5.16667V9.25H13.625C14.0392 9.25 14.375 9.58579 14.375 10C14.375 10.4142 14.0392 10.75 13.625 10.75H10C9.58579 10.75 9.25 10.4142 9.25 10V5.16667C9.25 4.75245 9.58579 4.41667 10 4.41667Z"
    />
  </Icon>
)
