/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CloseCircleOutlineIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M10 16.67c-3.675 0-6.67-2.995-6.67-6.67s2.995-6.67 6.67-6.67 6.67 2.995 6.67 6.67-2.995 6.67-6.67 6.67m0-15C5.39 1.67 1.67 5.39 1.67 10s3.72 8.33 8.33 8.33 8.33-3.72 8.33-8.33S14.61 1.67 10 1.67m2.16 5L10 8.83 7.84 6.67 6.67 7.84 8.83 10 6.67 12.16 7.84 13.33 10 11.17l2.16 2.16 1.17-1.17L11.17 10l2.16-2.16z" />
  </Icon>
)
