/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CreditCardIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M3.33333 4.66675C2.59695 4.66675 2 5.2637 2 6.00008V6.44453H18V6.00008C18 5.2637 17.403 4.66675 16.6667 4.66675H3.33333Z" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18 8.66675H2V14.0001C2 14.7365 2.59695 15.3334 3.33333 15.3334H16.6667C17.403 15.3334 18 14.7365 18 14.0001V8.66675ZM3.77778 12.889C3.77778 12.5208 4.07625 12.2223 4.44444 12.2223H5.77778C6.14597 12.2223 6.44444 12.5208 6.44444 12.889C6.44444 13.2572 6.14597 13.5556 5.77778 13.5556H4.44444C4.07625 13.5556 3.77778 13.2572 3.77778 12.889ZM8 12.2223C7.63181 12.2223 7.33333 12.5208 7.33333 12.889C7.33333 13.2572 7.63181 13.5556 8 13.5556H11.1111C11.4793 13.5556 11.7778 13.2572 11.7778 12.889C11.7778 12.5208 11.4793 12.2223 11.1111 12.2223H8Z"
    />
  </Icon>
)
