/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DocIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      d="M4.5 18h11a1.5 1.5 0 0 0 1.5-1.5v-13A1.5 1.5 0 0 0 15.5 2h-11A1.5 1.5 0 0 0 3 3.5v13A1.5 1.5 0 0 0 4.5 18M6.25 5.5A.75.75 0 0 1 7 4.75h3.464a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75M7 7.75a.75.75 0 0 0 0 1.5h5.469a.75.75 0 0 0 0-1.5zm-.75 3.75a.75.75 0 0 1 .75-.75h5.469a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75M7 13.75a.75.75 0 0 0 0 1.5h2.734a.75.75 0 1 0 0-1.5z"
      clipRule="evenodd"
    />
  </Icon>
)
