/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DocOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      d="M4.5 3.587v12.826a.1.1 0 0 0 .024.029.27.27 0 0 0 .178.058h10.784a.27.27 0 0 0 .178-.058.1.1 0 0 0 .024-.03V3.57a.07.07 0 0 0-.07-.07H4.701a.27.27 0 0 0-.178.058.1.1 0 0 0-.024.03m-1.5 0C3 2.622 3.856 2 4.702 2h10.915c.868 0 1.57.704 1.57 1.57v12.843c0 .965-.855 1.587-1.701 1.587H4.702C3.856 18 3 17.378 3 16.413zM6.172 6.25a.75.75 0 0 1 .75-.75V7a.75.75 0 0 1-.75-.75m.75 0V7h4.018a.75.75 0 0 0 0-1.5H6.922zm-.75 2.602a.75.75 0 0 1 .75-.75h6.344a.75.75 0 0 1 0 1.5H6.922a.75.75 0 0 1-.75-.75m0 2.473a.75.75 0 0 1 .75-.75h6.344a.75.75 0 0 1 0 1.5H6.922a.75.75 0 0 1-.75-.75m0 2.23a.75.75 0 0 1 .75-.75h3.172a.75.75 0 0 1 0 1.5H6.922a.75.75 0 0 1-.75-.75"
      clipRule="evenodd"
    />
  </Icon>
)
