/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DocOutline = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M5.587 3.5a.087.087 0 0 0-.087.087v12.827c0 .047.039.086.087.086h9.48a.086.086 0 0 0 .087-.087V9.721a1.76 1.76 0 0 0-1.76-1.76H12.28c-.876 0-1.587-.71-1.587-1.586V5.26a1.76 1.76 0 0 0-1.76-1.76zm0-1.5C4.71 2 4 2.71 4 3.587v12.827C4 17.29 4.71 18 5.587 18h9.48c.877 0 1.587-.71 1.587-1.587v-6.97A7.44 7.44 0 0 0 9.212 2zm6.43 2.203c.114.331.175.687.175 1.057v1.115c0 .048.04.087.087.087h1.115c.37 0 .726.061 1.057.175a5.97 5.97 0 0 0-2.434-2.434M6.788 12.23a.75.75 0 0 1 .75-.75h5.577a.75.75 0 0 1 0 1.5H7.538a.75.75 0 0 1-.75-.75m0 2.23a.75.75 0 0 1 .75-.75h2.789a.75.75 0 0 1 0 1.5H7.538a.75.75 0 0 1-.75-.75"
      clipRule="evenodd"
    />
  </Icon>
)
