/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

/**
 * @deprecated Use DragIcon instead.
 */
export const DragVariantIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="m22.67 12-4.49 4.5-2.51-2.5 1.98-2-1.98-1.96 2.51-2.51zM12 1.33l4.47 4.49-2.51 2.51L12 6.35l-2 1.98-2.5-2.51zm0 21.34-4.47-4.49 2.51-2.51L12 17.65l2-1.98 2.5 2.51zM1.33 12l4.49-4.5L8.33 10l-1.98 2 1.98 1.96-2.51 2.51zM12 10a2 2 0 0 1 2 2 2 2 0 0 1-2 2 2 2 0 0 1-2-2 2 2 0 0 1 2-2" />
  </Icon>
)
