/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EmailIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M3.778 4.66C2.796 4.66 2 5.456 2 6.438V7.47l7.503 3.752c.313.156.681.156.994 0L18 7.47V6.438c0-.982-.796-1.778-1.778-1.778z" />
    <path d="m18 8.96-6.907 3.454a2.44 2.44 0 0 1-2.186 0L2 8.961v4.588c0 .982.796 1.778 1.778 1.778h12.444c.982 0 1.778-.796 1.778-1.778z" />
  </Icon>
)
