/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ExpandIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M1.75 2a.75.75 0 0 1 .75.75V16.6a.75.75 0 0 1-1.5 0V2.75A.75.75 0 0 1 1.75 2m16.5 0a.75.75 0 0 1 .75.75V16.6a.75.75 0 0 1-1.5 0V2.75a.75.75 0 0 1 .75-.75M7.279 6.495a.75.75 0 0 1 0 1.06l-1.37 1.37h8.182l-1.37-1.37a.75.75 0 1 1 1.061-1.06l2.65 2.65a.75.75 0 0 1 0 1.06l-2.65 2.65a.75.75 0 0 1-1.06-1.06l1.369-1.37H5.909l1.37 1.37a.75.75 0 1 1-1.061 1.06l-2.65-2.65a.75.75 0 0 1 0-1.06l2.65-2.65a.75.75 0 0 1 1.06 0"
      clipRule="evenodd"
    />
  </Icon>
)
