/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EyeIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      d="M10.0004 12.1174C11.1699 12.1174 12.1179 11.1694 12.1179 9.99993C12.1179 8.83049 11.1699 7.88247 10.0004 7.88247C8.831 7.88247 7.88298 8.83049 7.88298 9.99993C7.88298 11.1694 8.831 12.1174 10.0004 12.1174Z"
      fill="#727683"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2.09322 10.5C1.96882 10.1767 1.96893 9.81837 2.09352 9.49519C3.3167 6.32223 6.39508 4.07104 9.99925 4.07104C13.6052 4.07104 16.6848 6.32445 17.9068 9.49989C18.0312 9.82314 18.0311 10.1815 17.9065 10.5047C16.6833 13.6776 13.6049 15.9288 10.0008 15.9288C6.39481 15.9288 3.31518 13.6754 2.09322 10.5ZM13.3887 9.99993C13.3887 11.871 11.8719 13.3879 10.0008 13.3879C8.12965 13.3879 6.61282 11.871 6.61282 9.99993C6.61282 8.12883 8.12965 6.612 10.0008 6.612C11.8719 6.612 13.3887 8.12883 13.3887 9.99993Z"
    />
  </Icon>
)
