/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const FilterIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3.44692 2.53424C5.5795 2.18275 7.76855 2 9.99978 2C12.231 2 14.4201 2.18275 16.5526 2.53424C16.8746 2.58731 17.1109 2.86568 17.1109 3.19203V5.22549C17.1109 5.75592 16.9002 6.26463 16.5251 6.6397L12.3633 10.8015C11.9883 11.1765 11.7776 11.6852 11.7776 12.2157V14.9147C11.7776 15.5223 11.5014 16.0969 11.0269 16.4765L9.30513 17.8539C9.10502 18.014 8.83085 18.0452 8.59988 17.9342C8.3689 17.8232 8.222 17.5896 8.222 17.3333V12.2157C8.222 11.6852 8.01129 11.1765 7.63622 10.8015L3.47446 6.6397C3.09939 6.26463 2.88867 5.75592 2.88867 5.22549V3.19203C2.88867 2.86568 3.12492 2.58731 3.44692 2.53424Z"
    />
  </Icon>
)
