/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const LockOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      d="M5.946 6.051a4.051 4.051 0 0 1 8.103 0v2.156a2.36 2.36 0 0 1 2.256 2.357v5.077A2.36 2.36 0 0 1 13.946 18H6.05a2.36 2.36 0 0 1-2.36-2.359v-5.077a2.36 2.36 0 0 1 2.257-2.357zm.103 3.487c-.567 0-1.026.46-1.026 1.026v5.077c0 .566.46 1.026 1.026 1.026h7.897c.567 0 1.026-.46 1.026-1.026v-5.077c0-.566-.46-1.026-1.026-1.026zm6.667-1.333H7.28V6.051a2.718 2.718 0 1 1 5.436 0z"
      clipRule="evenodd"
    />
  </Icon>
)
