/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const MoonIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      d="M7.207 2.444c.22.176.316.463.247.736a6.681 6.681 0 0 0 9.505 7.605.716.716 0 0 1 1.019.813A8.113 8.113 0 1 1 6.435 2.366a.72.72 0 0 1 .772.078"
      clipRule="evenodd"
    />
  </Icon>
)
