/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const NotificationIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.99972 2C6.68601 2 3.99972 4.68629 3.99972 8C3.99972 9.88663 3.54599 11.6651 2.74236 13.2343C2.63567 13.4426 2.63236 13.6888 2.7334 13.9C2.83445 14.1111 3.02827 14.2629 3.25744 14.3105C4.32513 14.5322 5.41157 14.7023 6.51401 14.818C6.6747 16.602 8.17396 18 9.99976 18C11.8255 18 13.3248 16.602 13.4855 14.818C14.5879 14.7023 15.6743 14.5322 16.742 14.3105C16.9712 14.2629 17.165 14.1111 17.266 13.9C17.3671 13.6888 17.3638 13.4426 17.2571 13.2343C16.4535 11.6651 15.9997 9.88663 15.9997 8C15.9997 4.68629 13.3134 2 9.99972 2ZM8.04905 14.9433C8.69453 14.9809 9.34493 15 9.99972 15C10.6545 15 11.305 14.9809 11.9505 14.9433C11.7488 15.8345 10.952 16.5 9.99976 16.5C9.04752 16.5 8.25072 15.8345 8.04905 14.9433Z"
    />
  </Icon>
)
