/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const Pen2Icon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="m3.243 14.325-1.208 3.018a.478.478 0 0 0 .622.621l3.018-1.207a3.8 3.8 0 0 0 1.285-.847L17.406 5.465a2.03 2.03 0 0 0-2.87-2.87L4.09 13.04a3.8 3.8 0 0 0-.847 1.285" />
  </Icon>
)
