/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PinIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M10.8769 2.51327C11.5612 1.82891 12.6708 1.82891 13.3551 2.51327L17.4867 6.64491C18.1711 7.32927 18.1711 8.43884 17.4867 9.1232L13.7456 12.8643C13.5044 13.1056 13.3859 13.4402 13.3874 13.7814C13.3928 14.9778 13.1099 16.1825 12.5402 17.2824C12.0748 18.181 10.882 18.2152 10.1664 17.4996L7.15964 14.4928L4.67984 16.9726C4.22352 17.429 3.48369 17.429 3.02737 16.9726C2.57105 16.5163 2.57105 15.7765 3.02737 15.3202L5.50717 12.8403L2.50035 9.8335C1.78483 9.11797 1.81901 7.92512 2.71755 7.45974C3.81754 6.89001 5.02232 6.60708 6.21879 6.6125C6.55997 6.61405 6.89465 6.49552 7.13591 6.25426L10.8769 2.51327Z" />
  </Icon>
)
