/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const UnlockOutlineIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10.4286 6.28571C10.4286 3.91878 12.3474 2 14.7143 2C17.0812 2 19 3.91878 19 6.28571V9.23214C19 9.64636 18.6642 9.98214 18.25 9.98214C17.8358 9.98214 17.5 9.64636 17.5 9.23214V6.28571C17.5 4.74721 16.2528 3.5 14.7143 3.5C13.1758 3.5 11.9286 4.74721 11.9286 6.28571V8.48719C13.2443 8.57007 14.2857 9.66341 14.2857 11V16.3036C14.2857 17.6941 13.1584 18.8214 11.7679 18.8214H3.51786C2.12728 18.8214 1 17.6941 1 16.3036V11C1 9.60943 2.12728 8.48214 3.51786 8.48214H10.4286V6.28571ZM3.51786 9.98214C2.95571 9.98214 2.5 10.4379 2.5 11V16.3036C2.5 16.8657 2.95571 17.3214 3.51786 17.3214H11.7679C12.33 17.3214 12.7857 16.8657 12.7857 16.3036V11C12.7857 10.4379 12.33 9.98214 11.7679 9.98214H3.51786Z"
    />
  </Icon>
)
