/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const WeatherNightIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M13.995 3.746c.2.006.282.26.123.381l-1.201.921a.21.21 0 0 0-.074.23l.431 1.45a.212.212 0 0 1-.324.235l-1.247-.858a.21.21 0 0 0-.24 0l-1.247.858a.212.212 0 0 1-.324-.235l.431-1.45a.21.21 0 0 0-.074-.23l-1.201-.92a.212.212 0 0 1 .123-.382l1.515-.042a.21.21 0 0 0 .195-.142l.502-1.42a.212.212 0 0 1 .4 0l.502 1.42c.03.083.107.139.194.142zm2.472 4.896c.2.005.283.26.123.382l-.563.43a.21.21 0 0 0-.075.229l.204.684a.212.212 0 0 1-.324.236l-.588-.404a.21.21 0 0 0-.24 0l-.588.404a.212.212 0 0 1-.324-.236l.204-.684a.21.21 0 0 0-.075-.23l-.563-.43a.212.212 0 0 1 .123-.38l.708-.018a.21.21 0 0 0 .195-.141l.24-.677a.212.212 0 0 1 .4 0l.24.677c.03.083.107.139.195.141z" />
    <path
      d="M7.513 4.405a.64.64 0 0 1 .22.655 5.95 5.95 0 0 0 8.463 6.771.637.637 0 0 1 .908.725 7.224 7.224 0 1 1-10.278-8.22.64.64 0 0 1 .687.07"
      clipRule="evenodd"
    />
  </Icon>
)
