/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const File = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="File">
      <g className=".Square">
        <path
          fill="#F1EEFC"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          className="fillWeak"
        />
      </g>
      <g className="File">
        <g className="icon">
          <g className="fill">
            <path
              d="M21 14a1 1 0 0 0-1 1v33a1 1 0 0 0 1 1h15a1 1 0 1 1 0 2H21a3 3 0 0 1-3-3V15a3 3 0 0 1 3-3h17.5a1 1 0 0 1 .791.389l8.5 11A1 1 0 0 1 48 24v8.5a1 1 0 1 1-2 0v-8.159L38.009 14z"
              className="fill"
              clipRule="evenodd"
              fillRule="evenodd"
            />
            <path
              d="M47 25h-1v23a1 1 0 0 1-1 1H30a1 1 0 1 0 0 2h15a3 3 0 0 0 3-3V25z"
              className="fill"
            />
            <path
              d="M37.5 22v-8.5h2V22a1 1 0 0 0 1 1H47v2h-6.5a3 3 0 0 1-3-3"
              className="fill"
              clipRule="evenodd"
              fillRule="evenodd"
            />
          </g>
          <path
            fill="#A060F6"
            d="M24.5 21a1 1 0 1 0 0 2h10a1 1 0 1 0 0-2zm0 13a1 1 0 1 0 0 2H38a1 1 0 1 0 0-2zm-1 8a1 1 0 0 1 1-1h9a1 1 0 1 1 0 2h-9a1 1 0 0 1-1-1m1-14.5a1 1 0 1 0 0 2H42a1 1 0 1 0 0-2z"
            className="fillStrong"
            clipRule="evenodd"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
  </Icon>
)
