/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PublicGateway = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="Public-Gateway">
      <g className=".Square">
        <path
          fill="#EEF"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          className="fillWeak"
        />
      </g>
      <path
        fill="#A365F6"
        d="M31 26V12.135h2V26zm17.63-5.215-10.904 6.627 1.039 1.71 10.904-6.628-1.04-1.71ZM37.689 36.287l.954-1.758 11.166 6.058-.953 1.758zM31 51.88V38h2v13.881z"
        className="fillStrong"
        clipRule="evenodd"
        fillRule="evenodd"
      />
      <path
        fill="#4F0599"
        d="M32 5a4 4 0 0 0-.2 7.995L32 13a3.988 3.988 0 0 0 2.854-1.197l13.188 7.614a4.002 4.002 0 0 0 2.877 4.435v15.296a4.002 4.002 0 0 0-2.648 5.303l-13.417 7.746a3.988 3.988 0 0 0-2.654-1.192L32 51a4 4 0 0 0-.2 7.995L32 59a4 4 0 0 0 3.855-5.07l13.594-7.85c.644.535 1.46.871 2.351.915L52 47a4 4 0 0 0 .919-7.894V23.894a4.002 4.002 0 0 0-.72-7.89L52 16c-1.291 0-2.44.612-3.171 1.561l-12.974-7.49A4.004 4.004 0 0 0 32.2 5.005zm2 50a2 2 0 1 0-4 0 2 2 0 0 0 4 0m20-12a2 2 0 1 0-4 0 2 2 0 0 0 4 0m0-23a2 2 0 1 0-4 0 2 2 0 0 0 4 0M34 9a2 2 0 1 0-4 0 2 2 0 0 0 4 0m-9 17a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H26a1 1 0 0 1-1-1v-5H11.692l4.32 3.886.082.083a1 1 0 0 1-1.42 1.404l-6.059-5.45a1 1 0 0 1-.142-1.773l6.201-5.578.091-.073a1 1 0 0 1 1.321.148l.073.091a1 1 0 0 1-.147 1.321L11.632 31H25zm2 1v10h10V27z"
        className="fill"
        clipRule="evenodd"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
