/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://scaleway-assets.s3.fr-par.scw.cloud/illustrations'

const accountBilling = `${BASE_URL}/various/documentation/account-billing.svg`
const generic = `${BASE_URL}/various/documentation/generic.svg`
const learning = `${BASE_URL}/various/documentation/learning.svg`
const writeCommunity = `${BASE_URL}/various/documentation/write-community.svg`

export { accountBilling, generic, learning, writeCommunity }
