/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const GoogleLogo = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g clipPath="url(#clip0_1710_7)">
      <path
        d="M17.04 10.1667C17.04 9.64675 16.9933 9.14675 16.9067 8.66675H10V11.5067H13.9467C13.7733 12.4201 13.2533 13.1934 12.4733 13.7134V15.5601H14.8533C16.24 14.2801 17.04 12.4001 17.04 10.1667Z"
        fill="#4285F4"
      />
      <path
        d="M10 17.3332C11.98 17.3332 13.64 16.6799 14.8534 15.5599L12.4734 13.7132C11.82 14.1532 10.9867 14.4199 10 14.4199C8.09337 14.4199 6.47337 13.1332 5.89337 11.3999H3.45337V13.2932C4.66004 15.6866 7.13337 17.3332 10 17.3332Z"
        fill="#34A853"
      />
      <path
        d="M5.89341 11.3934C5.74675 10.9534 5.66008 10.4867 5.66008 10C5.66008 9.51338 5.74675 9.04671 5.89341 8.60671V6.71338H3.45341C2.95341 7.70005 2.66675 8.81338 2.66675 10C2.66675 11.1867 2.95341 12.3 3.45341 13.2867L5.35341 11.8067L5.89341 11.3934Z"
        fill="#FBBC05"
      />
      <path
        d="M10 5.58675C11.08 5.58675 12.04 5.96008 12.8067 6.68008L14.9067 4.58008C13.6334 3.39341 11.98 2.66675 10 2.66675C7.13337 2.66675 4.66004 4.31341 3.45337 6.71341L5.89337 8.60675C6.47337 6.87341 8.09337 5.58675 10 5.58675Z"
        fill="#EA4335"
      />
    </g>
    <defs>
      <clipPath id="clip0_1710_7">
        <rect width="16" height="16" fill="white" transform="translate(2 2)" />
      </clipPath>
    </defs>
  </Icon>
)
