'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const AustriaFlag = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Austria">
    {props.disabled ? (
      <>
        <g>
          <path
            d="M23.2536 16.1741C23.736 14.8741 24 13.468 24 12.0002C24 10.5323 23.736 9.12633 23.2536 7.82629L12 6.78281L0.746391 7.82629C0.264047 9.12633 0 10.5323 0 12.0002C0 13.468 0.264047 14.8741 0.746391 16.1741L12 17.2176L23.2536 16.1741Z"
            fill="#F0F0F0"
          />
          <path
            d="M12.0001 24C17.1596 24 21.5582 20.7435 23.2537 16.1739H0.74646C2.44202 20.7435 6.84049 24 12.0001 24Z"
            fill="#454545"
          />
          <path
            d="M12.0001 0C6.84049 0 2.44202 3.2565 0.74646 7.82611H23.2537C21.5582 3.2565 17.1596 0 12.0001 0Z"
            fill="#454545"
          />
        </g>
        <defs>
          <clipPath id="clip0_3072_342">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    ) : (
      <>
        <g>
          <path
            d="M23.2536 16.1741C23.736 14.8741 24 13.468 24 12.0002C24 10.5323 23.736 9.12633 23.2536 7.82629L12 6.78281L0.746391 7.82629C0.264047 9.12633 0 10.5323 0 12.0002C0 13.468 0.264047 14.8741 0.746391 16.1741L12 17.2176L23.2536 16.1741Z"
            fill="#F0F0F0"
          />
          <path
            d="M12.0001 24C17.1596 24 21.5582 20.7435 23.2537 16.1739H0.74646C2.44202 20.7435 6.84049 24 12.0001 24Z"
            fill="#D80027"
          />
          <path
            d="M12.0001 0C6.84049 0 2.44202 3.2565 0.74646 7.82611H23.2537C21.5582 3.2565 17.1596 0 12.0001 0Z"
            fill="#D80027"
          />
        </g>
        <defs>
          <clipPath id="clip0_3072_201">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    )}
  </Icon>
)
