'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AustriaFlag = ({ disabled, ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="AustriaFlag">
    {disabled ? (
      <>
        <path
          fill="#f0f0f0"
          d="M14.565 10.435A7 7 0 0 0 15 8c0-.856-.154-1.676-.435-2.435L8 4.957l-6.565.608A7 7 0 0 0 1 8c0 .856.154 1.677.435 2.435L8 11.044z"
        />
        <path
          fill="#454545"
          d="M8 15c3.01 0 5.576-1.9 6.565-4.565H1.435A7 7 0 0 0 8 15M8 1C4.99 1 2.425 2.9 1.435 5.565h13.13A7 7 0 0 0 8 1"
        />
      </>
    ) : (
      <>
        <path
          fill="#f0f0f0"
          d="M14.565 10.435A7 7 0 0 0 15 8c0-.856-.154-1.676-.435-2.435L8 4.957l-6.565.608A7 7 0 0 0 1 8c0 .856.154 1.677.435 2.435L8 11.044z"
        />
        <path
          fill="#d80027"
          d="M8 15c3.01 0 5.576-1.9 6.565-4.565H1.435A7 7 0 0 0 8 15M8 1C4.99 1 2.425 2.9 1.435 5.565h13.13A7 7 0 0 0 8 1"
        />
      </>
    )}
  </Icon>
)

AustriaFlag.displayName = 'AustriaFlag'
