'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AustriaFlag = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {props.disabled ? (
      <>
        <path
          fill="#f0f0f0"
          d="M23.254 16.174c.482-1.3.746-2.706.746-4.174s-.264-2.874-.746-4.174L12 6.783.746 7.826A12 12 0 0 0 0 12c0 1.468.264 2.874.746 4.174L12 17.218z"
        />
        <path
          fill="#454545"
          d="M12 24c5.16 0 9.558-3.256 11.254-7.826H.746C2.442 20.744 6.84 24 12 24m0-24C6.84 0 2.442 3.257.746 7.826h22.508C21.558 3.257 17.16 0 12 0"
        />
      </>
    ) : (
      <>
        <path
          fill="#f0f0f0"
          d="M23.254 16.174c.482-1.3.746-2.706.746-4.174s-.264-2.874-.746-4.174L12 6.783.746 7.826A12 12 0 0 0 0 12c0 1.468.264 2.874.746 4.174L12 17.218z"
        />
        <path
          fill="#d80027"
          d="M12 24c5.16 0 9.558-3.256 11.254-7.826H.746C2.442 20.744 6.84 24 12 24m0-24C6.84 0 2.442 3.257.746 7.826h22.508C21.558 3.257 17.16 0 12 0"
        />
      </>
    )}
  </Icon>
)

AustriaFlag.displayName = 'AustriaFlag'
