'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const BulgariaFlag = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="BulgariaFlag">
    {props.disabled ? (
      <>
        <g>
          <path
            d="M24 12.0001C24 10.5322 23.736 9.12611 23.2536 7.82618L12 7.30441L0.746391 7.82613C0.264047 9.12611 0 10.5322 0 12.0001C0 13.4679 0.264047 14.874 0.746391 16.1739L12 16.6957L23.2536 16.174C23.736 14.874 24 13.4679 24 12.0001Z"
            fill="#5C5C5C"
          />
          <path
            d="M12.0001 24C17.1597 24 21.5582 20.7435 23.2537 16.1739H0.746521C2.44204 20.7435 6.84055 24 12.0001 24Z"
            fill="#454545"
          />
          <path
            d="M0.746521 7.82611H23.2538C21.5582 3.2565 17.1597 0 12.0001 0C6.84055 0 2.44204 3.2565 0.746521 7.82611V7.82611Z"
            fill="#F0F0F0"
          />
        </g>
        <defs>
          <clipPath id="clip0_3072_347">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    ) : (
      <>
        <g>
          <path
            d="M24 12.0001C24 10.5322 23.736 9.12611 23.2536 7.82618L12 7.30441L0.746391 7.82613C0.264047 9.12611 0 10.5322 0 12.0001C0 13.4679 0.264047 14.874 0.746391 16.1739L12 16.6957L23.2536 16.174C23.736 14.874 24 13.4679 24 12.0001Z"
            fill="#496E2D"
          />
          <path
            d="M12.0001 24C17.1597 24 21.5582 20.7435 23.2537 16.1739H0.746521C2.44204 20.7435 6.84055 24 12.0001 24Z"
            fill="#D80027"
          />
          <path
            d="M0.746521 7.82611H23.2538C21.5582 3.2565 17.1597 0 12.0001 0C6.84055 0 2.44204 3.2565 0.746521 7.82611V7.82611Z"
            fill="#F0F0F0"
          />
        </g>
        <defs>
          <clipPath id="clip0_3072_214">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    )}
  </Icon>
)
