'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CyprusFlag = ({ disabled, ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="CyprusFlag">
    {disabled ? (
      <>
        <path fill="#fcfcfc" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path
          fill="#8a8a8a"
          d="M11.957 7.087h-.914a3.043 3.043 0 1 1-6.087 0h-.913a3.96 3.96 0 0 0 2.877 3.807c-.182.346-.155.781.105 1.106l.995-.798.995.798a1.01 1.01 0 0 0 .1-1.116 3.96 3.96 0 0 0 2.842-3.797"
        />
        <path
          fill="#d5d5d5"
          d="M5.565 6.783s0 1.521 1.522 1.521l.304.305H8s.304-.913.913-.913c0 0 0-.609.609-.609h.913s-.305-1.217 1.217-2.13l-.608-.305S8.913 6.174 7.39 5.87v.608h-.608l-.305-.304z"
        />
      </>
    ) : (
      <>
        <path fill="#fcfcfc" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path
          fill="#6da544"
          d="M11.957 7.087h-.914a3.043 3.043 0 1 1-6.087 0h-.913a3.96 3.96 0 0 0 2.877 3.807c-.182.346-.155.781.105 1.106l.995-.798.995.798a1.01 1.01 0 0 0 .1-1.116 3.96 3.96 0 0 0 2.842-3.797"
        />
        <path
          fill="#ffda44"
          d="M5.565 6.783s0 1.521 1.522 1.521l.304.305H8s.304-.913.913-.913c0 0 0-.609.609-.609h.913s-.305-1.217 1.217-2.13l-.609-.305S8.913 6.174 7.391 5.87v.608h-.608l-.305-.304z"
        />
      </>
    )}
  </Icon>
)

CyprusFlag.displayName = 'CyprusFlag'
