'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DenmarkFlag = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {props.disabled ? (
      <>
        <path fill="#f0f0f0" d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12" />
        <path
          fill="#454545"
          d="M9.29 10.435h14.507C23.03 4.547 17.995 0 11.898 0c-.896 0-1.768.099-2.608.285zm-3.131 0V1.459A12 12 0 0 0 0 10.435zm0 3.13H0a12 12 0 0 0 6.159 8.976zm3.131 0v10.15c.84.186 1.712.285 2.608.285 6.097 0 11.132-4.547 11.899-10.435z"
        />
      </>
    ) : (
      <>
        <path fill="#f0f0f0" d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12" />
        <path
          fill="#d80027"
          d="M9.391 10.435h14.507C23.131 4.547 18.097 0 12 0c-.896 0-1.769.099-2.609.285zm-3.13 0V1.459a12 12 0 0 0-6.159 8.976zm0 3.13H.102a12 12 0 0 0 6.159 8.976zm3.13 0v10.15c.84.186 1.713.285 2.609.285 6.097 0 11.131-4.547 11.898-10.435z"
        />
      </>
    )}
  </Icon>
)

DenmarkFlag.displayName = 'DenmarkFlag'
