'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const FranceFlag = ({ disabled, ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {disabled ? (
      <>
        <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path fill="#454545" d="M15 8c0-3.01-1.9-5.576-4.565-6.565v13.13A7 7 0 0 0 15 8" />
        <path fill="#444" d="M1 8c0 3.01 1.9 5.576 4.565 6.565V1.435A7 7 0 0 0 1 8" />
      </>
    ) : (
      <>
        <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path fill="#d80027" d="M15 8c0-3.01-1.9-5.576-4.565-6.565v13.13A7 7 0 0 0 15 8" />
        <path fill="#0052b4" d="M1 8c0 3.01 1.9 5.576 4.565 6.565V1.435A7 7 0 0 0 1 8" />
      </>
    )}
  </Icon>
)

FranceFlag.displayName = 'FranceFlag'
