'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const GermanyFlag = ({ size = 'medium', disabled, ...props }: Omit<IconProps, 'children' | 'title'>) => {
  if (['small', 'xsmall'].includes(size)) {
    return (
      <Icon {...props} title="GermanyFlag">
        {disabled ? (
          <>
            <path fill="#d5d5d5" d="M1.435 10.435a7.002 7.002 0 0 0 13.13 0L8 9.826z" />
            <path fill="#000" d="M8 1C4.99 1 2.425 2.9 1.435 5.565L8 6.174l6.565-.609A7 7 0 0 0 8 1" />
            <path
              fill="#454545"
              d="M1.435 5.565A7 7 0 0 0 1 8c0 .856.154 1.676.435 2.435h13.13A7 7 0 0 0 15 8c0-.856-.154-1.676-.435-2.435z"
            />
          </>
        ) : (
          <>
            <path fill="#ffda44" d="M1.435 10.435a7.002 7.002 0 0 0 13.13 0L8 9.826z" />
            <path fill="#000" d="M8 1C4.99 1 2.425 2.9 1.435 5.565L8 6.174l6.565-.609A7 7 0 0 0 8 1" />
            <path
              fill="#d80027"
              d="M1.435 5.565A7 7 0 0 0 1 8c0 .856.154 1.676.435 2.435h13.13A7 7 0 0 0 15 8c0-.856-.154-1.676-.435-2.435z"
            />
          </>
        )}
      </Icon>
    )
  }
  return (
    <Icon {...props} title="GermanyFlag">
      {disabled ? (
        <>
          <path fill="#d5d5d5" d="M3.091 15.304a9.503 9.503 0 0 0 17.818 0L12 14.478z" />
          <path fill="#000" d="M12 2.5a9.5 9.5 0 0 0-8.909 6.196l8.91.826 8.908-.826A9.5 9.5 0 0 0 12 2.5" />
          <path
            fill="#454545"
            d="M3.09 8.696A9.5 9.5 0 0 0 2.5 12a9.5 9.5 0 0 0 .59 3.304h17.82A9.5 9.5 0 0 0 21.5 12a9.5 9.5 0 0 0-.59-3.304z"
          />
        </>
      ) : (
        <>
          <path fill="#ffda44" d="M3.091 15.304a9.503 9.503 0 0 0 17.818 0L12 14.478z" />
          <path fill="#000" d="M12 2.5a9.5 9.5 0 0 0-8.909 6.196l8.91.826 8.908-.826A9.5 9.5 0 0 0 12 2.5" />
          <path
            fill="#d80027"
            d="M3.09 8.696A9.5 9.5 0 0 0 2.5 12a9.5 9.5 0 0 0 .59 3.304h17.82A9.5 9.5 0 0 0 21.5 12a9.5 9.5 0 0 0-.59-3.304z"
          />
        </>
      )}
    </Icon>
  )
}

GermanyFlag.displayName = 'GermanyFlag'
