'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const GreeceFlag = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {props.disabled ? (
      <>
        <path fill="#f0f0f0" d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12" />
        <path
          fill="#7b7b7b"
          d="M12 8.869h11.587a12 12 0 0 0-1.348-3.13H12zM4.53 21.391h14.94a12 12 0 0 0 2.768-3.13H1.761a12 12 0 0 0 2.769 3.13M4.174 2.903a12 12 0 0 0-2.413 2.836h2.413zM12 12V8.87H7.304V12h-3.13V8.87H.413A12 12 0 0 0 0 12c0 1.083.144 2.132.413 3.13h23.174A12 12 0 0 0 24 12zm0-12c-1.666 0-3.253.34-4.696.954v4.785H12V2.61h7.47A11.95 11.95 0 0 0 12 0"
        />
      </>
    ) : (
      <>
        <path fill="#f0f0f0" d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12" />
        <path
          fill="#338af3"
          d="M12 8.869h11.587a12 12 0 0 0-1.348-3.13H12zM4.53 21.391h14.94a12 12 0 0 0 2.768-3.13H1.761a12 12 0 0 0 2.769 3.13M4.174 2.903a12 12 0 0 0-2.413 2.836h2.413zM12 12V8.87H7.304V12h-3.13V8.87H.413A12 12 0 0 0 0 12c0 1.083.144 2.132.413 3.13h23.174A12 12 0 0 0 24 12zm0-12c-1.666 0-3.253.34-4.696.954v4.785H12V2.61h7.47A11.95 11.95 0 0 0 12 0"
        />
      </>
    )}
  </Icon>
)

GreeceFlag.displayName = 'GreeceFlag'
