'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const HungaryFlag: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="HungaryFlag">
    {props.disabled ? (
      <>
        <g>
          <path
            d="M0.746391 7.82608C0.264047 9.12611 0 10.5321 0 12C0 13.4678 0.264047 14.8739 0.746391 16.1739L12 17.2174L23.2536 16.1739C23.736 14.8739 24 13.4678 24 12C24 10.5321 23.736 9.12611 23.2536 7.82608L12 6.78259L0.746391 7.82608Z"
            fill="#F0F0F0"
          />
          <path
            d="M12.0001 0C6.84061 0 2.44205 3.2565 0.746582 7.82611H23.2538C21.5582 3.2565 17.1598 0 12.0001 0V0Z"
            fill="#454545"
          />
          <path
            d="M12.2536 23.8261C17.4132 23.8261 21.8117 20.5696 23.5072 16H1C2.69547 20.5696 7.09403 23.8261 12.2536 23.8261V23.8261Z"
            fill="#8A8A8A"
          />
        </g>
        <defs>
          <clipPath id="clip0_3072_384">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    ) : (
      <>
        <g>
          <path
            d="M0.746391 7.82608C0.264047 9.12611 0 10.5321 0 12C0 13.4678 0.264047 14.8739 0.746391 16.1739L12 17.2174L23.2536 16.1739C23.736 14.8739 24 13.4678 24 12C24 10.5321 23.736 9.12611 23.2536 7.82608L12 6.78259L0.746391 7.82608Z"
            fill="#F0F0F0"
          />
          <path
            d="M12.0001 0C6.84061 0 2.44205 3.2565 0.746582 7.82611H23.2538C21.5582 3.2565 17.1598 0 12.0001 0V0Z"
            fill="#D80027"
          />
          <path
            d="M12.0001 24.0001C17.1598 24.0001 21.5582 20.7436 23.2538 16.174H0.746582C2.44205 20.7436 6.84061 24.0001 12.0001 24.0001V24.0001Z"
            fill="#6DA544"
          />
        </g>
        <defs>
          <clipPath id="clip0_3072_202">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    )}
  </Icon>
)
