'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const ItalyFlag: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ItalyFlag">
    {props.disabled ? (
      <>
        <g>
          <path
            d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
            fill="#F0F0F0"
          />
          <path
            d="M24 12C24 6.84045 20.7435 2.44193 16.1739 0.746414V23.2537C20.7435 21.5581 24 17.1596 24 12V12Z"
            fill="#5D5D5D"
          />
          <path
            d="M0 12C0 17.1596 3.25655 21.5581 7.82611 23.2536V0.746414C3.25655 2.44193 0 6.84045 0 12Z"
            fill="#5E5E5E"
          />
        </g>
        <defs>
          <clipPath id="clip0_3023_231">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    ) : (
      <>
        <g>
          <path
            d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
            fill="#F0F0F0"
          />
          <path
            d="M24.0001 12C24.0001 6.84045 20.7436 2.44193 16.174 0.746414V23.2537C20.7436 21.5581 24.0001 17.1596 24.0001 12V12Z"
            fill="#CE2B37"
          />
          <path
            d="M0 12C0 17.1596 3.25655 21.5581 7.82611 23.2536V0.746414C3.25655 2.44193 0 6.84045 0 12Z"
            fill="#009246"
          />
        </g>
        <defs>
          <clipPath>
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    )}
  </Icon>
)
