'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ItalyFlag = ({ size = 'medium', disabled, ...props }: Omit<IconProps, 'children' | 'title'>) => {
  if (['small', 'xsmall'].includes(size)) {
    return (
      <Icon {...props} title="ItalyFlag">
        {disabled ? (
          <>
            <g clipPath="url(#clip0_3237_1277)">
              <path fill="#f0f0f0" d="M7.5 14.5a7 7 0 1 0 0-14 7 7 0 0 0 0 14" />
              <path fill="#5d5d5d" d="M14.5 7.5c0-3.01-1.9-5.576-4.565-6.565v13.13A7 7 0 0 0 14.5 7.5" />
              <path fill="#5e5e5e" d="M.5 7.5c0 3.01 1.9 5.576 4.565 6.565V.935A7 7 0 0 0 .5 7.5" />
            </g>
            <defs>
              <clipPath id="clip0_3237_1277">
                <path fill="#fff" d="M0 0h16v16H0z" />
              </clipPath>
            </defs>
          </>
        ) : (
          <>
            <g clipPath="url(#clip0_3237_1273)">
              <path fill="#f0f0f0" d="M7.5 14.5a7 7 0 1 0 0-14 7 7 0 0 0 0 14" />
              <path fill="#ce2b37" d="M14.5 7.5c0-3.01-1.9-5.576-4.565-6.565v13.13A7 7 0 0 0 14.5 7.5" />
              <path fill="#009246" d="M.5 7.5c0 3.01 1.9 5.576 4.565 6.565V.935A7 7 0 0 0 .5 7.5" />
            </g>
            <defs>
              <clipPath id="clip0_3237_1273">
                <path fill="#fff" d="M0 0h16v16H0z" />
              </clipPath>
            </defs>
          </>
        )}
      </Icon>
    )
  }
  return (
    <Icon {...props} title="ItalyFlag">
      {disabled ? (
        <>
          <path fill="#f0f0f0" d="M12 21.5a9.5 9.5 0 1 0 0-19 9.5 9.5 0 0 0 0 19" />
          <path fill="#5d5d5d" d="M21.5 12a9.5 9.5 0 0 0-6.196-8.91v17.82A9.5 9.5 0 0 0 21.5 12" />
          <path fill="#5e5e5e" d="M2.5 12a9.5 9.5 0 0 0 6.196 8.91V3.09A9.5 9.5 0 0 0 2.5 12" />
        </>
      ) : (
        <>
          <path fill="#f0f0f0" d="M12 21.5a9.5 9.5 0 1 0 0-19 9.5 9.5 0 0 0 0 19" />
          <path fill="#ce2b37" d="M21.5 12a9.5 9.5 0 0 0-6.196-8.91v17.82A9.5 9.5 0 0 0 21.5 12" />
          <path fill="#009246" d="M2.5 12a9.5 9.5 0 0 0 6.196 8.91V3.09A9.5 9.5 0 0 0 2.5 12" />
        </>
      )}
    </Icon>
  )
}

ItalyFlag.displayName = 'ItalyFlag'
