'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const LatviaFlag = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="LatviaFlag">
    {props.disabled ? (
      <>
        <path
          fill="#f0f0f0"
          d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
        />
        <path
          fill="#343434"
          d="M12 0C6.455 0 1.79 3.76.413 8.87H23.586C22.209 3.76 17.544 0 12 0ZM12 24C17.544 24 22.209 20.239 23.586 15.13H.413C1.79 20.239 6.455 24 12 24Z"
        />
      </>
    ) : (
      <>
        <path
          fill="#f0f0f0"
          d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
        />
        <path
          fill="#a2001d"
          d="M12 0C6.455 0 1.79 3.76.413 8.87H23.586C22.209 3.76 17.544 0 12 0ZM12 24C17.544 24 22.209 20.239 23.586 15.13H.413C1.79 20.239 6.455 24 12 24Z"
        />
      </>
    )}
  </Icon>
)

LatviaFlag.displayName = 'LatviaFlag'
