'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const LatviaFlag = ({ disabled, ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {disabled ? (
      <>
        <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path
          fill="#343434"
          d="M8 1a7 7 0 0 0-6.76 5.174h13.518A7 7 0 0 0 7.999 1M8 15a7 7 0 0 0 6.759-5.174H1.24A7 7 0 0 0 8 15"
        />
      </>
    ) : (
      <>
        <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path
          fill="#a2001d"
          d="M8 1a7 7 0 0 0-6.76 5.174h13.518A7 7 0 0 0 7.999 1M8 15a7 7 0 0 0 6.759-5.174H1.24A7 7 0 0 0 8 15"
        />
      </>
    )}
  </Icon>
)

LatviaFlag.displayName = 'LatviaFlag'
