'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const LatviaFlag = ({ size = 'medium', disabled, ...props }: Omit<IconProps, 'children' | 'title'>) => {
  if (['small', 'xsmall'].includes(size)) {
    return (
      <Icon {...props} size={size} title="LatviaFlag">
        {disabled ? (
          <>
            <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
            <path
              fill="#343434"
              d="M8 1a7 7 0 0 0-6.76 5.174h13.518A7 7 0 0 0 7.999 1M8 15a7 7 0 0 0 6.759-5.174H1.24A7 7 0 0 0 8 15"
            />
          </>
        ) : (
          <>
            <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
            <path
              fill="#a2001d"
              d="M8 1a7 7 0 0 0-6.76 5.174h13.518A7 7 0 0 0 7.999 1M8 15a7 7 0 0 0 6.759-5.174H1.24A7 7 0 0 0 8 15"
            />
          </>
        )}
      </Icon>
    )
  }
  return (
    <Icon {...props} size={size} title="LatviaFlag">
      {disabled ? (
        <>
          <path fill="#f0f0f0" d="M12 21.5a9.5 9.5 0 1 0 0-19 9.5 9.5 0 0 0 0 19" />
          <path
            fill="#343434"
            d="M12 2.5c-4.39 0-8.083 2.977-9.173 7.022h18.346C20.083 5.477 16.389 2.5 12 2.5m0 19c4.389 0 8.082-2.977 9.173-7.022H2.826C3.917 18.523 7.611 21.5 12 21.5"
          />
        </>
      ) : (
        <>
          <path fill="#f0f0f0" d="M12 21.5a9.5 9.5 0 1 0 0-19 9.5 9.5 0 0 0 0 19" />
          <path
            fill="#a2001d"
            d="M12 2.5c-4.39 0-8.083 2.977-9.173 7.022h18.346C20.083 5.477 16.389 2.5 12 2.5m0 19c4.389 0 8.082-2.977 9.173-7.022H2.826C3.917 18.523 7.611 21.5 12 21.5"
          />
        </>
      )}
    </Icon>
  )
}

LatviaFlag.displayName = 'LatviaFlag'
