'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const MaltaFlag = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {props.disabled ? (
      <>
        <path fill="#f0f0f0" d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12" />
        <path fill="#454545" d="M12 0c6.627 0 12 5.373 12 12s-5.373 12-12 12" />
        <path fill="#acacac" d="M8.348 4.695V3.13H6.783v1.565H5.218v1.566h1.565v1.565h1.565V6.26h1.565V4.695z" />
      </>
    ) : (
      <>
        <path fill="#f0f0f0" d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12" />
        <path fill="#d80027" d="M12 0c6.627 0 12 5.373 12 12s-5.373 12-12 12" />
        <path fill="#acabb1" d="M8.348 4.695V3.13H6.783v1.565H5.218v1.566h1.565v1.565h1.565V6.26h1.565V4.695z" />
      </>
    )}
  </Icon>
)

MaltaFlag.displayName = 'MaltaFlag'
