'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PortugalFlag = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {props.disabled ? (
      <>
        <path fill="#8a8a8a" d="M0 12c0 5.16 3.257 9.558 7.826 11.254L8.87 12 7.826.746C3.256 2.442 0 6.84 0 12" />
        <path
          fill="#454545"
          d="M24 12c0-6.627-5.373-12-12-12-1.468 0-2.874.264-4.174.746v22.508c1.3.482 2.706.746 4.174.746 6.627 0 12-5.373 12-12"
        />
        <path fill="#d5d5d5" d="M7.826 16.174a4.174 4.174 0 1 0 0-8.348 4.174 4.174 0 0 0 0 8.348" />
        <path fill="#454545" d="M5.48 9.913v2.609a2.348 2.348 0 1 0 4.695 0V9.913z" />
        <path fill="#f0f0f0" d="M7.825 13.304a.784.784 0 0 1-.782-.782v-1.044h1.565v1.044a.783.783 0 0 1-.783.782" />
      </>
    ) : (
      <>
        <path fill="#6da544" d="M0 12c0 5.16 3.257 9.558 7.826 11.254L8.87 12 7.826.746C3.256 2.442 0 6.84 0 12" />
        <path
          fill="#d80027"
          d="M24 12c0-6.627-5.373-12-12-12-1.468 0-2.874.264-4.174.746v22.508c1.3.482 2.706.746 4.174.746 6.627 0 12-5.373 12-12"
        />
        <path fill="#ffda44" d="M7.826 16.174a4.174 4.174 0 1 0 0-8.348 4.174 4.174 0 0 0 0 8.348" />
        <path fill="#d80027" d="M5.48 9.913v2.609a2.348 2.348 0 1 0 4.695 0V9.913z" />
        <path fill="#f0f0f0" d="M7.825 13.304a.784.784 0 0 1-.782-.782v-1.044h1.565v1.044a.783.783 0 0 1-.783.782" />
      </>
    )}
  </Icon>
)

PortugalFlag.displayName = 'PortugalFlag'
