'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const SlovakiaFlag = ({ disabled, ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {disabled ? (
      <>
        <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path fill="#444" d="M8 15a7 7 0 0 0 6.565-9.435H1.435A7 7 0 0 0 8 15" />
        <path fill="#454545" d="M8 15c3.01 0 5.576-1.9 6.565-4.565H1.435A7 7 0 0 0 8 15" />
        <path fill="#f0f0f0" d="M2.81 4.956v3.492c0 1.987 2.595 2.595 2.595 2.595S8 10.435 8 8.448V4.956z" />
        <path fill="#454545" d="M3.419 4.956v3.492q0 .351.154.66h3.664q.154-.309.154-.66V4.956z" />
        <path
          fill="#f0f0f0"
          d="M6.622 7.391H5.71v-.609h.609v-.608H5.71v-.609h-.608v.609h-.609v.608h.609v.61h-.913V8H5.1v.609h.608v-.61h.913z"
        />
        <path
          fill="#454545"
          d="M4.403 9.958c.393.246.796.39 1.002.453.206-.063.61-.207 1.001-.453q.594-.374.83-.85a1.06 1.06 0 0 0-.856-.167 1.065 1.065 0 0 0-1.95 0 1.07 1.07 0 0 0-.857.167q.236.476.83.85"
        />
      </>
    ) : (
      <>
        <path fill="#f0f0f0" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        <path fill="#0052b4" d="M8 15a7 7 0 0 0 6.565-9.435H1.435A7 7 0 0 0 8 15" />
        <path fill="#d80027" d="M8 15c3.01 0 5.576-1.9 6.565-4.565H1.435A7 7 0 0 0 8 15" />
        <path fill="#f0f0f0" d="M2.81 4.956v3.492c0 1.987 2.595 2.595 2.595 2.595S8 10.435 8 8.448V4.956z" />
        <path fill="#d80027" d="M3.419 4.956v3.492q0 .351.154.66h3.664q.154-.309.154-.66V4.956z" />
        <path
          fill="#f0f0f0"
          d="M6.622 7.391H5.71v-.609h.609v-.608H5.71v-.609h-.608v.609h-.609v.608h.609v.61h-.913V8H5.1v.609h.608v-.61h.913z"
        />
        <path
          fill="#0052b4"
          d="M4.403 9.958c.393.246.796.39 1.002.453.206-.063.61-.207 1.001-.453q.594-.374.83-.85a1.06 1.06 0 0 0-.856-.167 1.065 1.065 0 0 0-1.95 0 1.07 1.07 0 0 0-.857.167q.236.476.83.85"
        />
      </>
    )}
  </Icon>
)

SlovakiaFlag.displayName = 'SlovakiaFlag'
