'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const SpainFlag = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {props.disabled ? (
      <>
        <path
          fill="#d5d5d5"
          d="M0 12c0 1.468.264 2.874.746 4.174L12 17.217l11.254-1.043c.482-1.3.746-2.706.746-4.174s-.264-2.874-.746-4.174L12 6.783.746 7.826A12 12 0 0 0 0 12"
        />
        <path
          fill="#454545"
          d="M23.253 7.826C21.557 3.257 17.159 0 11.999 0S2.441 3.257.746 7.826zM.746 16.174C2.441 20.744 6.84 24 11.999 24c5.16 0 9.558-3.256 11.254-7.826z"
        />
      </>
    ) : (
      <>
        <path
          fill="#ffda44"
          d="M0 12c0 1.468.264 2.874.746 4.174L12 17.217l11.254-1.043c.482-1.3.746-2.706.746-4.174s-.264-2.874-.746-4.174L12 6.783.746 7.826A12 12 0 0 0 0 12"
        />
        <path
          fill="#d80027"
          d="M23.253 7.826C21.557 3.257 17.159 0 11.999 0S2.441 3.257.746 7.826zM.746 16.174C2.441 20.744 6.84 24 11.999 24c5.16 0 9.558-3.256 11.254-7.826z"
        />
      </>
    )}
  </Icon>
)

SpainFlag.displayName = 'SpainFlag'
