'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const SpainFlag = ({ size = 'medium', disabled, ...props }: Omit<IconProps, 'children' | 'title'>) => {
  if (['small', 'xsmall'].includes(size)) {
    return (
      <Icon {...props} size={size} title="SpainFlag">
        {disabled ? (
          <>
            <path
              fill="#d5d5d5"
              d="M1 8c0 .856.154 1.676.435 2.435L8 11.043l6.565-.608A7 7 0 0 0 15 8c0-.856-.154-1.676-.435-2.435L8 4.956l-6.565.61A7 7 0 0 0 1 8"
            />
            <path fill="#454545" d="M14.564 5.565a7.002 7.002 0 0 0-13.13 0zm-13.129 4.87a7.002 7.002 0 0 0 13.13 0z" />
          </>
        ) : (
          <>
            <path
              fill="#ffda44"
              d="M1 8c0 .856.154 1.676.435 2.435L8 11.043l6.565-.608A7 7 0 0 0 15 8c0-.856-.154-1.676-.435-2.435L8 4.956l-6.565.61A7 7 0 0 0 1 8"
            />
            <path fill="#d80027" d="M14.564 5.565a7.002 7.002 0 0 0-13.13 0zm-13.129 4.87a7.002 7.002 0 0 0 13.13 0z" />
          </>
        )}
      </Icon>
    )
  }
  return (
    <Icon {...props} size={size} title="SpainFlag">
      {disabled ? (
        <>
          <path
            fill="#d5d5d5"
            d="M2.5 12a9.5 9.5 0 0 0 .59 3.304l8.91.826 8.91-.826A9.5 9.5 0 0 0 21.5 12a9.5 9.5 0 0 0-.59-3.304L12 7.87l-8.91.826A9.5 9.5 0 0 0 2.5 12"
          />
          <path fill="#454545" d="M20.909 8.696a9.503 9.503 0 0 0-17.819 0zM3.09 15.304a9.503 9.503 0 0 0 17.819 0z" />
        </>
      ) : (
        <>
          <path
            fill="#ffda44"
            d="M2.5 12a9.5 9.5 0 0 0 .59 3.304l8.91.826 8.91-.826A9.5 9.5 0 0 0 21.5 12a9.5 9.5 0 0 0-.59-3.304L12 7.87l-8.91.826A9.5 9.5 0 0 0 2.5 12"
          />
          <path fill="#d80027" d="M20.909 8.696a9.503 9.503 0 0 0-17.819 0zM3.09 15.304a9.503 9.503 0 0 0 17.819 0z" />
        </>
      )}
    </Icon>
  )
}

SpainFlag.displayName = 'SpainFlag'
