'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const SwedenFlag = ({ disabled, ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {disabled ? (
      <>
        <mask id="mask0_3237_1286" x="1" y="1" maskUnits="userSpaceOnUse">
          <path fill="#fff" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        </mask>
        <g mask="url(#mask0_3237_1286)">
          <path fill="#414141" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
          <path fill="#c4c4c4" d="M5.083.27H8v15.75H5.083z" />
          <path fill="#c4c4c4" d="M.417 6.688H16.75v2.916H.417z" />
        </g>
      </>
    ) : (
      <>
        <mask id="mask0_3237_1281" x="1" y="1" maskUnits="userSpaceOnUse">
          <path fill="#fff" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
        </mask>
        <g mask="url(#mask0_3237_1281)">
          <path fill="#005293" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14" />
          <path fill="#fecb00" d="M5.083.27H8v15.75H5.083z" />
          <path fill="#fecb00" d="M.417 6.688H16.75v2.916H.417z" />
        </g>
      </>
    )}
  </Icon>
)

SwedenFlag.displayName = 'SwedenFlag'
