'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const SwedenFlag = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Sweden">
    {props.disabled ? (
      <>
        <g>
          <mask id="mask0_3023_247" maskUnits="userSpaceOnUse" x="0" y="0">
            <path
              d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
              fill="#005293"
            />
          </mask>
          <g>
            <path
              d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
              fill="#414141"
            />
            <path d="M7 -1.25H12V25.75H7V-1.25Z" fill="#C4C4C4" />
            <path d="M-1 9.75H27V14.75H-1V9.75Z" fill="#C4C4C4" />
          </g>
        </g>
        <defs>
          <clipPath id="clip0_3023_247">
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    ) : (
      <>
        <g>
          <path
            d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
            fill="#005293"
          />
          <g mask="url(#mask0_3023_239)">
            <path
              d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
              fill="#005293"
            />
            <path d="M7 -1.25H12V25.75H7V-1.25Z" fill="#FECB00" />
            <path d="M-1 9.75H27V14.75H-1V9.75Z" fill="#FECB00" />
          </g>
        </g>
        <defs>
          <clipPath>
            <rect fill="white" />
          </clipPath>
        </defs>
      </>
    )}
  </Icon>
)
