/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const managedDatabaseContent = `${BASE_URL}/products/managedDatabase/managed-database-content.webp`
const managedDatabaseKeyvisual = `${BASE_URL}/products/managedDatabase/managed-database-keyvisual.webp`
const managedDatabaseOriginal = `${BASE_URL}/products/managedDatabase/managed-database-original.webp`
const managedDatabaseWire = `${BASE_URL}/products/managedDatabase/managed-database-wire.svg`

export {
  managedDatabaseContent,
  managedDatabaseKeyvisual,
  managedDatabaseOriginal,
  managedDatabaseWire,
}
