/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const quantumApplicationContent = `${BASE_URL}/products/quantumApplication/quantum-application-content.webp`
const quantumApplicationKeyvisual = `${BASE_URL}/products/quantumApplication/quantum-application-keyvisual.webp`
const quantumApplicationOriginal = `${BASE_URL}/products/quantumApplication/quantum-application-original.webp`
const quantumApplicationWire = `${BASE_URL}/products/quantumApplication/quantum-application-wire.svg`

export {
  quantumApplicationContent,
  quantumApplicationKeyvisual,
  quantumApplicationOriginal,
  quantumApplicationWire,
}
