/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://scaleway-assets.s3.fr-par.scw.cloud/illustrations'

const ipamContent = `${BASE_URL}/products/ipam/ipamContent.webp`
const ipamKeyvisual = `${BASE_URL}/products/ipam/ipamKeyvisual.webp`
const ipamOriginal = `${BASE_URL}/products/ipam/ipamOriginal.webp`
const ipamWire = `${BASE_URL}/products/ipam/ipamWire.svg`

export { ipamContent, ipamKeyvisual, ipamOriginal, ipamWire }
