/**
 * This file is automatically generated from /utils/scripts/update-illustration-components.tsx
 * PLEASE DO NOT EDIT HERE
 */
import { WireIllustration } from '../../WireIllustration'
import type { IllustrationWireProp } from '../../WireIllustration'

export const DataWarehouseWire = ({
  ...props
}: Omit<IllustrationWireProp, 'url'>) => (
  <WireIllustration
    // eslint-disable-next-line react/jsx-props-no-spreading
    {...props}
    url="https://assets.scaleway.com/illustrations/products/dataWarehouse/data-warehouse-wire.svg"
  />
)
