/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const appleSiliconContent = `${BASE_URL}/products/appleSilicon/apple-silicon-content.webp`
const appleSiliconKeyvisual = `${BASE_URL}/products/appleSilicon/apple-silicon-keyvisual.webp`
const appleSiliconM2Content = `${BASE_URL}/products/appleSilicon/apple-silicon-m2-content.webp`
const appleSiliconM2Keyvisual = `${BASE_URL}/products/appleSilicon/apple-silicon-m2-keyvisual.webp`
const appleSiliconM2Original = `${BASE_URL}/products/appleSilicon/apple-silicon-m2-original.webp`
const appleSiliconM2Wire = `${BASE_URL}/products/appleSilicon/apple-silicon-m2-wire.svg`
const appleSiliconOriginal = `${BASE_URL}/products/appleSilicon/apple-silicon-original.webp`
const appleSiliconWire = `${BASE_URL}/products/appleSilicon/apple-silicon-wire.svg`

export {
  appleSiliconContent,
  appleSiliconKeyvisual,
  appleSiliconM2Content,
  appleSiliconM2Keyvisual,
  appleSiliconM2Original,
  appleSiliconM2Wire,
  appleSiliconOriginal,
  appleSiliconWire,
}
