/**
 * This file is automatically generated from /utils/scripts/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const serverlessJobContent = `${BASE_URL}/products/serverlessJob/serverless-job-content.webp`
const serverlessJobKeyvisual = `${BASE_URL}/products/serverlessJob/serverless-job-keyvisual.webp`
const serverlessJobOriginal = `${BASE_URL}/products/serverlessJob/serverless-job-original.webp`
const serverlessJobWire = `${BASE_URL}/products/serverlessJob/serverless-job-wire.svg`

export {
  serverlessJobContent,
  serverlessJobKeyvisual,
  serverlessJobOriginal,
  serverlessJobWire,
}
