/**
 * This file is automatically generated from /utils/scripts/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const inferenceMoshiContent = `${BASE_URL}/products/moshiInference/inference-moshi-content.webp`
const inferenceMoshiKeyvisual = `${BASE_URL}/products/moshiInference/inference-moshi-keyvisual.webp`
const inferenceMoshiOriginal = `${BASE_URL}/products/moshiInference/inference-moshi-original.webp`
const inferenceMoshiWire = `${BASE_URL}/products/moshiInference/inference-moshi-wire.svg`

export {
  inferenceMoshiContent,
  inferenceMoshiKeyvisual,
  inferenceMoshiOriginal,
  inferenceMoshiWire,
}
