/**
 * This file is automatically generated from /utils/scripts/uploadIllustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const transactionalEmailContent = `${BASE_URL}/products/transactionalEmail/transactional-email-content.webp`
const transactionalEmailKeyvisual = `${BASE_URL}/products/transactionalEmail/transactional-email-keyvisual.webp`
const transactionalEmailOriginal = `${BASE_URL}/products/transactionalEmail/transactional-email-original.webp`
const transactionalEmailWire = `${BASE_URL}/products/transactionalEmail/transactional-email-wire.svg`

export {
  transactionalEmailContent,
  transactionalEmailKeyvisual,
  transactionalEmailOriginal,
  transactionalEmailWire,
}
