/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const elasticMetalContent = `${BASE_URL}/products/elasticMetal/elastic-metal-content.webp`
const elasticMetalKeyvisual = `${BASE_URL}/products/elasticMetal/elastic-metal-keyvisual.webp`
const elasticMetalOriginal = `${BASE_URL}/products/elasticMetal/elastic-metal-original.webp`
const elasticMetalWire = `${BASE_URL}/products/elasticMetal/elastic-metal-wire.svg`

export {
  elasticMetalContent,
  elasticMetalKeyvisual,
  elasticMetalOriginal,
  elasticMetalWire,
}
