/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const dataOrchestratorContent = `${BASE_URL}/products/dataOrchestrator/data-orchestrator-content.webp`
const dataOrchestratorKeyvisual = `${BASE_URL}/products/dataOrchestrator/data-orchestrator-keyvisual.webp`
const dataOrchestratorOriginal = `${BASE_URL}/products/dataOrchestrator/data-orchestrator-original.webp`
const dataOrchestratorWire = `${BASE_URL}/products/dataOrchestrator/data-orchestrator-wire.svg`

export {
  dataOrchestratorContent,
  dataOrchestratorKeyvisual,
  dataOrchestratorOriginal,
  dataOrchestratorWire,
}
