/**
 * This file is automatically generated from /utils/scripts/uploadIllustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const managedSearchDatabaseContent = `${BASE_URL}/products/managedSearchDatabase/managed-search-database-content.webp`
const managedSearchDatabaseKeyvisual = `${BASE_URL}/products/managedSearchDatabase/managed-search-database-keyvisual.webp`
const managedSearchDatabaseOriginal = `${BASE_URL}/products/managedSearchDatabase/managed-search-database-original.webp`
const managedSearchDatabaseWire = `${BASE_URL}/products/managedSearchDatabase/managed-search-database-wire.svg`

export {
  managedSearchDatabaseContent,
  managedSearchDatabaseKeyvisual,
  managedSearchDatabaseOriginal,
  managedSearchDatabaseWire,
}
