/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://scaleway-assets.s3.fr-par.scw.cloud/illustrations'

const documentDBContent = `${BASE_URL}/products/documentDB/documentDB-content.webp`
const documentDBKeyvisual = `${BASE_URL}/products/documentDB/documentDB-keyvisual.webp`
const documentDBOriginal = `${BASE_URL}/products/documentDB/documentDB-original.webp`
const documentDBWire = `${BASE_URL}/products/documentDB/documentDB-wire.svg`

export {
  documentDBContent,
  documentDBKeyvisual,
  documentDBOriginal,
  documentDBWire,
}
