'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AddressPlayIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="m9.66 17.914.34-.615.339.615a.71.71 0 0 1-.679 0" />
        <path
          fillRule="evenodd"
          d="M13.108 9.6a.612.612 0 0 0 0-1.083l-4.66-2.445a.612.612 0 0 0-.895.542v4.89a.612.612 0 0 0 .896.542zm-4.332.892V7.626l2.731 1.433z"
          clipRule="evenodd"
        />
        <path
          fillRule="evenodd"
          d="m9.66 17.914.34-.615c.339.615.34.614.34.614h.002l.005-.003.016-.01.057-.032a14 14 0 0 0 .906-.583 15.5 15.5 0 0 0 2.12-1.79c1.536-1.561 3.142-3.917 3.142-6.955C16.588 4.928 13.638 2 10 2 6.36 2 3.412 4.928 3.412 8.54c0 3.038 1.606 5.394 3.142 6.955a15.5 15.5 0 0 0 2.823 2.253 9 9 0 0 0 .26.153l.016.009.005.002zM4.823 8.54c0-2.838 2.318-5.139 5.177-5.139s5.176 2.301 5.176 5.14c0 2.523-1.334 4.546-2.74 5.974A14 14 0 0 1 10 16.482a14 14 0 0 1-2.436-1.966c-1.406-1.43-2.74-3.452-2.74-5.976Z"
          clipRule="evenodd"
        />
      </>
    ) : (
      <>
        <path
          fillRule="evenodd"
          d="M5.787 8.618a1.338 1.338 0 0 0 1.937 1.197l2.573-1.287a1.338 1.338 0 0 0 0-2.394L7.724 4.847a1.338 1.338 0 0 0-1.937 1.197zM9.699 7.33 7.125 8.618V6.044L9.7 7.331Z"
          clipRule="evenodd"
        />
        <path
          fillRule="evenodd"
          d="m7.7 14.923.003.002c.185.1.409.1.594 0L8 14.387c.296.537.298.537.298.537h.001l.005-.003.014-.008a7 7 0 0 0 .227-.134 13.5 13.5 0 0 0 2.47-1.971c1.344-1.366 2.75-3.428 2.75-6.085C13.765 3.563 11.184 1 8 1S2.235 3.562 2.235 6.723c0 2.657 1.406 4.72 2.75 6.085a13.5 13.5 0 0 0 2.47 1.971q.113.07.178.106l.031.018.018.01.015.008zm-4.23-8.2C3.47 4.239 5.5 2.226 8 2.226c2.502 0 4.53 2.013 4.53 4.497 0 2.208-1.168 3.978-2.398 5.228A12.3 12.3 0 0 1 8 13.671a12.3 12.3 0 0 1-2.132-1.72c-1.23-1.25-2.397-3.02-2.397-5.228ZM8 14.387l-.297.537z"
          clipRule="evenodd"
        />
      </>
    )}
  </Icon>
)

AddressPlayIcon.displayName = 'AddressPlayIcon'
