'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AlertCircleOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="AlertCircleOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M10 3.455a6.545 6.545 0 1 0 0 13.09 6.545 6.545 0 0 0 0-13.09M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m8-3.152c.402 0 .727.326.727.728v3.03a.727.727 0 0 1-1.454 0v-3.03c0-.402.325-.728.727-.728m-.727 6.182c0-.401.325-.727.727-.727h.006c.402 0 .727.326.727.727v.006a.727.727 0 0 1-.727.728H10a.727.727 0 0 1-.727-.728z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M8 2.764a5.236 5.236 0 1 0 0 10.472A5.236 5.236 0 0 0 8 2.764M1.6 8a6.4 6.4 0 1 1 12.8 0A6.4 6.4 0 0 1 1.6 8M8 5.48c.321 0 .582.26.582.582v2.424a.582.582 0 0 1-1.164 0V6.061c0-.322.26-.582.582-.582m-.582 4.945c0-.321.26-.581.582-.581h.005c.321 0 .582.26.582.581v.005c0 .322-.26.582-.582.582H8a.58.58 0 0 1-.582-.582z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

AlertCircleOutlineIcon.displayName = 'AlertCircleOutlineIcon'
