'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const ArrowLeftIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ArrowLeftIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M12.78 5.47a.75.75 0 0 1 0 1.06l-3.72 3.72 3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0"
        fillRule="evenodd"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M10.53 4.22a.75.75 0 0 1 0 1.06L7.81 8l2.72 2.72a.75.75 0 1 1-1.06 1.06L6.22 8.53a.75.75 0 0 1 0-1.06l3.25-3.25a.75.75 0 0 1 1.06 0"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
