'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ArrowLeftDoubleIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ArrowLeftDouble">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M4.47 9.72a.75.75 0 0 0 0 1.06l4.25 4.25a.75.75 0 0 0 1.06-1.06l-3.72-3.72 3.72-3.72a.75.75 0 0 0-1.06-1.06zm9.25-4.25L9.47 9.72a.75.75 0 0 0 0 1.06l4.25 4.25a.75.75 0 1 0 1.06-1.06l-3.72-3.72 3.72-3.72a.75.75 0 0 0-1.06-1.06"
        fillRule="evenodd"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M3.22 7.47a.75.75 0 0 0 0 1.06l3.25 3.25a.75.75 0 0 0 1.06-1.06L4.81 8l2.72-2.72a.75.75 0 0 0-1.06-1.06zm8.25-3.25L8.22 7.47a.75.75 0 0 0 0 1.06l3.25 3.25a.75.75 0 1 0 1.06-1.06L9.81 8l2.72-2.72a.75.75 0 0 0-1.06-1.06"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
