'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AudioIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M10.702 2.25a.75.75 0 0 1 .75.75v14a.75.75 0 0 1-1.5 0V3a.75.75 0 0 1 .75-.75m3.009 2.505a.75.75 0 0 1 .75.75v9.018a.75.75 0 0 1-1.5 0V5.505a.75.75 0 0 1 .75-.75m-9.027.496a.75.75 0 0 1 .75.75v7.996a.75.75 0 0 1-1.5 0V6.001a.75.75 0 0 1 .75-.75M7.693 7.25a.75.75 0 0 1 .75.75v3.998a.75.75 0 0 1-1.5 0V8a.75.75 0 0 1 .75-.75m9.027 0a.75.75 0 0 1 .75.75v3.998a.75.75 0 0 1-1.5 0V8a.75.75 0 0 1 .75-.75" />
    ) : (
      <path d="M8.702 1.998a.75.75 0 0 1 .75.749v10.505a.75.75 0 0 1-1.5 0V2.748a.75.75 0 0 1 .75-.75m2.257 1.878c.414 0 .751.336.751.75v6.767a.75.75 0 0 1-1.5 0V4.626a.75.75 0 0 1 .749-.75m-6.773.373a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0v-6a.75.75 0 0 1 .75-.75m2.258 1.5a.75.75 0 0 1 .75.75v3a.75.75 0 0 1-1.5 0v-3a.75.75 0 0 1 .75-.75m6.773 0a.75.75 0 0 1 .751.75v3a.75.75 0 0 1-1.5 0v-3c0-.415.335-.75.749-.75" />
    )}
  </Icon>
)

AudioIcon.displayName = 'AudioIcon'
