'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const BookOpenOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="BookOpenOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M10.75 16.91C11.958 16.077 13.421 15.59 15 15.59 15.71 15.59 16.396 15.689 17.046 15.873 17.272 15.937 17.515 15.891 17.702 15.749 17.89 15.607 18 15.386 18 15.151V4.151C18 3.815 17.777 3.521 17.454 3.429 16.673 3.208 15.85 3.09 15 3.09 13.464 3.09 12.016 3.476 10.75 4.155V16.91ZM9.25 4.155C7.984 3.476 6.536 3.09 5 3.09 4.15 3.09 3.327 3.208 2.546 3.429 2.223 3.521 2 3.815 2 4.151V15.151C2 15.386 2.11 15.607 2.298 15.749 2.485 15.891 2.728 15.937 2.954 15.873 3.604 15.689 4.29 15.59 5 15.59 6.579 15.59 8.042 16.077 9.25 16.91V4.155Z" />
    ) : (
      <path d="M7.125 2.995C5.966 2.479 4.683 2.193 3.333 2.193 2.685 2.193 2.052 2.259 1.441 2.385 1.18 2.438 1 2.673 1 2.939V12.266C1 12.669 1.399 12.951 1.792 12.863 2.288 12.751 2.804 12.693 3.333 12.693 4.731 12.693 6.032 13.102 7.125 13.808V2.995ZM8.875 13.808C9.968 13.102 11.269 12.693 12.667 12.693 13.196 12.693 13.712 12.751 14.208 12.863 14.601 12.951 15 12.669 15 12.266V2.939C15 2.673 14.82 2.438 14.56 2.385 13.948 2.259 13.315 2.193 12.667 2.193 11.317 2.193 10.034 2.479 8.875 2.995V13.808Z" />
    )}
  </Icon>
)

BookOpenOutlineIcon.displayName = 'BookOpenOutlineIcon'
