'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const BookOpenOutlineOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="BookOpenOutlineOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        fillRule="evenodd"
        d="M3.455 4.266v10.019a8.03 8.03 0 0 1 5.818.961V5.504a6.5 6.5 0 0 0-4.121-1.46c-.588 0-1.157.077-1.697.222m7.272 1.238v9.742a8.03 8.03 0 0 1 5.818-.961V4.265a6.6 6.6 0 0 0-1.697-.221 6.5 6.5 0 0 0-4.12 1.46M10 4.225A7.97 7.97 0 0 0 5.152 2.59c-.934 0-1.832.16-2.667.456A.73.73 0 0 0 2 3.73v11.515a.727.727 0 0 0 .97.686 6.5 6.5 0 0 1 2.182-.372c1.676 0 3.204.63 4.363 1.666a.727.727 0 0 0 .97 0 6.52 6.52 0 0 1 4.364-1.666c.766 0 1.5.131 2.181.372a.727.727 0 0 0 .97-.686V3.73a.73.73 0 0 0-.485-.685 8 8 0 0 0-2.667-.456c-1.822 0-3.503.61-4.848 1.636"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M2.273 2.982v8.767a7.02 7.02 0 0 1 5.09.841V4.066a5.7 5.7 0 0 0-3.605-1.278c-.515 0-1.012.068-1.485.194m6.363 1.084v8.524a7.03 7.03 0 0 1 5.09-.841V2.982a5.7 5.7 0 0 0-1.484-.194 5.7 5.7 0 0 0-3.606 1.278M8 2.947a6.97 6.97 0 0 0-4.242-1.432 7 7 0 0 0-2.334.399.64.64 0 0 0-.424.6V12.59a.636.636 0 0 0 .848.6 5.7 5.7 0 0 1 1.91-.326 5.7 5.7 0 0 1 3.818 1.458.636.636 0 0 0 .848 0 5.7 5.7 0 0 1 3.818-1.458c.671 0 1.313.115 1.91.326a.636.636 0 0 0 .848-.6V2.514c0-.27-.17-.51-.424-.6a7 7 0 0 0-2.334-.399A6.97 6.97 0 0 0 8 2.947"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

BookOpenOutlineOutlineIcon.displayName = 'BookOpenOutlineOutlineIcon'
