'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const BoxEssentialsOutlineIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="m17.25 6.78-6.42 3.322v7.186l6.42-3.188zM3.666 5.55l6.411 3.252L16.36 5.55l-6.284-3.21zm-.916 8.545 6.58 3.204v-7.193L2.75 6.767zm16 .47a.75.75 0 0 1-.416.671l-7.92 3.936a.75.75 0 0 1-.661.002L1.672 15.24a.75.75 0 0 1-.422-.674v-9.02a.75.75 0 0 1 .414-.67L9.745.83l.082-.036a.75.75 0 0 1 .595.038l7.92 4.047c.25.128.408.386.409.667z" />
    ) : (
      <path d="M13.8 5.424 8.665 8.082v5.749L13.8 11.28zM2.933 4.44l5.129 2.602 5.026-2.602-5.027-2.568zM2.2 11.276l5.264 2.564V8.085L2.2 5.414zm12.8.376a.6.6 0 0 1-.332.537l-6.336 3.149a.6.6 0 0 1-.53.002l-6.465-3.15A.6.6 0 0 1 1 11.652V4.437a.6.6 0 0 1 .332-.536L7.796.664l.066-.029a.6.6 0 0 1 .475.03l6.336 3.238a.6.6 0 0 1 .328.534z" />
    )}
  </Icon>
)

BoxEssentialsOutlineIcon.displayName = 'BoxEssentialsOutlineIcon'
