'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CheckCircleOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="CheckCircleOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M10 3.455a6.545 6.545 0 1 0 0 13.09 6.545 6.545 0 0 0 0-13.09M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m10.847-2.41a.727.727 0 0 1 .169 1.015l-3.03 4.242a.727.727 0 0 1-1.106.091L7.06 11.12a.727.727 0 1 1 1.029-1.028l1.211 1.21 2.531-3.543a.727.727 0 0 1 1.015-.169"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M8 2.273a5.727 5.727 0 1 0 0 11.454A5.727 5.727 0 0 0 8 2.273M1 8a7 7 0 1 1 14 0A7 7 0 0 1 1 8m9.491-2.109a.636.636 0 0 1 .148.888l-2.651 3.712a.636.636 0 0 1-.968.08l-1.591-1.59a.636.636 0 0 1 .9-.9l1.06 1.06 2.214-3.102a.636.636 0 0 1 .888-.148"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

CheckCircleOutlineIcon.displayName = 'CheckCircleOutlineIcon'
