'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ClockOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ClockOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        fillRule="evenodd"
        d="M10 3.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m8-5.583a.75.75 0 0 1 .75.75V9.25h2.875a.75.75 0 0 1 0 1.5H10a.75.75 0 0 1-.75-.75V5.167a.75.75 0 0 1 .75-.75"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M8 2.313a5.687 5.687 0 1 0 0 11.374A5.687 5.687 0 0 0 8 2.313M1 8a7 7 0 1 1 14 0A7 7 0 0 1 1 8m7-4.885c.362 0 .656.293.656.656v3.573h2.516a.656.656 0 0 1 0 1.312H8A.656.656 0 0 1 7.344 8V3.77c0-.362.294-.655.656-.655"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ClockOutlineIcon.displayName = 'ClockOutlineIcon'
