'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ClockOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M10 3.5C6.41015 3.5 3.5 6.41015 3.5 10C3.5 13.5899 6.41015 16.5 10 16.5C13.5899 16.5 16.5 13.5899 16.5 10C16.5 6.41015 13.5899 3.5 10 3.5ZM2 10C2 5.58172 5.58172 2 10 2C14.4183 2 18 5.58172 18 10C18 14.4183 14.4183 18 10 18C5.58172 18 2 14.4183 2 10ZM10 4.41667C10.4142 4.41667 10.75 4.75245 10.75 5.16667V9.25H13.625C14.0392 9.25 14.375 9.58579 14.375 10C14.375 10.4142 14.0392 10.75 13.625 10.75H10C9.58579 10.75 9.25 10.4142 9.25 10V5.16667C9.25 4.75245 9.58579 4.41667 10 4.41667Z"
        fillRule="evenodd"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M8 2.3125C4.85888 2.3125 2.3125 4.85888 2.3125 8C2.3125 11.1411 4.85888 13.6875 8 13.6875C11.1411 13.6875 13.6875 11.1411 13.6875 8C13.6875 4.85888 11.1411 2.3125 8 2.3125ZM1 8C1 4.13401 4.13401 1 8 1C11.866 1 15 4.13401 15 8C15 11.866 11.866 15 8 15C4.13401 15 1 11.866 1 8ZM8 3.11458C8.36244 3.11458 8.65625 3.4084 8.65625 3.77083V7.34375H11.1719C11.5343 7.34375 11.8281 7.63756 11.8281 8C11.8281 8.36244 11.5343 8.65625 11.1719 8.65625H8C7.63756 8.65625 7.34375 8.36244 7.34375 8V3.77083C7.34375 3.4084 7.63756 3.11458 8 3.11458Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
