'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const CloseCircleOutlineIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="CloseCircleOutlineIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M10 16.67c-3.675 0-6.67-2.995-6.67-6.67S6.325 3.33 10 3.33s6.67 2.995 6.67 6.67-2.995 6.67-6.67 6.67m0-15c-4.61 0-8.33 3.72-8.33 8.33s3.72 8.33 8.33 8.33 8.33-3.72 8.33-8.33S14.61 1.67 10 1.67m2.16 5L10 8.83 7.84 6.67 6.67 7.84 8.83 10l-2.16 2.16 1.17 1.17L10 11.17l2.16 2.16 1.17-1.17L11.17 10l2.16-2.16z" />
    ) : (
      <path
        clipRule="evenodd"
        d="M8 2.5C4.96243 2.5 2.5 4.96243 2.5 8C2.5 11.0376 4.96243 13.5 8 13.5C11.0376 13.5 13.5 11.0376 13.5 8C13.5 4.96243 11.0376 2.5 8 2.5ZM1 8C1 4.13401 4.13401 1 8 1C11.866 1 15 4.13401 15 8C15 11.866 11.866 15 8 15C4.13401 15 1 11.866 1 8ZM5.90717 5.90717C6.20006 5.61428 6.67494 5.61428 6.96783 5.90717L8 6.93934L9.03217 5.90717C9.32506 5.61428 9.79994 5.61428 10.0928 5.90717C10.3857 6.20006 10.3857 6.67494 10.0928 6.96783L9.06066 8L10.0928 9.03217C10.3857 9.32506 10.3857 9.79994 10.0928 10.0928C9.79994 10.3857 9.32506 10.3857 9.03217 10.0928L8 9.06066L6.96783 10.0928C6.67494 10.3857 6.20006 10.3857 5.90717 10.0928C5.61428 9.79994 5.61428 9.32506 5.90717 9.03217L6.93934 8L5.90717 6.96783C5.61428 6.67494 5.61428 6.20006 5.90717 5.90717Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
