'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ConsoleIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M4 3.778a2 2 0 0 0-2 2v8.444a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V5.778a2 2 0 0 0-2-2zm.838 7.78a.667.667 0 0 1 .05-.942l1.67-1.506-1.671-1.503a.667.667 0 1 1 .892-.991l2.223 2a.667.667 0 0 1 0 .99l-2.223 2a.667.667 0 0 1-.941-.049m4.94-1.336a.667.667 0 0 0 0 1.334H12a.667.667 0 0 0 0-1.334z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M1 3.333A2.333 2.333 0 0 1 3.333 1h9.334A2.333 2.333 0 0 1 15 3.333v9.334A2.333 2.333 0 0 1 12.667 15H3.333A2.333 2.333 0 0 1 1 12.667zm2.59 2.298a.875.875 0 0 0 0 1.238L4.72 8 3.59 9.131a.875.875 0 0 0 1.237 1.238l1.75-1.75a.875.875 0 0 0 0-1.238l-1.75-1.75a.875.875 0 0 0-1.237 0m5.285 2.952a.875.875 0 1 0 0 1.75h2.917a.875.875 0 0 0 0-1.75z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ConsoleIcon.displayName = 'ConsoleIcon'
