'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ConsoleOutlineIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M2 5.167a2.56 2.56 0 0 1 2.563-2.563h10.875A2.563 2.563 0 0 1 18 5.167v9.666a2.563 2.563 0 0 1-2.562 2.563H4.563A2.563 2.563 0 0 1 2 14.833zm2.563-1.063c-.587 0-1.063.476-1.063 1.063v9.666c0 .587.476 1.063 1.063 1.063h10.875c.586 0 1.062-.476 1.062-1.063V5.167c0-.587-.476-1.063-1.062-1.063zm.608 1.821a.75.75 0 0 1 1.05-.15l2.416 1.813a.75.75 0 0 1 0 1.2L6.221 10.6a.75.75 0 1 1-.9-1.2l1.617-1.212L5.32 6.975a.75.75 0 0 1-.15-1.05M8.646 10a.75.75 0 0 1 .75-.75h2.416a.75.75 0 0 1 0 1.5H9.397a.75.75 0 0 1-.75-.75"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M1 3.771a2.24 2.24 0 0 1 2.242-2.242h9.516A2.24 2.24 0 0 1 15 3.77v8.458a2.24 2.24 0 0 1-2.242 2.243H3.242A2.24 2.24 0 0 1 1 12.229zm2.242-.93a.93.93 0 0 0-.93.93v8.458c0 .514.417.93.93.93h9.516a.93.93 0 0 0 .93-.93V3.771a.93.93 0 0 0-.93-.93zm.532 1.594a.656.656 0 0 1 .92-.132L6.807 5.89a.656.656 0 0 1 0 1.05L4.693 8.525a.656.656 0 1 1-.787-1.05l1.414-1.06-1.414-1.062a.656.656 0 0 1-.132-.918M6.815 8c0-.362.294-.656.656-.656h2.115a.656.656 0 0 1 0 1.312H7.47A.656.656 0 0 1 6.815 8"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ConsoleOutlineIcon.displayName = 'ConsoleOutlineIcon'
