'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const CreditCardIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="CreditCard">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="M3.333 4.667C2.597 4.667 2 5.264 2 6v.445h16V6c0-.736-.597-1.333-1.333-1.333z" />
        <path
          clipRule="evenodd"
          d="M18 8.667H2V14c0 .736.597 1.333 1.333 1.333h13.334c.736 0 1.333-.597 1.333-1.333zM3.778 12.889c0-.368.298-.667.666-.667h1.334a.667.667 0 0 1 0 1.334H4.444a.667.667 0 0 1-.666-.667M8 12.222a.667.667 0 0 0 0 1.334h3.111a.667.667 0 1 0 0-1.334z"
        />
      </>
    ) : (
      <>
        <path d="M2.5 3C1.67157 3 1 3.67157 1 4.5V5H15V4.5C15 3.67157 14.3284 3 13.5 3H2.5Z" />
        <path
          clipRule="evenodd"
          d="M15 7H1V11.5C1 12.3284 1.67157 13 2.5 13H13.5C14.3284 13 15 12.3284 15 11.5V7ZM3 10.25C3 9.83579 3.33579 9.5 3.75 9.5H4.25C4.66421 9.5 5 9.83579 5 10.25C5 10.6642 4.66421 11 4.25 11H3.75C3.33579 11 3 10.6642 3 10.25ZM6.75 9.5C6.33579 9.5 6 9.83579 6 10.25C6 10.6642 6.33579 11 6.75 11H9.25C9.66421 11 10 10.6642 10 10.25C10 9.83579 9.66421 9.5 9.25 9.5H6.75Z"
          fillRule="evenodd"
        />
      </>
    )}
  </Icon>
)
