'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CursorOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M2.47 2.47a.75.75 0 0 1 .865-.141l14.5 7.25a.75.75 0 0 1-.098 1.383l-5.083 1.693-1.692 5.082a.75.75 0 0 1-1.383.098l-7.25-14.5a.75.75 0 0 1 .14-.865m7.64 13.074 1.24-3.719a.75.75 0 0 1 .475-.473l3.72-1.242L4.677 4.677z" />
    ) : (
      <path d="M1.47 1.47a.75.75 0 0 1 .865-.141l12.5 6.25a.75.75 0 0 1-.098 1.383l-4.333 1.443-1.442 4.332a.75.75 0 0 1-1.383.098l-6.25-12.5a.75.75 0 0 1 .14-.865m6.64 11.074.99-2.969a.75.75 0 0 1 .475-.474l2.97-.99-8.868-4.434z" />
    )}
  </Icon>
)

CursorOutlineIcon.displayName = 'CursorOutlineIcon'
