'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DatabaseIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="M10 2c3.437 0 6.222 1.592 6.222 3.556S13.436 9.11 10 9.11 3.778 7.52 3.778 5.556 6.564 2 10 2" />
        <path d="M15.061 9.227c.412-.235.81-.518 1.161-.847V10c0 1.964-2.786 3.556-6.222 3.556S3.778 11.964 3.778 10V8.38a6.2 6.2 0 0 0 1.16.847c1.363.778 3.155 1.217 5.062 1.217s3.7-.439 5.061-1.217" />
        <path d="M3.778 12.825v1.62C3.778 16.407 6.564 18 10 18s6.222-1.592 6.222-3.556v-1.62a6.2 6.2 0 0 1-1.16.848c-1.362.778-3.155 1.217-5.062 1.217s-3.7-.439-5.061-1.217a6.2 6.2 0 0 1-1.161-.847" />
      </>
    ) : (
      <>
        <path d="M8 7c3.314 0 6-1.343 6-3s-2.686-3-6-3-6 1.343-6 3 2.686 3 6 3" />
        <path d="M8 8.5c1.84 0 3.579-.37 4.914-1.037A6.3 6.3 0 0 0 14 6.78V8c0 1.657-2.686 3-6 3S2 9.657 2 8V6.78c.346.273.72.5 1.087.683C4.42 8.131 6.16 8.5 8 8.5" />
        <path d="M8 12.5c1.84 0 3.579-.37 4.914-1.037.366-.183.74-.41 1.086-.684V12c0 1.657-2.686 3-6 3s-6-1.343-6-3v-1.22c.346.273.72.5 1.087.683C4.42 12.131 6.16 12.5 8 12.5" />
      </>
    )}
  </Icon>
)

DatabaseIcon.displayName = 'DatabaseIcon'
