'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const DatabaseIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DatabaseIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="M10 2c3.437 0 6.222 1.592 6.222 3.556S13.436 9.11 10 9.11 3.778 7.52 3.778 5.556 6.564 2 10 2" />
        <path d="M15.061 9.227c.412-.235.81-.518 1.161-.847V10c0 1.964-2.786 3.556-6.222 3.556S3.778 11.964 3.778 10V8.38a6.2 6.2 0 0 0 1.16.847c1.363.778 3.155 1.217 5.062 1.217s3.7-.439 5.061-1.217" />
        <path d="M3.778 12.825v1.62C3.778 16.407 6.564 18 10 18s6.222-1.592 6.222-3.556v-1.62a6.2 6.2 0 0 1-1.16.848c-1.362.778-3.155 1.217-5.062 1.217s-3.7-.439-5.061-1.217a6.2 6.2 0 0 1-1.161-.847" />
      </>
    ) : (
      <>
        <path d="M8 7C11.3137 7 14 5.65685 14 4C14 2.34315 11.3137 1 8 1C4.68629 1 2 2.34315 2 4C2 5.65685 4.68629 7 8 7Z" />
        <path d="M8 8.5002C9.83923 8.5002 11.5785 8.13064 12.9135 7.46316C13.2795 7.28013 13.6539 7.0526 14 6.7793V8.0002C14 9.65705 11.3137 11.0002 8 11.0002C4.68629 11.0002 2 9.65705 2 8.0002V6.7793C2.34614 7.0526 2.72049 7.28013 3.08654 7.46316C4.4215 8.13064 6.16077 8.5002 8 8.5002Z" />
        <path d="M8 12.5002C9.83923 12.5002 11.5785 12.1306 12.9135 11.4632C13.2795 11.2801 13.6539 11.0526 14 10.7793V12.0002C14 13.6571 11.3137 15.0002 8 15.0002C4.68629 15.0002 2 13.6571 2 12.0002V10.7793C2.34614 11.0526 2.72049 11.2801 3.08654 11.4632C4.4215 12.1306 6.16077 12.5002 8 12.5002Z" />
      </>
    )}
  </Icon>
)
