'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DocPaperOutlineIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        fillRule="evenodd"
        d="M5.26 3.5a.087.087 0 0 0-.087.087v12.827c0 .047.039.086.086.086h9.481a.086.086 0 0 0 .087-.087V9.721a1.76 1.76 0 0 0-1.76-1.76h-1.115c-.876 0-1.587-.71-1.587-1.586V5.26a1.76 1.76 0 0 0-1.76-1.76zm0-1.5c-.877 0-1.587.71-1.587 1.587v12.827c0 .876.71 1.586 1.586 1.586h9.481c.876 0 1.587-.71 1.587-1.587v-6.97A7.44 7.44 0 0 0 8.884 2zm6.43 2.203c.114.331.175.687.175 1.057v1.115c0 .048.039.087.087.087h1.115c.37 0 .726.061 1.057.175a5.97 5.97 0 0 0-2.434-2.434M6.461 12.23a.75.75 0 0 1 .75-.75h5.577a.75.75 0 0 1 0 1.5H7.211a.75.75 0 0 1-.75-.75m0 2.23a.75.75 0 0 1 .75-.75H10a.75.75 0 1 1 0 1.5H7.21a.75.75 0 0 1-.75-.75"
        clipRule="evenodd"
      />
    ) : (
      <>
        <path d="M10.251 10a.75.75 0 0 1 0 1.5H5.75a.75.75 0 0 1 0-1.5zm0-3a.75.75 0 0 1 0 1.5H5.75a.75.75 0 0 1 0-1.5z" />
        <path
          fillRule="evenodd"
          d="M8.88 1.25c.596 0 1.168.237 1.59.66l3.121 3.12c.422.422.66.995.66 1.591V12.5A2.25 2.25 0 0 1 12 14.75H4a2.25 2.25 0 0 1-2.25-2.25v-9A2.25 2.25 0 0 1 4 1.25zM4 2.75a.75.75 0 0 0-.75.75v9c0 .414.336.75.75.75h8a.75.75 0 0 0 .75-.75V6.621a.75.75 0 0 0-.22-.53L9.41 2.97a.75.75 0 0 0-.53-.22z"
          clipRule="evenodd"
        />
      </>
    )}
  </Icon>
)

DocPaperOutlineIcon.displayName = 'DocPaperOutlineIcon'
