'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DocPaperIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path
          fillRule="evenodd"
          d="M5.143 2a1.43 1.43 0 0 0-1.429 1.429V16.57c0 .79.64 1.429 1.429 1.429h9.714c.79 0 1.429-.64 1.429-1.429v-6a2.857 2.857 0 0 0-2.857-2.857H12c-.789 0-1.428-.64-1.428-1.428V4.857A2.857 2.857 0 0 0 7.714 2zm1.429 10.286a.57.57 0 0 1 .57-.572h5.715a.571.571 0 1 1 0 1.143H7.143a.57.57 0 0 1-.571-.571M7.142 14a.571.571 0 1 0 0 1.143H10A.571.571 0 0 0 10 14z"
          clipRule="evenodd"
        />
        <path d="M10.74 2.24c.607.702.974 1.617.974 2.617v1.429c0 .158.128.285.286.285h1.429c1 0 1.915.368 2.616.975A7.44 7.44 0 0 0 10.74 2.24" />
      </>
    ) : (
      <path
        fillRule="evenodd"
        d="M3.334 1a1.75 1.75 0 0 0-1.75 1.75v10.5c0 .966.783 1.75 1.75 1.75h9.333a1.75 1.75 0 0 0 1.75-1.75V6.392c0-.465-.184-.91-.513-1.238l-3.641-3.641A1.75 1.75 0 0 0 9.025 1zM4.5 7.708c0-.483.392-.875.875-.875h5.25a.875.875 0 0 1 0 1.75h-5.25a.875.875 0 0 1-.875-.875m0 3.5c0-.483.392-.875.875-.875h5.25a.875.875 0 0 1 0 1.75h-5.25a.875.875 0 0 1-.875-.875"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

DocPaperIcon.displayName = 'DocPaperIcon'
