'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EmailRemoveOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path
          d="M4.235 3.684C3 3.684 2 4.684 2 5.92v7.482c0 1.234 1 2.235 2.235 2.235h7.87v-1.263h-7.87a.97.97 0 0 1-.972-.972V8.118l5.145 3.166a2.24 2.24 0 0 0 2.342 0l1.355-.834v-.029h.047l3.743-2.303v2.303h1.263V5.92c0-1.234-1-2.235-2.235-2.235zm-.972 2.408V5.92c0-.536.435-.972.972-.972h10.688c.537 0 .972.436.972.972v.173c0 .338-.175.65-.463.828l-5.344 3.288a.97.97 0 0 1-1.018 0L3.726 6.92a.97.97 0 0 1-.463-.828"
          clipRule="evenodd"
        />
        <path
          d="M13.132 11.448a.63.63 0 0 1 .893 0l1.449 1.448 1.448-1.448a.631.631 0 1 1 .893.893l-1.448 1.449 1.448 1.448a.631.631 0 1 1-.893.893l-1.448-1.448-1.449 1.448a.631.631 0 1 1-.893-.893l1.449-1.448-1.449-1.449a.63.63 0 0 1 0-.893"
          clipRule="evenodd"
        />
      </>
    ) : (
      <>
        <path
          fillRule="evenodd"
          d="M2.955 2.474C1.875 2.474 1 3.349 1 4.429v6.547c0 1.08.875 1.955 1.955 1.955h6.887v-1.105H2.955a.85.85 0 0 1-.85-.85V6.354l4.502 2.77a1.96 1.96 0 0 0 2.05 0l1.185-.73v-.025h.041l3.275-2.015v2.015h1.105v-3.94c0-1.08-.875-1.955-1.955-1.955zm-.85 2.107v-.152c0-.47.38-.85.85-.85h9.353c.47 0 .85.38.85.85v.152a.85.85 0 0 1-.405.724L8.077 8.182a.85.85 0 0 1-.891 0L2.51 5.305a.85.85 0 0 1-.405-.724"
          clipRule="evenodd"
        />
        <path
          fillRule="evenodd"
          d="M10.74 9.267a.553.553 0 0 1 .782 0l1.268 1.267 1.267-1.267a.553.553 0 1 1 .781.782l-1.267 1.267 1.267 1.267a.552.552 0 1 1-.781.782l-1.267-1.267-1.268 1.267a.552.552 0 1 1-.781-.782l1.267-1.267-1.267-1.267a.553.553 0 0 1 0-.782"
          clipRule="evenodd"
        />
      </>
    )}
  </Icon>
)

EmailRemoveOutlineIcon.displayName = 'EmailRemoveOutlineIcon'
