'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EmailOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M2 6.049a2.36 2.36 0 0 1 2.359-2.36h11.282A2.36 2.36 0 0 1 18 6.05v7.897a2.36 2.36 0 0 1-2.359 2.36H4.359A2.36 2.36 0 0 1 2 13.945zm1.333 0v.182c0 .357.185.687.488.874l5.641 3.471c.33.203.746.203 1.076 0l5.64-3.471c.304-.187.489-.517.489-.874V6.05c0-.567-.46-1.026-1.026-1.026H4.359c-.566 0-1.026.46-1.026 1.026m13.334 2.32-5.43 3.342a2.36 2.36 0 0 1-2.473 0L3.334 8.37v5.576c0 .567.459 1.026 1.025 1.026h11.282c.566 0 1.026-.46 1.026-1.026z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M1 4.544c0-1.14.924-2.064 2.064-2.064h9.872c1.14 0 2.064.924 2.064 2.064v6.91c0 1.14-.924 2.064-2.064 2.064H3.064A2.064 2.064 0 0 1 1 11.454zm1.167 0v.16c0 .311.161.6.427.764L7.53 8.506a.9.9 0 0 0 .94 0l4.936-3.038a.9.9 0 0 0 .427-.764v-.16a.897.897 0 0 0-.897-.897H3.064a.897.897 0 0 0-.897.897m11.666 2.031L9.082 9.5c-.664.408-1.5.408-2.164 0L2.167 6.575v4.88c0 .495.401.897.897.897h9.872a.897.897 0 0 0 .897-.898z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

EmailOutlineIcon.displayName = 'EmailOutlineIcon'
