'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EmbeddingOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="M2.5 1.75a.75.75 0 0 1 .75.75v14.25H17.5a.75.75 0 0 1 0 1.5h-15a.75.75 0 0 1-.75-.75v-15a.75.75 0 0 1 .75-.75" />
        <path
          fillRule="evenodd"
          d="M14 9.75a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5m0 1.5a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5m-7-4a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5m0 1.5a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5m4-6.5a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5m0 1.5a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5"
          clipRule="evenodd"
        />
      </>
    ) : (
      <>
        <path d="M2 1.4a.6.6 0 0 1 .6.6v11.4H14a.6.6 0 1 1 0 1.2H2a.6.6 0 0 1-.6-.6V2a.6.6 0 0 1 .6-.6" />
        <path
          fillRule="evenodd"
          d="M11.199 7.801a2.2 2.2 0 1 1 .002 4.398 2.2 2.2 0 0 1-.002-4.398m0 1.199a1 1 0 1 0 0 2 1 1 0 0 0 0-2M5.6 5.801a2.2 2.2 0 1 1 .002 4.398A2.2 2.2 0 0 1 5.6 5.801M5.6 7a1 1 0 1 0 0 2 1 1 0 0 0 0-2m3.2-5.199a2.2 2.2 0 1 1 .002 4.398A2.2 2.2 0 0 1 8.8 1.801M8.8 3a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
          clipRule="evenodd"
        />
      </>
    )}
  </Icon>
)

EmbeddingOutlineIcon.displayName = 'EmbeddingOutlineIcon'
