'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EmbeddingIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="M2.5 1.75a.75.75 0 0 1 .75.75v14.25H17.5a.75.75 0 0 1 0 1.5h-15a.75.75 0 0 1-.75-.75v-15a.75.75 0 0 1 .75-.75" />
        <path d="M14 10a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5M7 7.5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5m4-5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5" />
      </>
    ) : (
      <>
        <path d="M2 1.4a.6.6 0 0 1 .6.6v11.4H14a.6.6 0 1 1 0 1.2H2a.6.6 0 0 1-.6-.6V2a.6.6 0 0 1 .6-.6" />
        <path d="M11.199 8a2 2 0 1 1 0 4 2 2 0 0 1 0-4M5.6 6c1.104 0 1.999.896 2 2a2 2 0 1 1-2-2m3.2-4a2 2 0 1 1-.001 4.001A2 2 0 0 1 8.8 2" />
      </>
    )}
  </Icon>
)

EmbeddingIcon.displayName = 'EmbeddingIcon'
