'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ExpandMoreIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ExpandMoreIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M12 18.17 8.83 15l-1.41 1.41L12 21l4.59-4.59L15.17 15M12 5.83 15.17 9l1.41-1.41L12 3 7.41 7.59 8.83 9z" />
    ) : (
      <path d="M12 18.17 8.83 15l-1.41 1.41L12 21l4.59-4.59L15.17 15M12 5.83 15.17 9l1.41-1.41L12 3 7.41 7.59 8.83 9z" />
    )}
  </Icon>
)
