'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ExpandMoreIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ExpandMoreIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M6.28653 13.3952C6.66856 13.0132 7.28796 13.0132 7.67 13.3952L9.91304 15.6383L12.1561 13.3952C12.5381 13.0132 13.1575 13.0132 13.5396 13.3952C13.9216 13.7773 13.9216 14.3967 13.5396 14.7787L10.6048 17.7135C10.2227 18.0955 9.60334 18.0955 9.22131 17.7135L6.28653 14.7787C5.90449 14.3967 5.90449 13.7773 6.28653 13.3952Z"
        />
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M13.5396 7.60478C13.1575 7.98681 12.5381 7.98681 12.1561 7.60478L9.91304 5.36173L7.67 7.60478C7.28796 7.98681 6.66856 7.98681 6.28653 7.60478C5.90449 7.22274 5.90449 6.60334 6.28653 6.22131L9.22131 3.28653C9.60334 2.90449 10.2227 2.90449 10.6048 3.28653L13.5396 6.22131C13.9216 6.60334 13.9216 7.22274 13.5396 7.60478Z"
        />
      </>
    ) : (
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M5.21967 9.96967C5.51256 9.67678 5.98744 9.67678 6.28033 9.96967L8 11.6893L9.71967 9.96967C10.0126 9.67678 10.4874 9.67678 10.7803 9.96967C11.0732 10.2626 11.0732 10.7374 10.7803 11.0303L8.53033 13.2803C8.23744 13.5732 7.76256 13.5732 7.46967 13.2803L5.21967 11.0303C4.92678 10.7374 4.92678 10.2626 5.21967 9.96967Z"
        />
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M10.7803 5.53033C10.4874 5.82322 10.0126 5.82322 9.71967 5.53033L8 3.81066L6.28033 5.53033C5.98744 5.82322 5.51256 5.82322 5.21967 5.53033C4.92678 5.23744 4.92678 4.76256 5.21967 4.46967L7.46967 2.21967C7.76256 1.92678 8.23744 1.92678 8.53033 2.21967L10.7803 4.46967C11.0732 4.76256 11.0732 5.23744 10.7803 5.53033Z"
        />
      </>
    )}
  </Icon>
)

ExpandMoreIcon.displayName = 'ExpandMoreIcon'
