'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ExpandMoreIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ExpandMoreIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        fillRule="evenodd"
        d="M6.287 13.395a.98.98 0 0 1 1.383 0l2.243 2.243 2.243-2.243a.979.979 0 0 1 1.384 1.384l-2.935 2.935a.98.98 0 0 1-1.384 0l-2.934-2.935a.977.977 0 0 1 0-1.384m7.253-5.79a.98.98 0 0 1-1.384 0L9.913 5.362 7.67 7.605a.978.978 0 1 1-1.383-1.384l2.934-2.934a.977.977 0 0 1 1.384 0l2.935 2.934a.98.98 0 0 1 0 1.384"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M5.22 9.97a.75.75 0 0 1 1.06 0L8 11.689 9.72 9.97a.749.749 0 1 1 1.06 1.06l-2.25 2.25a.75.75 0 0 1-1.06 0l-2.25-2.25a.75.75 0 0 1 0-1.06m5.56-4.44a.75.75 0 0 1-1.06 0L8 3.811 6.28 5.53a.749.749 0 1 1-1.06-1.06l2.25-2.25a.75.75 0 0 1 1.06 0l2.25 2.25a.75.75 0 0 1 0 1.06"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ExpandMoreIcon.displayName = 'ExpandMoreIcon'
