'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EyeOffIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="EyeOffIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path
          fillRule="evenodd"
          d="M4.309 3.41a.635.635 0 1 0-.898.899l12.28 12.28a.635.635 0 1 0 .9-.898l-1.479-1.478a8.5 8.5 0 0 0 2.795-3.708 1.4 1.4 0 0 0 0-1.005A8.473 8.473 0 0 0 5.982 5.083zm3.787 3.788.925.924a2.118 2.118 0 0 1 2.857 2.857l.925.925a3.388 3.388 0 0 0-4.707-4.707"
          clipRule="evenodd"
        />
        <path d="m10.634 13.329 2.137 2.137c-.868.3-1.8.463-2.77.463A8.47 8.47 0 0 1 2.093 10.5a1.4 1.4 0 0 1 0-1.005A8.5 8.5 0 0 1 3.935 6.63l2.738 2.737q-.06.309-.06.634a3.388 3.388 0 0 0 4.022 3.329" />
      </>
    ) : (
      <>
        <path
          fillRule="evenodd"
          d="M3.046 1.93a.788.788 0 1 0-1.114 1.114L12.957 14.07a.788.788 0 0 0 1.114-1.113l-1.389-1.39a7.36 7.36 0 0 0 2.268-3.265.9.9 0 0 0 0-.596A7.353 7.353 0 0 0 4.664 3.55zM6.4 5.287l1.192 1.192a1.577 1.577 0 0 1 1.93 1.93L10.715 9.6a3.15 3.15 0 0 0-4.314-4.314"
          clipRule="evenodd"
        />
        <path d="M7.804 11.144 9.71 13.05a7.353 7.353 0 0 1-8.66-4.756.9.9 0 0 1 0-.595 7.3 7.3 0 0 1 1.17-2.14l2.637 2.638a3.15 3.15 0 0 0 2.947 2.947" />
      </>
    )}
  </Icon>
)

EyeOffIcon.displayName = 'EyeOffIcon'
