'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const FilterIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Filter">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M3.447 2.534A40 40 0 0 1 10 2c2.231 0 4.42.183 6.553.534a.67.67 0 0 1 .558.658v2.033a2 2 0 0 1-.586 1.415l-4.162 4.162a2 2 0 0 0-.585 1.414v2.699a2 2 0 0 1-.751 1.562l-1.722 1.377a.667.667 0 0 1-1.083-.52v-5.118a2 2 0 0 0-.586-1.414L3.474 6.64a2 2 0 0 1-.585-1.415V3.192c0-.326.236-.605.558-.658"
      />
    ) : (
      <path d="M14.135 2.02252C14.135 1.4578 13.6772 1 13.1125 1H2.88727C2.32255 1 1.86475 1.4578 1.86475 2.02252V4.24301C1.86475 4.78539 2.08021 5.30555 2.46373 5.68907L5.35586 8.5812C5.73938 8.96472 5.95484 9.48489 5.95484 10.0273V14.4881C5.95484 14.8681 6.3548 15.1153 6.69474 14.9454L8.91445 13.8355C9.60728 13.4891 10.0449 12.781 10.0449 12.0064V10.0273C10.0449 9.48489 10.2604 8.96472 10.6439 8.5812L13.536 5.68907C13.9196 5.30555 14.135 4.78538 14.135 4.24301V2.02252Z" />
    )}
  </Icon>
)
