'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const FolderOutlineIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M3.75 3.875c-.621 0-1.125.504-1.125 1.125v2.628a2.6 2.6 0 0 1 1.125-.253h12.5a2.6 2.6 0 0 1 1.125.253V7.5c0-.621-.504-1.125-1.125-1.125h-4.482a2 2 0 0 1-1.414-.586L8.586 4.021a.5.5 0 0 0-.354-.146zM17.375 10c0-.621-.504-1.125-1.125-1.125H3.75c-.621 0-1.125.504-1.125 1.125v5c0 .621.504 1.125 1.125 1.125h12.5c.621 0 1.125-.504 1.125-1.125zm1.5 5a2.625 2.625 0 0 1-2.625 2.625H3.75A2.625 2.625 0 0 1 1.125 15V5A2.625 2.625 0 0 1 3.75 2.375h4.482a2 2 0 0 1 1.414.586l1.768 1.768a.5.5 0 0 0 .354.146h4.482A2.625 2.625 0 0 1 18.875 7.5z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M3 3.25a.75.75 0 0 0-.75.75v1.878q.354-.126.75-.128h10q.391.002.74.124A.75.75 0 0 0 13 5.25H9.414a1.75 1.75 0 0 1-1.237-.513L6.763 3.323a.25.25 0 0 0-.177-.073zM13.75 8a.75.75 0 0 0-.75-.75H3a.75.75 0 0 0-.75.75v4c0 .414.336.75.75.75h10a.75.75 0 0 0 .75-.75zm1.5 4A2.25 2.25 0 0 1 13 14.25H3A2.25 2.25 0 0 1 .75 12V4A2.25 2.25 0 0 1 3 1.75h3.586c.464 0 .909.184 1.237.513l1.414 1.414a.25.25 0 0 0 .177.073H13A2.25 2.25 0 0 1 15.25 6z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

FolderOutlineIcon.displayName = 'FolderOutlineIcon'
