'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const FolderOutlineIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="FolderOutlineIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M3.75 3.875c-.621 0-1.125.504-1.125 1.125v2.628a2.6 2.6 0 0 1 1.125-.253h12.5a2.6 2.6 0 0 1 1.125.253V7.5c0-.621-.504-1.125-1.125-1.125h-4.482a2 2 0 0 1-1.414-.586L8.586 4.021a.5.5 0 0 0-.354-.146zM17.375 10c0-.621-.504-1.125-1.125-1.125H3.75c-.621 0-1.125.504-1.125 1.125v5c0 .621.504 1.125 1.125 1.125h12.5c.621 0 1.125-.504 1.125-1.125zm1.5 5a2.625 2.625 0 0 1-2.625 2.625H3.75A2.625 2.625 0 0 1 1.125 15V5A2.625 2.625 0 0 1 3.75 2.375h4.482a2 2 0 0 1 1.414.586l1.768 1.768a.5.5 0 0 0 .354.146h4.482A2.625 2.625 0 0 1 18.875 7.5z"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M3 3.25C2.58579 3.25 2.25 3.58579 2.25 4V5.87803C2.48458 5.79512 2.73702 5.75 3 5.75H13C13.2591 5.75 13.5079 5.79379 13.7395 5.87436C13.6797 5.51996 13.3714 5.25 13 5.25H9.41421C8.95008 5.25 8.50497 5.06563 8.17678 4.73744L6.76256 3.32322C6.71568 3.27634 6.65209 3.25 6.58579 3.25H3ZM13.75 8C13.75 7.58579 13.4142 7.25 13 7.25H3C2.58579 7.25 2.25 7.58579 2.25 8V12C2.25 12.4142 2.58579 12.75 3 12.75H13C13.4142 12.75 13.75 12.4142 13.75 12V8ZM15.25 12C15.25 13.2426 14.2426 14.25 13 14.25H3C1.75736 14.25 0.75 13.2426 0.75 12V4C0.75 2.75736 1.75736 1.75 3 1.75H6.58579C7.04991 1.75 7.49503 1.93437 7.82322 2.26256L9.23744 3.67678C9.28432 3.72366 9.34791 3.75 9.41421 3.75H13C14.2426 3.75 15.25 4.75736 15.25 6V12Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
