'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const HandIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M8.966 2.8a.8.8 0 1 1 1.6 0v5.845q.553.173 1.066.468V3.867a.8.8 0 0 1 1.6 0v7.777a3.2 3.2 0 0 0-2.31 1.688 6.4 6.4 0 0 1 2.844-.665.533.533 0 0 0 .533-.534v-1.611c.003-.61.237-1.22.703-1.686a.8.8 0 0 1 1.131 1.132.8.8 0 0 0-.234.561v2.138h-.003a4.27 4.27 0 0 1-1.247 2.85l-1.234 1.233c-.8.8-1.885 1.25-3.017 1.25H8.966a5.333 5.333 0 0 1-5.334-5.333V6a.8.8 0 0 1 1.6 0v3.925A5.3 5.3 0 0 1 6.3 9.113V3.867a.8.8 0 1 1 1.6 0v4.64A5.4 5.4 0 0 1 8.966 8.4z" />
    ) : (
      <path d="M8 1a.75.75 0 0 0-.75.75V6.5a.5.5 0 0 1-1 0V2.75a.75.75 0 0 0-1.5 0V7.5a.5.5 0 0 1-1 0V4.75a.75.75 0 0 0-1.5 0v4.5a5.75 5.75 0 0 0 11.5 0v-2.5a.75.75 0 0 0-1.5 0V9.5a.5.5 0 0 1-1 0V2.75a.75.75 0 0 0-1.5 0V6.5a.5.5 0 0 1-1 0V1.75A.75.75 0 0 0 8 1" />
    )}
  </Icon>
)

HandIcon.displayName = 'HandIcon'
