'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const HeaderIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="HeaderIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M17.143 3.25c.473 0 .857.336.857.75s-.384.75-.857.75H2.857C2.384 4.75 2 4.414 2 4s.384-.75.857-.75zM2 10.306c0-1.245 0-1.867.249-2.343.219-.418.569-.758.999-.971.489-.242 1.129-.242 2.409-.242h8.686c1.28 0 1.92 0 2.409.242.43.213.78.553.999.971.249.476.249 1.098.249 2.343v2.888c0 1.245 0 1.867-.249 2.343a2.26 2.26 0 0 1-.999.971c-.489.242-1.129.242-2.409.242H5.657c-1.28 0-1.92 0-2.409-.242a2.26 2.26 0 0 1-.999-.971C2 15.061 2 14.439 2 13.194z" />
    ) : (
      <path d="M10.25 1.75a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5zM1 7.25c0-.932 0-1.398.152-1.765.203-.49.593-.88 1.083-1.083.367-.152.833-.152 1.765-.152h4c.932 0 1.398 0 1.765.152.49.203.88.593 1.083 1.083.152.367.152.833.152 1.765s0 1.398-.152 1.765c-.203.49-.593.88-1.083 1.083-.367.152-.833.152-1.765.152H4c-.932 0-1.398 0-1.765-.152a2 2 0 0 1-1.083-1.083C1 8.648 1 8.182 1 7.25" />
    )}
  </Icon>
)

HeaderIcon.displayName = 'HeaderIcon'
