'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ImageIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        fillRule="evenodd"
        d="M2 5.929C2 4.863 2.895 4 4 4h12c1.105 0 2 .863 2 1.929v8.142C18 15.137 17.105 16 16 16H4c-1.105 0-2-.864-2-1.929zm1.333 4.98v3.162c0 .356.299.643.667.643h12a.655.655 0 0 0 .667-.643v-2.305l-1.973-1.902a.684.684 0 0 0-.943 0L12.054 11.5l.417.403c.26.25.26.658 0 .909a.684.684 0 0 1-.942 0L6.916 8.364a.684.684 0 0 0-.943 0zm8.445-3.48c0 .473-.398.857-.89.857-.49 0-.888-.384-.888-.857 0-.474.398-.858.889-.858.49 0 .889.384.889.858"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M2 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2zm10.5 5.707a.5.5 0 0 0-.146-.353l-1-1a.5.5 0 0 0-.708 0L9.354 9.646a.5.5 0 0 1-.708 0L6.354 7.354a.5.5 0 0 0-.708 0l-2 2a.5.5 0 0 0-.146.353V12a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5zM12 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ImageIcon.displayName = 'ImageIcon'
