'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const InformationOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="InformationOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M10 3.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m7.25-3.02a.75.75 0 0 1 .75-.75h.006a.75.75 0 0 1 .75.75v.005a.75.75 0 0 1-.75.75H10a.75.75 0 0 1-.75-.75zm.244 3.16a.75.75 0 0 1-.434-1.415l.034-.017c1.035-.517 2.2.418 1.92 1.54l-.508 2.03a.75.75 0 0 1 .434 1.414l-.034.016c-1.035.518-2.2-.417-1.92-1.54z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M8 2.313a5.687 5.687 0 1 0 0 11.374A5.687 5.687 0 0 0 8 2.313M1 8a7 7 0 1 1 14 0A7 7 0 0 1 1 8m6.344-2.643c0-.363.294-.656.656-.656h.005c.363 0 .657.293.657.656v.005a.656.656 0 0 1-.657.656H8a.656.656 0 0 1-.656-.656zm.213 2.765a.657.657 0 0 1-.38-1.238l.03-.014c.906-.453 1.925.365 1.68 1.347l-.444 1.775a.657.657 0 0 1 .38 1.238l-.03.015c-.906.453-1.925-.365-1.68-1.347z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

InformationOutlineIcon.displayName = 'InformationOutlineIcon'
