'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ItalicIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ItalicIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        fillRule="evenodd"
        d="M8.681 3.75a.75.75 0 0 1 .75-.75h5.681a.75.75 0 0 1 0 1.5H12.76l-3.928 11h1.735a.75.75 0 0 1 0 1.5h-5.68a.75.75 0 0 1 0-1.5H7.24l3.928-11H9.431a.75.75 0 0 1-.75-.75"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M6.863 3.75a.75.75 0 0 1 .75-.75h3.863a.75.75 0 0 1 0 1.5h-1.43l-2.5 7h.84a.75.75 0 0 1 0 1.5H4.524a.75.75 0 0 1 0-1.5h1.43l2.5-7h-.84a.75.75 0 0 1-.75-.75"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ItalicIcon.displayName = 'ItalicIcon'
