'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const LockIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="LockIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M10.0023 2C7.79311 2 6.00225 3.79086 6.00225 6V9.11111H5.55781C4.57597 9.11111 3.78003 9.90705 3.78003 10.8889V16.2222C3.78003 17.2041 4.57597 18 5.55781 18H14.4467C15.4285 18 16.2245 17.2041 16.2245 16.2222V10.8889C16.2245 9.90705 15.4285 9.11111 14.4467 9.11111H14.0023V6C14.0023 3.79086 12.2114 2 10.0023 2ZM12.6689 9.11111V6C12.6689 4.52724 11.475 3.33333 10.0023 3.33333C8.52949 3.33333 7.33558 4.52724 7.33558 6V9.11111H12.6689Z"
        fillRule="evenodd"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M8 1C6.067 1 4.5 2.567 4.5 4.5L4.5 7C3.67157 7 3 7.67157 3 8.5V13.5C3 14.3284 3.67157 15 4.5 15H11.5C12.3284 15 13 14.3284 13 13.5V8.5C13 7.67157 12.3284 7 11.5 7V4.5C11.5 2.567 9.933 1 8 1ZM10 7V4.5C10 3.39543 9.10457 2.5 8 2.5C6.89543 2.5 6 3.39543 6 4.5V7H10Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
