'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const MoonOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M7.866 2.205a.7.7 0 0 1 .15.765 6.89 6.89 0 0 0 9.013 9.013.701.701 0 0 1 .917.917A8.293 8.293 0 0 1 2 9.709a8.29 8.29 0 0 1 5.1-7.655.7.7 0 0 1 .766.151M6.217 4.152a6.89 6.89 0 1 0 9.631 9.631q-.716.129-1.47.13a8.29 8.29 0 0 1-8.16-9.761"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M6.132 1.18c.176.175.228.44.133.67a6.029 6.029 0 0 0 7.886 7.886.613.613 0 0 1 .802.801A7.257 7.257 0 0 1 1 7.745a7.26 7.26 0 0 1 4.463-6.698.61.61 0 0 1 .67.133M4.69 2.883a6.029 6.029 0 1 0 8.427 8.427A7.255 7.255 0 0 1 4.69 2.883"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

MoonOutlineIcon.displayName = 'MoonOutlineIcon'
