'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const OcrOutlineIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="OcrOutlineIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M3.45 16.38V3.62c0-.895.725-1.62 1.62-1.62h3.77a7.71 7.71 0 0 1 7.71 7.71v6.67A1.62 1.62 0 0 1 14.93 18H5.07a1.62 1.62 0 0 1-1.62-1.62m7.54-4.64a1.28 1.28 0 1 0-2.561 0 1.28 1.28 0 0 0 2.56 0m1.5 0c0 .495-.132.959-.359 1.362l.72.717a.75.75 0 0 1-1.061 1.06l-.72-.717a2.78 2.78 0 1 1 1.419-2.422m-.58-5.22c0 .066.053.12.12.12h1.16c.407 0 .797.072 1.158.205A6.23 6.23 0 0 0 11.704 4.2c.133.362.206.753.206 1.16zm-6.96 9.86c0 .066.054.12.12.12h9.86a.12.12 0 0 0 .12-.12V10a1.86 1.86 0 0 0-1.86-1.86h-1.16a1.62 1.62 0 0 1-1.62-1.62V5.36A1.86 1.86 0 0 0 8.55 3.5H5.07a.12.12 0 0 0-.12.12z" />
    ) : (
      <>
        <path d="M1.521 12.688V3.313A2.31 2.31 0 0 1 3.834 1h5.082c.613 0 1.2.244 1.634.678l3.252 3.25c.434.434.677 1.022.677 1.635v6.125A2.31 2.31 0 0 1 12.167 15H3.833a2.31 2.31 0 0 1-2.313-2.312m1.5 0c0 .448.364.812.813.812h8.332a.813.813 0 0 0 .813-.812V6.563a.8.8 0 0 0-.237-.574L9.49 2.74a.8.8 0 0 0-.574-.239H3.833a.81.81 0 0 0-.812.813z" />
        <path
          fillRule="evenodd"
          d="M7.48 4.354a3.125 3.125 0 0 1 2.692 4.712l1.246 1.246a.782.782 0 0 1-1.106 1.105l-1.245-1.245A3.126 3.126 0 1 1 7.48 4.354m0 1.563a1.562 1.562 0 1 0 0 3.125 1.562 1.562 0 0 0 0-3.125"
          clipRule="evenodd"
        />
      </>
    )}
  </Icon>
)

OcrOutlineIcon.displayName = 'OcrOutlineIcon'
