'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PauseOutlineIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M16.5 10a6.5 6.5 0 1 0-13 0 6.5 6.5 0 0 0 13 0m-9.062 2.417V7.583a.75.75 0 0 1 1.5 0v4.834a.75.75 0 0 1-1.5 0m3.625 0V7.583a.75.75 0 0 1 1.5 0v4.834a.75.75 0 0 1-1.5 0M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0" />
    ) : (
      <>
        <path d="M8 1a7 7 0 1 1 0 14A7 7 0 0 1 8 1m0 1.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11" />
        <path d="M5.5 5.5A.5.5 0 0 1 6 5h.5a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-.5.5H6a.5.5 0 0 1-.5-.5zm4-.5a.5.5 0 0 0-.5.5v5a.5.5 0 0 0 .5.5h.5a.5.5 0 0 0 .5-.5v-5A.5.5 0 0 0 10 5z" />
      </>
    )}
  </Icon>
)

PauseOutlineIcon.displayName = 'PauseOutlineIcon'
