'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const Pen2OutlineIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Pen2">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M16.433 3.567a.73.73 0 0 0-1.035 0l-.79.79 1.036 1.035.79-.79a.73.73 0 0 0 0-1.035m-1.745 2.781-1.036-1.036-9.048 9.048c-.317.318-.551.71-.68 1.14l-.243.82.819-.245c.43-.128.822-.362 1.14-.68zm-.247-3.737a2.085 2.085 0 0 1 2.949 2.947L6.596 16.352a4.06 4.06 0 0 1-1.71 1.02l-2.017.6a.676.676 0 0 1-.84-.841l.6-2.017a4.06 4.06 0 0 1 1.02-1.71z"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M10.4907 1.77368C11.5222 0.742107 13.1948 0.742107 14.2263 1.77368C15.2579 2.80525 15.2579 4.47775 14.2263 5.50932L6.5539 13.1817C6.21048 13.5252 5.80278 13.7976 5.35408 13.9834L3.19143 14.8792C2.59919 15.1245 1.91749 14.9889 1.46423 14.5356C1.01096 14.0823 0.875376 13.4006 1.1207 12.8083L1.85282 13.1116L1.1207 12.8083L2.01645 10.646C2.20229 10.1973 2.47468 9.78967 2.81806 9.44629L10.4907 1.77368ZM13.1056 2.89437C12.693 2.48174 12.024 2.48174 11.6114 2.89437L3.93876 10.567C3.74254 10.7632 3.58689 10.9961 3.48069 11.2525L2.74857 10.9492L3.48069 11.2525L2.58495 13.4149L4.74759 12.5192C5.004 12.413 5.23697 12.2573 5.43321 12.0611L13.1056 4.38863C13.5183 3.976 13.5183 3.307 13.1056 2.89437Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
