'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const Pen2Icon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="m3.243 14.325-1.208 3.018a.478.478 0 0 0 .622.621l3.018-1.207a3.8 3.8 0 0 0 1.285-.847L17.406 5.465a2.03 2.03 0 0 0-2.87-2.87L4.09 13.04a3.8 3.8 0 0 0-.847 1.285" />
    ) : (
      <path
        fillRule="evenodd"
        d="M11.44 1.61a2.085 2.085 0 0 1 2.95 2.95l-8.654 8.65a3.3 3.3 0 0 1-1.063.71l-2.438 1.01a.894.894 0 0 1-1.168-1.167l1.01-2.438c.165-.398.406-.759.71-1.063z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

Pen2Icon.displayName = 'Pen2Icon'
