'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PencilIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <>
        <path d="m5.407 13.947 1.253-3.13c.2-.5.498-.953.878-1.333l6.868-6.867a2.105 2.105 0 1 1 2.977 2.977l-6.867 6.867c-.38.38-.834.68-1.333.879l-3.13 1.252a.496.496 0 0 1-.646-.645" />
        <path d="M3.489 5.842a1.24 1.24 0 0 1 1.24-1.241H9.94a.744.744 0 0 0 0-1.489H4.73A2.73 2.73 0 0 0 2 5.842v9.428A2.73 2.73 0 0 0 4.73 18h9.428a2.73 2.73 0 0 0 2.73-2.73v-5.21a.744.744 0 0 0-1.49 0v5.21a1.24 1.24 0 0 1-1.24 1.241H4.73a1.24 1.24 0 0 1-1.24-1.24z" />
      </>
    ) : (
      <>
        <path d="M14.402 1.598a2.04 2.04 0 0 0-2.887 0L6.543 6.57a3.2 3.2 0 0 0-.696 1.04l-.989 2.388a.875.875 0 0 0 1.144 1.144l2.387-.99a3.2 3.2 0 0 0 1.041-.695l4.972-4.972a2.04 2.04 0 0 0 0-2.887" />
        <path d="M4.208 2.75c-.805 0-1.458.653-1.458 1.458v7.584c0 .805.653 1.458 1.458 1.458h7.584c.805 0 1.458-.653 1.458-1.458V9.167a.875.875 0 1 1 1.75 0v2.625A3.21 3.21 0 0 1 11.792 15H4.208A3.21 3.21 0 0 1 1 11.792V4.208A3.21 3.21 0 0 1 4.208 1h2.625a.875.875 0 1 1 0 1.75z" />
      </>
    )}
  </Icon>
)

PencilIcon.displayName = 'PencilIcon'
