'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const PinIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="PinIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M10.877 2.513a1.75 1.75 0 0 1 2.478 0l4.132 4.132a1.75 1.75 0 0 1 0 2.478l-3.741 3.741a1.28 1.28 0 0 0-.359.917 7.54 7.54 0 0 1-.847 3.501c-.465.899-1.658.933-2.374.218L7.16 14.493l-2.48 2.48a1.168 1.168 0 1 1-1.653-1.653l2.48-2.48L2.5 9.834c-.715-.716-.681-1.909.218-2.374a7.54 7.54 0 0 1 3.5-.848 1.28 1.28 0 0 0 .918-.358z" />
    ) : (
      <path d="M8.76726 1.44911C9.36607 0.850296 10.3369 0.850296 10.9357 1.44911L14.5509 5.0643C15.1497 5.66311 15.1497 6.63398 14.5509 7.2328L11.2774 10.5063C11.0664 10.7174 10.9626 11.0102 10.964 11.3087C10.9687 12.3556 10.7211 13.4097 10.2227 14.3721C9.81545 15.1584 8.77171 15.1883 8.14563 14.5622L5.51468 11.9312L3.34486 14.1011C2.94558 14.5003 2.29823 14.5003 1.89895 14.1011C1.49967 13.7018 1.49967 13.0544 1.89895 12.6551L4.06878 10.4853L1.43781 7.85431C0.811725 7.22822 0.841635 6.18448 1.62785 5.77727C2.59035 5.27876 3.64453 5.03119 4.69144 5.03594C4.98998 5.03729 5.28282 4.93358 5.49392 4.72248L8.76726 1.44911Z" />
    )}
  </Icon>
)
