'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const PlayOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M10 3.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m6.938-1.746v3.492L12.08 10zm-1.5-.761c0-.803.861-1.31 1.563-.92l4.513 2.507a1.053 1.053 0 0 1 0 1.84L9 13.427a1.052 1.052 0 0 1-1.563-.92z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M8 2.313a5.687 5.687 0 1 0 0 11.374A5.687 5.687 0 0 0 8 2.313M1 8a7 7 0 1 1 14 0A7 7 0 0 1 1 8m6.07-1.528v3.056L9.82 8zm-1.312-.666a.92.92 0 0 1 1.367-.805l3.95 2.194a.92.92 0 0 1 0 1.61l-3.95 2.194a.92.92 0 0 1-1.367-.805z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

PlayOutlineIcon.displayName = 'PlayOutlineIcon'
