'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const SendIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="SendIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M2.778 2.213a.609.609 0 0 0-.751.764L4 9.39h6.91a.609.609 0 0 1 0 1.218H4l-1.974 6.414a.609.609 0 0 0 .752.764 49.1 49.1 0 0 0 14.968-7.293.61.61 0 0 0 0-.988A49.1 49.1 0 0 0 2.778 2.213" />
    ) : (
      <path d="M1.94507 2.00973C1.65385 1.96448 1.36078 2.07913 1.17756 2.30996C0.99435 2.5408 0.949239 2.85225 1.05943 3.12559L2.51452 6.73513C2.68113 7.14841 3.08205 7.41906 3.52765 7.41906H7.8229C8.27536 7.41906 8.64216 7.78586 8.64216 8.23832C8.64216 8.69079 8.27536 9.05758 7.8229 9.05758H3.52793C3.08233 9.05758 2.68141 9.32824 2.5148 9.74151L1.05943 13.3518C0.949239 13.6251 0.99435 13.9365 1.17756 14.1674C1.36078 14.3982 1.65385 14.5129 1.94507 14.4676C6.71444 13.7265 11.0752 11.7514 14.6903 8.88021C14.8859 8.72479 15 8.48856 15 8.23867C15 7.98878 14.8859 7.75255 14.6903 7.59713C11.0752 4.72593 6.71444 2.75086 1.94507 2.00973Z" />
    )}
  </Icon>
)
