'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ShieldOutlineIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M16.245 8.218c0-.753-.1-1.482-.281-2.176A10.03 10.03 0 0 1 10 3.747a10.03 10.03 0 0 1-5.965 2.295A8.58 8.58 0 0 0 10 16.471c3.603-1.016 6.245-4.326 6.245-8.253m1.5 0c0 4.696-3.212 8.64-7.558 9.759a.75.75 0 0 1-.374 0c-4.345-1.119-7.557-5.063-7.557-9.76 0-1.098.176-2.157.502-3.149l.046-.11a.75.75 0 0 1 .675-.405h.11a8.54 8.54 0 0 0 5.895-2.348l.115-.09a.75.75 0 0 1 .916.09 8.55 8.55 0 0 0 5.897 2.349l.108-.001a.75.75 0 0 1 .722.515c.326.992.503 2.051.503 3.15" />
    ) : (
      <path d="M13.066 4.828A9.45 9.45 0 0 1 8 2.507a9.44 9.44 0 0 1-5.067 2.321q-.004.15-.004.3A9.44 9.44 0 0 0 8 13.498a9.44 9.44 0 0 0 5.067-8.669m1.505.3c0 4.222-2.392 7.883-5.888 9.705a1.48 1.48 0 0 1-1.366 0A10.94 10.94 0 0 1 1.435 4.76l.01-.135a1.48 1.48 0 0 1 1.28-1.282l.304-.045a7.95 7.95 0 0 0 3.986-1.921l.109-.089a1.48 1.48 0 0 1 1.753 0l.109.089.223.192a7.94 7.94 0 0 0 4.068 1.774c.674.086 1.195.62 1.277 1.282l.01.135z" />
    )}
  </Icon>
)

ShieldOutlineIcon.displayName = 'ShieldOutlineIcon'
