'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ShieldIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M9.661 2.036a.53.53 0 0 1 .678 0 11.95 11.95 0 0 0 7.078 2.75.5.5 0 0 1 .479.425Q18 5.99 18 6.8c0 5.162-3.26 9.563-7.834 11.256a.48.48 0 0 1-.332 0C5.26 16.363 2 11.962 2 6.8q0-.807.104-1.588a.5.5 0 0 1 .48-.426 11.95 11.95 0 0 0 7.077-2.75"
        clipRule="evenodd"
      />
    ) : (
      <path
        d="M6.976 1.208a.815.815 0 0 1 1.087 0 9.74 9.74 0 0 0 5.26 2.41.815.815 0 0 1 .71.78q.006.193.006.386c0 4.403-2.494 8.222-6.143 10.124a.82.82 0 0 1-.753 0 11.41 11.41 0 0 1-6.137-10.51.815.815 0 0 1 .711-.78 9.74 9.74 0 0 0 5.26-2.41"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

ShieldIcon.displayName = 'ShieldIcon'
