'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ShieldIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ShieldIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M9.66109 2.03588C9.85709 1.87313 10.1429 1.87313 10.3389 2.03588C12.2777 3.64574 14.7315 4.65679 17.4166 4.78533C17.658 4.79688 17.8641 4.9712 17.8957 5.21075C17.9645 5.7306 18 6.26096 18 6.7996C18 11.962 14.7401 16.3631 10.1665 18.0565C10.0593 18.0962 9.94102 18.0962 9.83378 18.0565C5.26004 16.3632 2 11.962 2 6.79948C2 6.26088 2.03548 5.73057 2.10424 5.21075C2.13593 4.97121 2.34202 4.79688 2.58337 4.78533C5.2685 4.6568 7.72231 3.64574 9.66109 2.03588Z"
        fillRule="evenodd"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M6.97605 1.20794C7.28546 0.931011 7.75362 0.931011 8.06304 1.20794C9.4992 2.49335 11.3157 3.35958 13.3221 3.61751C13.7185 3.66846 14.0194 3.9993 14.0327 4.39871C14.0369 4.5268 14.0391 4.6554 14.0391 4.78446C14.0391 9.18733 11.5449 13.0063 7.8962 14.908C7.66016 15.031 7.37892 15.031 7.14289 14.908C3.49418 13.0063 1 9.18733 1 4.78446C1 4.65539 1.00215 4.5268 1.00641 4.3987C1.01969 3.9993 1.32063 3.66846 1.71699 3.61751C3.72336 3.35958 5.53988 2.49335 6.97605 1.20794Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
