'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const SouthShortIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="SouthShort">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M9.792 2a.75.75 0 0 1 .75.75v12.69l4.761-4.762a.75.75 0 0 1 1.06 1.06l-6.041 6.042a.75.75 0 0 1-1.06 0L3.22 11.74a.75.75 0 0 1 1.06-1.061l4.762 4.761V2.75a.75.75 0 0 1 .75-.75"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M8.125 2a.75.75 0 0 1 .75.75v8.69l3.095-3.095a.75.75 0 1 1 1.06 1.06L8.655 13.78a.75.75 0 0 1-1.06 0L3.22 9.405a.75.75 0 0 1 1.06-1.06l3.095 3.094V2.75a.75.75 0 0 1 .75-.75"
      />
    )}
  </Icon>
)
