'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const StarIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="StarIcon">
    {typeof props.size === 'string' &&
    ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        clipRule="evenodd"
        d="M10 3C10.3754 3 10.7139 3.22129 10.8581 3.56092L12.6065 7.68022L17.1449 8.03674C17.5191 8.06614 17.8385 8.31323 17.9545 8.66306C18.0705 9.01289 17.9603 9.39675 17.6752 9.63604L14.2174 12.5384L15.2739 16.8781C15.361 17.2359 15.2198 17.6099 14.9161 17.8261C14.6124 18.0423 14.2058 18.0582 13.8855 17.8665L10 15.541L6.11451 17.8665C5.79416 18.0582 5.38755 18.0423 5.08386 17.8261C4.78018 17.6099 4.63905 17.2359 4.72615 16.8781L5.78255 12.5384L2.32478 9.63604C2.0397 9.39675 1.92953 9.01289 2.04552 8.66306C2.16152 8.31323 2.48091 8.06614 2.85509 8.03674L7.39348 7.68022L9.14195 3.56092C9.2861 3.22129 9.62462 3 10 3Z"
        fillRule="evenodd"
      />
    ) : (
      <path
        clipRule="evenodd"
        d="M8 2C8.32846 2 8.62466 2.19179 8.7508 2.48613L10.2807 6.05619L14.2518 6.36518C14.5792 6.39065 14.8587 6.6048 14.9602 6.90799C15.0617 7.21117 14.9653 7.54385 14.7158 7.75124L11.6903 10.2666L12.6146 14.0277C12.6908 14.3378 12.5673 14.6619 12.3016 14.8493C12.0359 15.0367 11.6801 15.0505 11.3998 14.8843L8 12.8688L4.6002 14.8843C4.31989 15.0505 3.96411 15.0367 3.69838 14.8493C3.43265 14.6619 3.30917 14.3378 3.38538 14.0277L4.30973 10.2666L1.28419 7.75124C1.03474 7.54385 0.938335 7.21117 1.03983 6.90799C1.14133 6.6048 1.4208 6.39065 1.7482 6.36518L5.71929 6.05619L7.2492 2.48613C7.37534 2.19179 7.67154 2 8 2Z"
        fillRule="evenodd"
      />
    )}
  </Icon>
)
