'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const UnlockOutlineIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path
        d="M10.429 6.286a4.286 4.286 0 0 1 8.571 0v2.946a.75.75 0 0 1-1.5 0V6.286a2.786 2.786 0 1 0-5.571 0v2.201A2.52 2.52 0 0 1 14.286 11v5.304a2.52 2.52 0 0 1-2.518 2.517h-8.25A2.52 2.52 0 0 1 1 16.304V11a2.52 2.52 0 0 1 2.518-2.518h6.91zM3.518 9.982c-.562 0-1.018.456-1.018 1.018v5.304c0 .562.456 1.017 1.018 1.017h8.25c.562 0 1.018-.455 1.018-1.017V11c0-.562-.456-1.018-1.018-1.018z"
        clipRule="evenodd"
      />
    ) : (
      <path
        fillRule="evenodd"
        d="M8.343 5.029a3.429 3.429 0 0 1 6.857 0v2.357a.6.6 0 1 1-1.2 0V5.029a2.229 2.229 0 1 0-4.457 0v1.76A2.014 2.014 0 0 1 11.429 8.8v4.243a2.014 2.014 0 0 1-2.015 2.014h-6.6A2.014 2.014 0 0 1 .8 13.043V8.8c0-1.112.902-2.014 2.014-2.014h5.529zM2.814 7.986A.814.814 0 0 0 2 8.8v4.243c0 .45.365.814.814.814h6.6c.45 0 .815-.364.815-.814V8.8a.814.814 0 0 0-.815-.814z"
        clipRule="evenodd"
      />
    )}
  </Icon>
)

UnlockOutlineIcon.displayName = 'UnlockOutlineIcon'
