'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const UnpinIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M3.17 2.2a.686.686 0 0 0-.976.963L16.4 17.37l.007.007.422.422a.686.686 0 0 0 .97-.97l-4.292-4.292 2.853-2.854a1.6 1.6 0 0 0 0-2.266L12.583 3.64a1.6 1.6 0 0 0-2.266 0L7.463 6.493zm9.297 13.176L4.624 7.533a7 7 0 0 0-1.767.63c-.822.425-.853 1.515-.199 2.17l2.75 2.749-2.268 2.267a1.068 1.068 0 1 0 1.511 1.51l2.267-2.267 2.75 2.75c.654.654 1.744.623 2.17-.199.292-.565.502-1.16.629-1.767" />
    ) : (
      <path d="M2.558 1.224a.764.764 0 0 0-1.08 1.08l.365.364a1 1 0 0 1 .089.077l11.853 11.853a.764.764 0 0 0 .991-1.156l-3.585-3.585 1.635-1.636a1.337 1.337 0 0 0 0-1.892L9.671 3.174a1.337 1.337 0 0 0-1.892 0L6.143 4.809zm7.081 11.387-6.25-6.25a5.8 5.8 0 0 0-1.841.59c-.686.355-.712 1.266-.166 1.813l2.296 2.296-1.893 1.894a.891.891 0 1 0 1.261 1.262l1.894-1.894 2.296 2.296c.547.546 1.457.52 1.813-.166a5.8 5.8 0 0 0 .59-1.841" />
    )}
  </Icon>
)

UnpinIcon.displayName = 'UnpinIcon'
