'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const VideoIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="VideoIcon">
    {typeof props.size === 'string' && ['medium', 'large', 'xlarge', 'xxlarge'].includes(props.size) ? (
      <path d="M4 4.667C2.895 4.667 2 5.562 2 6.667V13.333C2 14.438 2.895 15.333 4 15.333H10.667C11.771 15.333 12.667 14.438 12.667 13.333V6.667C12.667 5.562 11.771 4.667 10.667 4.667H4ZM18 5.333C18 5.064 17.838 4.821 17.589 4.718 17.339 4.614 17.053 4.671 16.862 4.862L14.195 7.529C14.07 7.654 14 7.823 14 8V12C14 12.177 14.07 12.347 14.195 12.472L16.862 15.138C17.053 15.329 17.339 15.386 17.589 15.283 17.838 15.18 18 14.936 18 14.667V5.333Z" />
    ) : (
      <path d="M3.714 4.571C2.768 4.571 2 5.339 2 6.286V9.714C2 10.661 2.768 11.428 3.714 11.428H8C8.947 11.428 9.714 10.661 9.714 9.714V6.286C9.714 5.339 8.947 4.571 8 4.571H3.714ZM14 5.214C14 4.954 13.843 4.72 13.603 4.62 13.363 4.521 13.086 4.576 12.903 4.76L11.188 6.474C11.068 6.594 11 6.758 11 6.928V9.071C11 9.242 11.068 9.405 11.188 9.526L12.903 11.24C13.086 11.424 13.363 11.479 13.603 11.38 13.843 11.28 14 11.046 14 10.786V5.214Z" />
    )}
  </Icon>
)
