/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const partnerProgram = `${BASE_URL}/various/people/partnerProgram.webp`

export { partnerProgram }
