/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const AddressOutline = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M10 3.489c-3.038 0-5.5 2.445-5.5 5.46 0 2.681 1.418 4.83 2.912 6.349A15 15 0 0 0 10 17.387a15 15 0 0 0 2.589-2.089c1.493-1.518 2.911-3.668 2.911-6.35 0-3.014-2.462-5.459-5.5-5.459m0 14.767-.36.652h-.002l-.001-.001-.006-.003-.017-.01a7 7 0 0 1-.276-.162 16.4 16.4 0 0 1-3-2.394C4.707 14.68 3 12.176 3 8.948 3 5.112 6.134 2 10 2s7 3.111 7 6.949c0 3.227-1.707 5.73-3.338 7.389a16.4 16.4 0 0 1-3 2.394 9 9 0 0 1-.276.162l-.017.01-.006.003h-.002v.001zm0 0 .36.652a.76.76 0 0 1-.72 0zm0-11.044c-.966 0-1.75.777-1.75 1.737s.784 1.737 1.75 1.737 1.75-.778 1.75-1.737-.784-1.737-1.75-1.737M6.75 8.949c0-1.782 1.455-3.226 3.25-3.226s3.25 1.444 3.25 3.226-1.455 3.226-3.25 3.226-3.25-1.444-3.25-3.226"
      clipRule="evenodd"
    />
  </Icon>
)
