/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const AutoFixOutline = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <path d="m16.43 6.143.806-1.766 1.766-.806-1.766-.805L16.431 1l-.806 1.766-1.766.805 1.766.806zm-9.856 0 .805-1.766 1.766-.806-1.766-.805L6.574 1l-.806 1.766-1.766.805 1.766.806zm9.856 4.713-.805 1.766-1.766.806 1.766.806.806 1.765.805-1.765 1.766-.806-1.765-.806zM14.468 7.96l-2.426-2.425a.88.88 0 0 0-.608-.249.88.88 0 0 0-.609.249l-9.574 9.574a.854.854 0 0 0 0 1.208l2.425 2.426a.85.85 0 0 0 .609.257.88.88 0 0 0 .609-.248l9.574-9.575a.864.864 0 0 0 0-1.217m-3.034-.6 1.208 1.209-1.003 1.003-1.208-1.209zm-7.149 9.575-1.209-1.209 6.146-6.154 1.209 1.208z" />
  </IconV2>
)
