/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */

import type { ReactNode } from 'react'
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const Cancel = ({
  children,
  ...props
}: { children: ReactNode } & IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <svg xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        d="m5.965 4.904 9.131 9.131a6.5 6.5 0 0 0-9.131-9.131m8.07 10.192L4.904 5.965a6.5 6.5 0 0 0 9.131 9.131M4.343 4.343a8 8 0 1 1 11.314 11.314A8 8 0 0 1 4.343 4.343"
        clipRule="evenodd"
      />
    </svg>
  </IconV2>
)
