/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const ClockOutlineOutline = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <path
      fill-rule="evenodd"
      d="M10 3.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m8-5.583a.75.75 0 0 1 .75.75V9.25h2.875a.75.75 0 0 1 0 1.5H10a.75.75 0 0 1-.75-.75V5.167a.75.75 0 0 1 .75-.75"
      clip-rule="evenodd"
    />
  </IconV2>
)
