/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CreditCardOutline = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M1.125 5.625A2.625 2.625 0 0 1 3.75 3h12.5a2.625 2.625 0 0 1 2.625 2.625v8.75A2.625 2.625 0 0 1 16.25 17H3.75a2.625 2.625 0 0 1-2.625-2.625zm1.5 2.625v6.125c0 .621.504 1.125 1.125 1.125h12.5c.621 0 1.125-.504 1.125-1.125V8.25zm14.75-2.125H2.625v-.5c0-.621.504-1.125 1.125-1.125h12.5c.621 0 1.125.504 1.125 1.125zm-13.75 5.75a.75.75 0 0 1 .75-.75h5a.75.75 0 0 1 0 1.5h-5a.75.75 0 0 1-.75-.75m0 1.875a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5h-2.5a.75.75 0 0 1-.75-.75"
      clipRule="evenodd"
    />
  </Icon>
)
