/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const DotsHorizontal = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <path d="M3 10.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0m5.5 0a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0m7-1.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3" />
  </IconV2>
)
