/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */

import type { ReactNode } from 'react'
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const EastShort = ({
  children,
  ...props
}: { children: ReactNode } & IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      fill="none"
      viewBox="0 0 20 20"
    >
      <path
        d="M10.678 3.22a.75.75 0 0 1 1.06 0l6.042 6.04a.75.75 0 0 1 0 1.061l-6.041 6.042a.75.75 0 0 1-1.061-1.061l4.761-4.761H2.75a.75.75 0 0 1 0-1.5h12.69L10.677 4.28a.75.75 0 0 1 0-1.06"
        clipRule="evenodd"
      />
    </svg>
  </IconV2>
)
