/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EmailRemove = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M0 6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v1.161l-8.441 4.221a1.25 1.25 0 0 1-1.118 0L0 7.162zm15.065 4.306L18 8.84v1.224a2 2 0 0 0-.914.523l-.836.836-.836-.836a2 2 0 0 0-.35-.28" />
    <path d="m12.007 11.835-1.777.889a2.75 2.75 0 0 1-2.46 0L0 8.839V14a2 2 0 0 0 2 2h10.063a2 2 0 0 1 .523-.914l.836-.836-.836-.836a2 2 0 0 1-.58-1.579" />
    <path
      fillRule="evenodd"
      d="M13.22 11.22a.75.75 0 0 1 1.06 0L16 12.94l1.72-1.72a.75.75 0 1 1 1.06 1.06L17.06 14l1.72 1.72a.75.75 0 1 1-1.06 1.06L16 15.06l-1.72 1.72a.75.75 0 1 1-1.06-1.06L14.94 14l-1.72-1.72a.75.75 0 0 1 0-1.06"
      clipRule="evenodd"
    />
  </Icon>
)
