/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const Eye = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <path d="M10 12.052a2.382 2.382 0 1 0 0-4.764 2.382 2.382 0 0 0 0 4.764" />
    <path
      fill-rule="evenodd"
      d="M1.105 10.233a1.57 1.57 0 0 1 0-1.13 9.532 9.532 0 0 1 17.79.004c.14.364.14.767 0 1.13a9.532 9.532 0 0 1-17.79-.005m12.707-.563a3.811 3.811 0 1 1-7.623 0 3.811 3.811 0 0 1 7.623 0"
      clip-rule="evenodd"
    />
  </IconV2>
)
