/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const EyeOutline = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M10 4.5a7.9 7.9 0 0 0-7.496 5.403.1.1 0 0 0 0 .053 7.902 7.902 0 0 0 14.992-.005.1.1 0 0 0 0-.052A7.9 7.9 0 0 0 10 4.5M1.08 9.43a9.402 9.402 0 0 1 17.839-.005c.108.324.108.675 0 1a9.402 9.402 0 0 1-17.838.005 1.6 1.6 0 0 1 0-1M10 8.206a1.721 1.721 0 1 0 0 3.442 1.721 1.721 0 0 0 0-3.442M6.78 9.927a3.221 3.221 0 1 1 6.441 0 3.221 3.221 0 0 1-6.442 0"
      clipRule="evenodd"
    />
  </Icon>
)
