/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const HelpCircleOutline = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M10 3.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m9.215-3.045c-.66-.579-1.769-.579-2.43 0a.75.75 0 1 1-.988-1.13c1.227-1.072 3.18-1.072 4.406 0 1.285 1.125 1.285 2.995 0 4.12-.217.19-.456.345-.707.467-.531.257-.746.58-.746.796v.604a.75.75 0 0 1-1.5 0v-.604c0-1.118.922-1.822 1.592-2.146q.205-.099.373-.246c.602-.527.602-1.334 0-1.861M9.25 14.229a.75.75 0 0 1 .75-.75h.006a.75.75 0 0 1 .75.75v.006a.75.75 0 0 1-.75.75H10a.75.75 0 0 1-.75-.75z"
      clipRule="evenodd"
    />
  </Icon>
)
