/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const LockOutline = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path
      fillRule="evenodd"
      d="M5.538 5.558a4.558 4.558 0 0 1 9.116 0v2.425a2.654 2.654 0 0 1 2.538 2.652v5.711A2.654 2.654 0 0 1 14.54 19H5.654A2.654 2.654 0 0 1 3 16.346v-5.711a2.654 2.654 0 0 1 2.538-2.652zm.116 3.923c-.637 0-1.154.516-1.154 1.154v5.711c0 .637.517 1.154 1.154 1.154h8.885c.637 0 1.153-.517 1.153-1.154v-5.711c0-.638-.516-1.154-1.153-1.154zm7.5-1.5H7.038V5.558a3.058 3.058 0 0 1 6.116 0z"
      clipRule="evenodd"
    />
  </Icon>
)
