/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const Members = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <path d="M10 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6M6 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-4.51 7.326a.78.78 0 0 1-.358-.442 3 3 0 0 1 4.308-3.516 6.48 6.48 0 0 0-1.905 3.959q-.034.335.025.654a5 5 0 0 1-2.07-.655m14.95.654a5 5 0 0 0 2.07-.654.78.78 0 0 0 .357-.442 3 3 0 0 0-4.308-3.517 6.48 6.48 0 0 1 1.907 3.96 2.3 2.3 0 0 1-.026.654M18 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0M5.304 16.19a.84.84 0 0 1-.277-.71 5 5 0 0 1 9.947 0 .84.84 0 0 1-.277.71A6.98 6.98 0 0 1 10 18a6.97 6.97 0 0 1-4.696-1.81" />
  </Icon>
)
