/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const Privacy = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <path
      fill-rule="evenodd"
      d="M9.246 1.183a.67.67 0 0 1 .92 0 10 10 0 0 0 7.035 2.75.67.67 0 0 1 .644.46c.369 1.121.568 2.318.568 3.56 0 5.305-3.63 9.762-8.54 11.026a.7.7 0 0 1-.334 0C4.63 17.715 1 13.259 1 7.952c0-1.241.199-2.438.567-3.558a.67.67 0 0 1 .645-.46h.127c2.676 0 5.106-1.045 6.907-2.75m.46 10.966c-1.806 0-3.416.85-4.464 2.177.446 1.44 2.719 2.78 4.465 2.78s3.571-1.34 4.464-2.78a5.68 5.68 0 0 0-4.464-2.177m0-1.74c1.58 0 2.86-1.3 2.86-2.903s-1.28-2.902-2.86-2.902-2.86 1.3-2.86 2.902 1.281 2.902 2.86 2.902"
      clip-rule="evenodd"
    />
  </IconV2>
)
