/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */

import type { ReactNode } from 'react'
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const Upload = ({
  children,
  ...props
}: { children: ReactNode } & IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <svg xmlns="http://www.w3.org/2000/svg">
      <path d="M9.25 13.25a.75.75 0 0 0 1.5 0V4.636l2.955 3.129a.75.75 0 0 0 1.09-1.03l-4.25-4.5a.75.75 0 0 0-1.09 0l-4.25 4.5a.75.75 0 1 0 1.09 1.03L9.25 4.636z" />
      <path d="M3.5 12.75a.75.75 0 0 0-1.5 0v2.5A2.75 2.75 0 0 0 4.75 18h10.5A2.75 2.75 0 0 0 18 15.25v-2.5a.75.75 0 0 0-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25z" />
    </svg>
  </IconV2>
)
