/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.mjs.
 * PLEASE DO NOT EDIT HERE
 */
import { IconV2 } from '../IconV2'
import type { IconProps } from '../IconV2'

export const WestShort = ({ ...props }: IconProps) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <IconV2 {...props}>
    <path
      d="M9.322 3.22a.75.75 0 0 1 0 1.06L4.561 9.042H17.25a.75.75 0 0 1 0 1.5H4.56l4.762 4.761a.75.75 0 0 1-1.06 1.06l-6.042-6.04a.75.75 0 0 1 0-1.06L8.26 3.22a.75.75 0 0 1 1.061 0"
      clip-rule="evenodd"
    />
  </IconV2>
)
