/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://ultraviolet.s3.fr-par.scw.cloud/illustrations'

const distributedDataLabContent = `${BASE_URL}/products/distributedDataLab/distributed-data-lab-content.webp`
const distributedDataLabKeyvisual = `${BASE_URL}/products/distributedDataLab/distributed-data-lab-keyvisual.webp`
const distributedDataLabOriginal = `${BASE_URL}/products/distributedDataLab/distributed-data-lab-original.webp`
const distributedDataLabWire = `${BASE_URL}/products/distributedDataLab/distributed-data-lab-wire.svg`

export {
  distributedDataLabContent,
  distributedDataLabKeyvisual,
  distributedDataLabOriginal,
  distributedDataLabWire,
}
