'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const BaremetalCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="BaremetalCategoryIcon">
    <g className="Baremetal">
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M11.167 11.167H8.834v3.5H5.167a1 1 0 0 0-1 1V16a1 1 0 0 0 1 1h9.666a1 1 0 0 0 1-1v-.333a1 1 0 0 0-1-1h-3.666z"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <g fill="#4F0599">
        <path
          className="fill"
          clipRule="evenodd"
          d="M13 5H7a2 2 0 0 0-2 2v1.333a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2M7 3a4 4 0 0 0-4 4v1.333a4 4 0 0 0 4 4h6a4 4 0 0 0 4-4V7a4 4 0 0 0-4-4z"
          fillRule="evenodd"
        />
        <path
          className="fill"
          d="M8.833 7.5a1 1 0 0 1 1-1H12.5a1 1 0 0 1 1 1v.333a1 1 0 0 1-1 1H9.833a1 1 0 0 1-1-1z"
        />
      </g>
    </g>
  </Icon>
)
