'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const ContainersCategoryIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ContainersCategoryIcon">
    <g className="Containers">
      <path
        className="fill"
        clipRule="evenodd"
        d="M3 5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zm12 0H5v10h10z"
        fill="#4F0599"
        fillRule="evenodd"
      />
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M8 7a1 1 0 0 1 1 1v4a1 1 0 0 1-2 0V8a1 1 0 0 1 1-1m4 0a1 1 0 0 1 1 1v4a1 1 0 0 1-2 0V8a1 1 0 0 1 1-1"
        fill="#A365F6"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
