'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const DatacenterCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DatacenterCategoryIcon">
    <g className="Datacenter">
      <g className="Datacenters-icon">
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M15 9V7H5v2zm0 4v-2H5v2z"
          fill="#A365F6"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="M5 3h10a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1m9 12V5H6v10z"
          fill="#4F0599"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
