'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const DedicatedServerCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DedicatedServerCategoryIcon">
    <g className="Dedicated-Server">
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M10.25 14a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5H11a.75.75 0 0 1-.75-.75m0-7.7a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5H11a.75.75 0 0 1-.75-.75"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="M3 13.5a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v1a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1zM3 5.8a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v1a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1z"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
