'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const DevToolsCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DevTools">
    <g className="DevTools">
      <g fill="#A365F6">
        <path
          className="fillStrong"
          d="M16.828 13.101a2.25 2.25 0 1 1-2.177-3.363c.339-.035.512.338.342.633l-.554.96a.5.5 0 0 0 .183.684l.353.204a.5.5 0 0 0 .683-.183l.555-.96c.17-.295.58-.332.72-.021a2.25 2.25 0 0 1-.105 2.046"
        />
        <path
          className="fillStrong"
          d="M13.549 12.781a.5.5 0 0 1 .683-.183l.433.25a.5.5 0 0 1 .183.683l-1.5 2.598a.5.5 0 0 1-.683.183l-.433-.25a.5.5 0 0 1-.183-.683z"
        />
      </g>
      <g fill="#4F0599">
        <path
          className="fill"
          clipRule="evenodd"
          d="M2.5 6a3 3 0 0 1 3-3h9a3 3 0 0 1 3 3v2.5a1 1 0 1 1-2 0V6a1 1 0 0 0-1-1h-9a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1H10a1 1 0 1 1 0 2H5.5a3 3 0 0 1-3-3z"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="M2.75 7a.75.75 0 0 1 .75-.75H16a.75.75 0 0 1 0 1.5H3.5A.75.75 0 0 1 2.75 7m3.68 2.012a.75.75 0 0 1 1.058-.081l2.435 2.087a.75.75 0 0 1-.025 1.159L7.463 14.09a.75.75 0 0 1-.926-1.18l1.716-1.348-1.741-1.492a.75.75 0 0 1-.081-1.058Z"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
