'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const DocumentationCategoryIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DocumentationCategoryIcon">
    <g className="Documentation">
      <g className="Icon">
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M10 7.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-1 1a1 1 0 0 0 0 2v3a1 1 0 1 0 2 0v-5z"
          fill="#A365F6"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="M10 4.5a5.5 5.5 0 0 0-4.582 8.544 1 1 0 0 1 .146.764L5.29 15.08l1.27-.363a1 1 0 0 1 .763.088A5.5 5.5 0 1 0 10 4.5M2.5 10a7.5 7.5 0 1 1 4.228 6.75l-2.489.712a1 1 0 0 1-1.253-1.171l.538-2.507A7.47 7.47 0 0 1 2.5 10"
          fill="#4F0599"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
