'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const IntegrationServicesCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="IntegrationServices">
    <g className="Application-Integration">
      <g className="Icon">
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M6.707 18.707a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 0-1.414l2-2a1 1 0 0 1 1.414 1.414L6.414 15H16a1 1 0 1 1 0 2H6.414l.293.293a1 1 0 0 1 0 1.414m6.586-17.414a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-2 2a1 1 0 1 1-1.414-1.414L13.586 5H4a1 1 0 1 1 0-2h9.586l-.293-.293a1 1 0 0 1 0-1.414"
          fill="#521094"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="M4 7.25a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8A.75.75 0 0 1 4 7.25m3 0a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8A.75.75 0 0 1 7 7.25m4 0a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8a.75.75 0 0 1 .75-.75m5 0a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8a.75.75 0 0 1 .75-.75"
          fill="#A060F6"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
