'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const ManagementAndGovernanceCategoryIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ManagementAndGovernanceCategoryIcon">
    <g className="Tools-Services">
      <g className="tool_icon">
        <path
          className="fill"
          clipRule="evenodd"
          d="M9 2h2l.62 2.32 1.25.51 2.05-1.22 1.47 1.56-1.23 2 .52 1.25L18 9v2l-2.36.62-.52 1.25 1.23 2.05-1.47 1.47-2.05-1.23-1.25.52L11 18H9l-.62-2.32-1.25-.52-2.05 1.23-1.47-1.47 1.23-2.09-.52-1.25L2 11V9l2.32-.62.51-1.25-1.22-2.05 1.52-1.46 2 1.22 1.25-.52zm1.85 4.16L10 5.81l-.89.31-1.25.52L7 7l-.32.9-.52 1.25-.35.85.35.85.48 1.29L7 13l.9.31 1.25.53.85.35.89-.31 1.25-.53L13 13l.35-.94.53-1.25.35-.85-.35-.85-.53-1.25L13 7l-.9-.32z"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          d="m10 8 .39.16.62.26.4.17.17.39.26.63.16.39-.16.39-.26.62-.17.4-.4.17-.62.26L10 12l-.39-.16-.63-.26-.39-.17-.17-.4-.26-.62L8 10l.16-.39.26-.63.17-.39.39-.17.63-.26z"
          fill="#A365F6"
        />
      </g>
    </g>
  </Icon>
)
