'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const MonitoringCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Monitoring">
    <g className="Observability">
      <g className="icon">
        <path
          className="fill"
          d="M3 7.25a1.25 1.25 0 1 1 2.5 0v7.5a1.25 1.25 0 1 1-2.5 0zm11.5-2a1.25 1.25 0 1 1 2.5 0v9.5a1.25 1.25 0 1 1-2.5 0z"
          fill="#4F0599"
        />
        <path
          className="fillStrong"
          d="M8.75 9.25a1.25 1.25 0 1 1 2.5 0v5.5a1.25 1.25 0 1 1-2.5 0z"
          fill="#A365F6"
        />
      </g>
    </g>
  </Icon>
)
