'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const MonitoringCategoryIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <g>
      <g>
        <path
          fill="#521094"
          className="fill"
          d="M3 7.25a1.25 1.25 0 1 1 2.5 0v7.5a1.25 1.25 0 1 1-2.5 0zm11.5-2a1.25 1.25 0 1 1 2.5 0v9.5a1.25 1.25 0 1 1-2.5 0z"
        />
        <path fill="#a060f6" className="fillStrong" d="M8.75 9.25a1.25 1.25 0 1 1 2.5 0v5.5a1.25 1.25 0 1 1-2.5 0z" />
      </g>
    </g>
  </Icon>
)

MonitoringCategoryIcon.displayName = 'MonitoringCategoryIcon'
