'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const OrganizationDashboardCategoryIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <g>
      <g>
        <path
          fill="#521094"
          className="fill"
          d="M5 4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1zm7 4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1z"
          clipRule="evenodd"
          fillRule="evenodd"
        />
        <path
          fill="#a060f6"
          className="fillStrong"
          d="M12 4a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1zm-7 9a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1z"
          clipRule="evenodd"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)

OrganizationDashboardCategoryIcon.displayName = 'OrganizationDashboardCategoryIcon'
