'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const PinCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="PinCategoryIcon">
    <g className="Pin">
      <path
        className="fillStrong"
        d="M6.343 12.284a.97.97 0 1 1 1.373 1.373l-2.06 2.059a.97.97 0 1 1-1.372-1.373l2.06-2.059Z"
        fill="#A060F6"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="M8.771 8.66a1.04 1.04 0 0 1-.843.299l-.54-.057a4.7 4.7 0 0 0-1.624.116l5.219 5.218c.134-.54.172-1.091.116-1.625l-.058-.54a1.04 1.04 0 0 1 .299-.843l3.314-3.314-2.568-2.568zm2.232-5.167c.637-.636 1.646-.66 2.254-.052l3.302 3.302c.608.608.584 1.617-.053 2.254l-3.293 3.293a7 7 0 0 1-.81 4.032c-.442.827-1.527.883-2.163.248L3.43 9.76c-.635-.635-.579-1.72.248-2.163a7 7 0 0 1 4.03-.81z"
        fill="#521094"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
