'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const PrivacyCategoryIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="PrivacyCategoryIcon">
    <path
      className="fillStrong"
      d="M12 5.41309C11.9999 3.90976 11.0869 3 10 3C8.9131 3 8.00013 3.90976 8 5.41309V6H6V5.41309C6.00014 3.10268 7.53283 1 10 1C12.4672 1 13.9999 3.10268 14 5.41309V6H12V5.41309Z"
      fill="#A060F6"
    />
    <path
      className="fill"
      d="M14.4004 6C15.9524 6.00023 17 7.38598 17 8.81836V15.1816C17 16.614 15.9524 17.9998 14.4004 18H5.59961C4.0476 17.9998 3 16.614 3 15.1816V8.81836C3 7.38598 4.0476 6.00023 5.59961 6H14.4004ZM5.59961 8C5.38445 8.00029 5 8.24289 5 8.81836V15.1816C5 15.7571 5.38445 15.9997 5.59961 16H14.4004C14.6156 15.9997 15 15.7571 15 15.1816V8.81836C15 8.2429 14.6156 8.00029 14.4004 8H5.59961ZM10 9.5C11.4707 9.50014 12.8008 10.3049 13.5459 11.5996C13.6885 11.8474 13.6885 12.1526 13.5459 12.4004C12.8008 13.6952 11.4707 14.4999 10 14.5C8.5292 14.4998 7.19822 13.6953 6.45312 12.4004C6.31072 12.1527 6.31071 11.8473 6.45312 11.5996C7.19822 10.3047 8.5292 9.50017 10 9.5ZM10 10.75C9.30975 10.7502 8.75 11.3097 8.75 12C8.75003 12.6903 9.30977 13.2498 10 13.25C10.6903 13.2499 11.25 12.6903 11.25 12C11.25 11.3096 10.6903 10.7501 10 10.75Z"
      fill="#521094"
    />
  </Icon>
)
