'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ProfileCategoryIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ProfileCategoryIcon">
    <path
      fill="#a060f6"
      className="fillStrong"
      fillRule="evenodd"
      d="M10 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4m-3 2.91A1.91 1.91 0 0 1 8.91 11h2.18A1.91 1.91 0 0 1 13 12.91V16l-3 1-3-1z"
      clipRule="evenodd"
    />
    <path
      fill="#521094"
      className="fill"
      fillRule="evenodd"
      d="M10 2a8 8 0 1 0 .001 16.001A8 8 0 0 0 10 2m0 2.011A5.995 5.995 0 0 1 15.989 10 5.996 5.996 0 0 1 10 15.989 5.996 5.996 0 0 1 4.011 10 5.995 5.995 0 0 1 10 4.011"
      clipRule="evenodd"
    />
  </Icon>
)

ProfileCategoryIcon.displayName = 'ProfileCategoryIcon'
