'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ServerlessComputeCategoryIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ServerlessCompute">
    <g className="Serverless">
      <path
        className="fillStrong"
        d="M11.59 3.72a.526.526 0 0 0-.96-.422l-4.056 8.02c-.154.288-.064.536.228.536l2.271-.015c.38 0 .38.194.248.684l-.94 3.858c-.13.64.69.863 1.001.287l4.071-8.06a.301.301 0 0 0-.252-.462l-2.36.01a.236.236 0 0 1-.243-.309z"
        fill="#A365F6"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="M17.5 14.5A1.5 1.5 0 0 1 16 16h-2.616a.3.3 0 0 1-.29-.373l.311-1.248A.5.5 0 0 1 13.89 14h1.61V6h-1.616a.3.3 0 0 1-.29-.373l.311-1.248A.5.5 0 0 1 14.39 4H16a1.5 1.5 0 0 1 1.5 1.5zm-15-9A1.5 1.5 0 0 1 4 4h3.116a.3.3 0 0 1 .29.373l-.31 1.247A.5.5 0 0 1 6.61 6H4.5v8h1.616a.3.3 0 0 1 .29.373l-.311 1.248A.5.5 0 0 1 5.61 16H4a1.5 1.5 0 0 1-1.5-1.5z"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
