'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const UseCasesCategoryIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="UseCasesCategoryIcon">
    <path
      fill="#a060f6"
      d="M14 14C15.105 14 16 14.895 16 16 16 17.105 15.105 18 14 18 12.895 18 12 17.105 12 16 12 14.895 12.895 14 14 14ZM14 8C15.105 8 16 8.895 16 10 16 11.105 15.105 12 14 12 12.895 12 12 11.105 12 10 12 8.895 12.895 8 14 8ZM14 2C15.105 2 16 2.895 16 4 16 5.105 15.105 6 14 6 12.895 6 12 5.105 12 4 12 2.895 12.895 2 14 2Z"
      className="fillStrong"
    />
    <path
      fill="#521094"
      d="M11.1738 3C11.0631 3.31306 11 3.649 11 4C11 4.351 11.0631 4.68694 11.1738 5H8.5C7.94772 5 7.5 5.44772 7.5 6V9H11.1738C11.0631 9.31306 11 9.649 11 10C11 10.351 11.0631 10.6869 11.1738 11H7.5V14C7.5 14.5523 7.94772 15 8.5 15H11.1738C11.0631 15.3131 11 15.649 11 16C11 16.351 11.0631 16.6869 11.1738 17H8.5C6.84315 17 5.5 15.6569 5.5 14V11H3.5C2.94772 11 2.5 10.5523 2.5 10C2.5 9.44772 2.94772 9 3.5 9H5.5V6C5.5 4.34315 6.84315 3 8.5 3H11.1738Z"
      className="fill"
    />
  </Icon>
)

UseCasesCategoryIcon.displayName = 'UseCasesCategoryIcon'
