/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CloudHosting = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="Cloud-Hosting">
      <g className="Cloud-Hosting-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            fill="#F1EEFC"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            className="fillWeak"
          />
        </g>
        <g fillRule="evenodd" className="Icon" clipRule="evenodd">
          <path
            fill="#A060F6"
            d="M52.996 17.65A5.87 5.87 0 0 0 47.13 12H16.87l-.22.004A5.87 5.87 0 0 0 11 17.87v23.26l.005.242a5.87 5.87 0 0 0 4.32 5.423 1 1 0 1 0 .526-1.93A3.87 3.87 0 0 1 13 41.13V22h38v19.13l-.005.198a3.87 3.87 0 0 1-3.108 3.598 1 1 0 1 0 .388 1.962A5.87 5.87 0 0 0 53 41.13V17.87zM51 20v-2.13a3.87 3.87 0 0 0-3.67-3.865l-.2-.005H16.87a3.87 3.87 0 0 0-3.865 3.67l-.005.2V20z"
            className="fillStrong"
          />
          <path
            fill="#521094"
            d="M46.498 16H41l-.117.007A1 1 0 0 0 41 18h5.498l.116-.007A1 1 0 0 0 46.498 16M32.229 30.004a9.51 9.51 0 0 0-8.822 6.738l-.086.303-.073-.008A7.5 7.5 0 0 0 15 44.5l.004.25a7.5 7.5 0 0 0 6.673 7.205l.047.004.056.017A1 1 0 0 0 22 52h19l.114-.006.014-.003A7.5 7.5 0 0 0 49 44.5l-.004-.244a7.5 7.5 0 0 0-7.253-7.253l-.076-.002-.057-.204A9.505 9.505 0 0 0 32.5 30zM32.5 32a7.5 7.5 0 0 1 7.388 6.202 1 1 0 0 0 1.082.823 5.5 5.5 0 1 1 .106 10.959l-.112-.002-.11.01-.045.008H22.197l-.064-.01-.057-.006a5.5 5.5 0 1 1 1.779-10.816 1 1 0 0 0 1.233-.818A7.5 7.5 0 0 1 32.5 32"
            className="fill"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath id="a" className="a">
        <path fill="#fff" d="M0 0h64v64H0z" />
      </clipPath>
    </defs>
  </Icon>
)
