/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const DocumentationProductIcon = ({
  ...props
}: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="Documentation">
      <g className=".Square">
        <path
          fill="#EEF"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          className="fillWeak"
        />
      </g>
      <g className="Documentation">
        <g className="icon">
          <path
            fill="#4F0599"
            d="M12 20a6 6 0 0 1 6-6h28.462a6 6 0 0 1 6 6v21.73a6 6 0 0 1-6 6H43.5a1 1 0 1 1 0-2h2.962a4 4 0 0 0 4-4V24H14v17.73a4 4 0 0 0 4 4h2.5a1 1 0 1 1 0 2H18a6 6 0 0 1-6-6zm38.462 0v2H14v-2a4 4 0 0 1 4-4h28.462a4 4 0 0 1 4 4m-9.577-2.154a1 1 0 1 0 0 2h5.288a1 1 0 1 0 0-2z"
            className="fill"
            clipRule="evenodd"
            fillRule="evenodd"
          />
          <path
            fill="#A365F6"
            d="M22.836 46.736A11.446 11.446 0 0 1 21 40.5C21 34.149 26.149 29 32.5 29S44 34.149 44 40.5 38.851 52 32.5 52c-2 0-3.881-.51-5.52-1.409l-5.578 1.495zm3.922 5.985A13.455 13.455 0 0 0 32.5 54C39.956 54 46 47.956 46 40.5S39.956 27 32.5 27 19 33.044 19 40.5c0 2.368.611 4.598 1.685 6.536l-1.214 4.532a2 2 0 0 0 2.45 2.45z"
            className="fillStrong"
            clipRule="evenodd"
            fillRule="evenodd"
          />
          <g fill="#4F0599" className="fill">
            <path
              d="M29.25 39.378c0-.69.56-1.25 1.25-1.25h3.34v8.563a1.25 1.25 0 1 1-2.5 0v-6.063h-.84c-.69 0-1.25-.56-1.25-1.25"
              className="fill"
              clipRule="evenodd"
              fillRule="evenodd"
            />
            <path
              d="M34.166 34.736a1.736 1.736 0 1 1-3.472 0 1.736 1.736 0 0 1 3.472 0"
              className="fill"
            />
          </g>
        </g>
      </g>
    </g>
  </Icon>
)
