/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /scripts/generateIconFiles.ts.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const User = ({ ...props }: Omit<IconProps, 'children'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props}>
    <g className="User">
      <g className=".Square">
        <path
          fill="#EEF"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          className="fillWeak"
        />
      </g>
      <g className="User">
        <path
          fill="#4F0599"
          d="M32 33.7c-5.819 0-10.556 4.776-10.556 10.692v1.315l.101.067c.328.213.875.518 1.698.83 1.648.626 4.414 1.285 8.757 1.285s7.11-.66 8.756-1.284c.824-.313 1.371-.618 1.699-.83l.1-.068v-1.315C42.555 38.476 37.82 33.7 32 33.7m11.555 12.49.712.704a1 1 0 0 0 .288-.703v-1.799c0-6.999-5.61-12.692-12.555-12.692-6.945 0-12.556 5.693-12.556 12.692v1.799a1 1 0 0 0 .29.703l.71-.703-.71.704.001.001.003.003.006.006.016.015a2.581 2.581 0 0 0 .183.161c.119.096.287.223.512.37.45.292 1.125.662 2.079 1.024 1.909.724 4.92 1.414 9.466 1.414 4.545 0 7.557-.69 9.466-1.414.954-.362 1.629-.732 2.08-1.024.224-.147.392-.273.51-.37a3.46 3.46 0 0 0 .184-.161l.015-.015.007-.006.002-.003.002-.001-.71-.704Z"
          className="fill"
          clipRule="evenodd"
          fillRule="evenodd"
        />
        <path
          fill="#A365F6"
          d="M32 15.461c-3.364 0-6.112 2.763-6.112 6.196 0 3.432 2.747 6.195 6.111 6.195 3.365 0 6.112-2.763 6.112-6.195 0-3.433-2.747-6.196-6.111-6.196m-8.112 6.196c0-4.515 3.62-8.196 8.111-8.196 4.491 0 8.112 3.68 8.112 8.196 0 4.515-3.62 8.195-8.111 8.195-4.491 0-8.112-3.68-8.112-8.195"
          className="fillStrong"
          clipRule="evenodd"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
