/**
 * This file is automatically generated from /utils/scripts/illustrations/update-illustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const environmentalFootprintCalculatorContent = `${BASE_URL}/products/environmentalFootprintCalculator/environmentalFootprintCalculatorContent.webp`
const environmentalFootprintCalculatorKeyvisual = `${BASE_URL}/products/environmentalFootprintCalculator/environmentalFootprintCalculatorKeyvisual.webp`
const environmentalFootprintCalculatorOriginal = `${BASE_URL}/products/environmentalFootprintCalculator/environmentalFootprintCalculatorOriginal.webp`
const environmentalFootprintCalculatorWire = `${BASE_URL}/products/environmentalFootprintCalculator/environmentalFootprintCalculatorWire.svg`

export {
  environmentalFootprintCalculatorContent,
  environmentalFootprintCalculatorKeyvisual,
  environmentalFootprintCalculatorOriginal,
  environmentalFootprintCalculatorWire,
}
