/**
 * This file is automatically generated from /utils/scripts/uploadIllustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const loadBalancersContent = `${BASE_URL}/products/loadBalancers/load-balancers-content.webp`
const loadBalancersKeyvisual = `${BASE_URL}/products/loadBalancers/load-balancers-keyvisual.webp`
const loadBalancersOriginal = `${BASE_URL}/products/loadBalancers/load-balancers-original.webp`
const loadBalancersWire = `${BASE_URL}/products/loadBalancers/load-balancers-wire.svg`

export {
  loadBalancersContent,
  loadBalancersKeyvisual,
  loadBalancersOriginal,
  loadBalancersWire,
}
