/**
 * This file is automatically generated from /scripts/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://ultraviolet.s3.fr-par.scw.cloud/illustrations'

const generativeApiContent = `${BASE_URL}/products/generativeApi/generative-api-content.webp`
const generativeApiKeyvisual = `${BASE_URL}/products/generativeApi/generative-api-keyvisual.webp`
const generativeApiOriginal = `${BASE_URL}/products/generativeApi/generative-api-original.webp`
const generativeApiWire = `${BASE_URL}/products/generativeApi/generative-api-wire.svg`

export {
  generativeApiContent,
  generativeApiKeyvisual,
  generativeApiOriginal,
  generativeApiWire,
}
