/**
 * This file is automatically generated from /utils/scripts/uploadIllustrations.tsx
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://assets.scaleway.com/illustrations'

const nabuContent = `${BASE_URL}/products/nabu/nabu-content.webp`
const nabuKeyvisual = `${BASE_URL}/products/nabu/nabu-keyvisual.webp`
const nabuOriginal = `${BASE_URL}/products/nabu/nabu-original.webp`
const nabuWire = `${BASE_URL}/products/nabu/nabu-wire.svg`

export { nabuContent, nabuKeyvisual, nabuOriginal, nabuWire }
