name: Generate changeset for Renovate

on:
  pull_request_target:
    paths:
      - '.github/workflows/changesets-renovate.yml'
      - '**/pnpm-lock.yaml'
      - '**/package.json'

jobs:
  generate-changeset:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: github.actor == 'renovate[bot]' && github.repository == 'scaleway/ultraviolet' && github.event.pull_request.head.repo.full_name == 'scaleway/ultraviolet'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 10
          ref: ${{ github.head_ref }}
      - name: Git Identity
        run: |
          git config --global user.name 'Scaleway Bot'
          git config --global user.email 'github@scaleway.com'
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Run changesets-renovate
        run: pnpm dlx @scaleway/changesets-renovate
        env:
          EXCLUDE_DEVDEPS: true
