name: Release

on:
  push:
    branches:
      - main
      - beta

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Pull Secrets
        uses: scaleway/action-scw-secret@3658f2234f185b17405d19254557b34484bf4f99 # v0.0.11
        with:
          secret-names: |
            NPM_TOKEN, /npm/token_ultraviolet
          access-key: ${{ vars.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ vars.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ vars.SCW_DEFAULT_ORGANIZATION_ID }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Git Identity
        run: |
          git config --global user.name 'Scaleway Bot'
          git config --global user.email 'github@scaleway.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          commit: 'chore: release'
          title: 'chore: release'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          PNPM_CONFIG_PROVENANCE: true
