name: Release

on:
  push:
    branches:
      - main
      - beta

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Pull Secrets
        uses: scaleway/action-scw-secret@3658f2234f185b17405d19254557b34484bf4f99 # v0.0.11
        with:
          secret-names: |
            NPM_TOKEN, /npm/token_ultraviolet
          access-key: ${{ vars.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ vars.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ vars.SCW_DEFAULT_ORGANIZATION_ID }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Git Identity
        run: |
          git config --global user.name 'Scaleway Bot'
          git config --global user.email 'github@scaleway.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@c47fa68bd43bb8ae0bae7e558622593deebf5955 # v2.0.0-next.3
        with:
          commit-message: 'chore: release'
          pr-title: 'chore: release'
          publish-script: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          PNPM_CONFIG_PROVENANCE: true
