name: Sync Main to Beta

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-main-to-beta:
    name: Sync Main to Beta
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if Beta Branch Exists
        id: check-beta
        run: |
          if git ls-remote --heads origin beta | grep -q beta; then
            echo "Beta branch exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Beta branch does not exist. Exiting."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Exit if Beta Branch Does Not Exist
        if: env.exists == 'false'
        run: exit 0

      - name: Set Git Identity
        run: |
          git config --global user.name $FRONT_USER_NAME
          git config --global user.email $FRONT_USER_EMAIL

      - name: Fetch All Branches
        run: git fetch --all

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: beta
          head: main
          title: "Sync Main to Beta"
          body: |
            This pull request keeps the `beta` branch in sync with the latest changes from the `main` branch.
          branch: sync-main-to-beta # Temporary branch for the PR
          update-existing-pr: true # Update the existing PR if one already exists
