name: Design tokens

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 1-5'

jobs:
  synchronise:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        env:
          LANG: en_US.UTF-8
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - name: Generate json files
        run: |
          pnpm run tokens:update

      - name: Compare & Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: main
          author: Scaleway Design <github@scaleway.com>
          commit-message: 'fix(theme): synchronise design tokens'
          branch: fix/design-tokens-synchronise
          delete-branch: true
          title: 'fix(theme): synchronise design tokens'
          body: |
            Design system tokens update. This MR is created automatically when a change is detected in design tokens.
          team-reviewers: console
          labels: design system
