'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const AdditionalDiskProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="AdditionalDiskProductIcon">
    <g className="Additional-Disk">
      <g className="Additional-Disk-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="Icon">
          <g className="fill" fill="#521094">
            <path d="M21.904 17v2h-2.125a3.78 3.78 0 0 0-3.774 3.585l-.005.194v26.442a3.78 3.78 0 0 0 3.585 3.774l.194.005h16.442a3.78 3.78 0 0 0 3.774-3.585l.005-.194v-2.05h2v2.05a5.78 5.78 0 0 1-5.557 5.775L36.22 55H19.779a5.78 5.78 0 0 1-5.775-5.557L14 49.22V22.779a5.78 5.78 0 0 1 5.558-5.775l.221-.004z" />
            <path d="M44 10a5 5 0 0 1 4.995 4.783L49 15v5.886h-2V15a3 3 0 0 0-2.824-2.995L44 12H26a3 3 0 0 0-2.995 2.824L23 15v28a3 3 0 0 0 2.824 2.995L26 46h18a3 3 0 0 0 2.995-2.824L47 43v-5.64h2V43a5 5 0 0 1-4.783 4.995L44 48H26a5 5 0 0 1-4.995-4.783L21 43V15a5 5 0 0 1 4.783-4.995L26 10z" />
            <path
              clipRule="evenodd"
              d="M43.5 13.61V10h-17v3.61A2.39 2.39 0 0 0 28.89 16h12.22a2.39 2.39 0 0 0 2.39-2.39M28.5 12h13v1.61l-.008.079a.39.39 0 0 1-.382.311H28.89l-.079-.008a.39.39 0 0 1-.311-.382z"
              fillRule="evenodd"
            />
            <path d="M38.532 11.001V15h-2v-3.999zm-5 0V15h-2v-3.999z" />
          </g>
          <path
            className="fillStrong"
            clipRule="evenodd"
            d="M44 19c-5.523 0-10 4.477-10 10s4.477 10 10 10 10-4.477 10-10-4.477-10-10-10m0 2a8 8 0 1 1 0 16 8 8 0 0 1 0-16m1.026 2.883a1 1 0 0 0-1.994.117v4h-4l-.116.007A1 1 0 0 0 39.033 30h3.999v4l.007.117A1 1 0 0 0 45.032 34v-4h4l.117-.007A1 1 0 0 0 49.032 28h-4v-4z"
            fill="#A060F6"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
