'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const ApplicationLibraryProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ApplicationLibraryProductIcon">
    <path
      className="fillWeak"
      d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
      fill="#EEF"
    />
    <path
      className="fill"
      clipRule="evenodd"
      d="M15 29h34a2 2 0 0 1 2 2v23a2 2 0 0 1-2 2H15a2 2 0 0 1-2-2V31a2 2 0 0 1 2-2m0 3v21a1 1 0 0 0 1 1h32a1 1 0 0 0 1-1V32a1 1 0 0 0-1-1H16a1 1 0 0 0-1 1"
      fill="#4F0599"
      fillRule="evenodd"
    />
    <path
      className="fillStrong"
      clipRule="evenodd"
      d="M31.866 9.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11m-7.5 5.5a7.5 7.5 0 1 1 11.26 6.491l5.18 14.392-1.881.678-5.15-14.306q-.445.117-.91.179V45h-2V22.434a8 8 0 0 1-.908-.18L24.94 36.188l-1.882-.677 5.047-14.019A7.5 7.5 0 0 1 24.366 15"
      fill="#A365F6"
      fillRule="evenodd"
    />
    <path
      className="fill"
      clipRule="evenodd"
      d="M19 39a4 4 0 1 0 8 0 4 4 0 0 0-8 0m22 4a4 4 0 1 1 0-8 4 4 0 0 1 0 8m-9 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8M21.585 40.414a2 2 0 0 1 0-2.828l.149-.135A2 2 0 0 1 23 37a1.999 1.999 0 1 1-1.414 3.414Zm9 8a2 2 0 0 1 0-2.828l.149-.135A2 2 0 0 1 32 45a1.999 1.999 0 1 1-1.414 3.414Zm9-10.828a2 2 0 1 0 .149-.135z"
      fill="#4F0599"
      fillRule="evenodd"
    />
  </Icon>
)
