'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const BackendsProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="BackendsProductIcon">
    <g className="Backends">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M32.2 31.827a1 1 0 0 1 .984.82l.016.18v7.889h13a1 1 0 0 1 1 1v9.23l3.327-3.881a1 1 0 0 1 1.623 1.155l-.105.147-5.143 6a.997.997 0 0 1-1.39.126l-.002-.003-.018-.015a1 1 0 0 1-.108-.108l-5.143-6a1 1 0 0 1 1.39-1.428l.128.126L45.2 51.08v-8.364h-26v8.23l3.327-3.881a1 1 0 0 1 1.623 1.155l-.105.147-5.143 6a1 1 0 0 1-.76.349 1 1 0 0 1-.63-.223l-.002-.003-.018-.015a1 1 0 0 1-.108-.108l-5.143-6a1 1 0 0 1 1.39-1.428l.128.126L17.2 51.08v-9.364a1 1 0 0 1 1-1h13v-7.889a1 1 0 0 1 1-1"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="m20.06 30.581 10.684-18.794a1.941 1.941 0 0 1 3.375 0L44.802 30.58a1.94 1.94 0 0 1-1.688 2.9H21.748a1.94 1.94 0 0 1-1.688-2.9Zm22.951.9L32.43 12.866 21.849 31.482H43.01Z"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
