'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const CbProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="CbProductIcon">
    <g className="CB" clipPath="url(#a)">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="Icon">
        <path
          className="fill"
          clipRule="evenodd"
          d="m36.552 23.634-3.196 1.164a1.7 1.7 0 0 1-2.18-1.016l-.282-.784a1.7 1.7 0 0 1 1.014-2.178l3.196-1.162a1.7 1.7 0 0 1 2.18 1.014l.286.784a1.703 1.703 0 0 1-1.018 2.18zm3.138-6.25a2.104 2.104 0 0 0-2.696-1.256l-23.61 8.592a2.104 2.104 0 0 0-1.256 2.696L16.42 39.21l1.02 2.806a2.11 2.11 0 0 0 2.698 1.258l1.784-.65V29.932c0-1.066.864-1.932 1.93-1.932h19.7z"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M23.854 29.2a.734.734 0 0 0-.734.732v14.27c0 .404.33.732.734.732H46.93a.73.73 0 0 0 .73-.732v-14.27a.73.73 0 0 0-.73-.732zM46.93 47.334H23.854a3.136 3.136 0 0 1-3.134-3.132v-14.27a3.137 3.137 0 0 1 3.134-3.132H46.93a3.135 3.135 0 0 1 3.13 3.132v14.27a3.134 3.134 0 0 1-3.13 3.132"
          fill="#A365F6"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="M23.054 35.89h24.672v-3.734H23.054z"
          fill="#4F0599"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
