'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const CdnProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="CdnProductIcon">
    <g className="CDN">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="fill" fill="#4F0599">
        <path d="M32 20.08a1 1 0 0 1 .993.884l.007.116v7.93a1 1 0 0 1-1.993.116L31 29.009V21.08a1 1 0 0 1 1-1M38.904 31a1 1 0 0 1 .116 1.993l-.116.007H35.18a1 1 0 0 1-.117-1.993L35.18 31z" />
        <path
          clipRule="evenodd"
          d="M32 13c-10.493 0-19 8.507-19 19s8.507 19 19 19 19-8.507 19-19-8.507-19-19-19m-6.102 3.128c-2.834 3.238-4.7 8.683-4.883 14.872h-.98l-.116.007A1 1 0 0 0 20.036 33h.979c.098 3.322.684 6.49 1.692 9.24l.189.5 1.862-.731c-1.031-2.627-1.64-5.73-1.742-9.009h5.858l.117-.007A1 1 0 0 0 28.874 31h-5.858c.278-8.858 4.226-15.798 8.784-15.996L32 15l.202.005c4.163.184 7.91 6.049 8.662 14.07l1.992-.186-.04-.398c-.55-5.17-2.28-9.585-4.715-12.363 6.08 2.338 10.475 8.068 10.87 14.872h-3.804l-.117.007A1 1 0 0 0 45.167 33h3.804c-.395 6.804-4.79 12.534-10.87 14.872 2.481-2.83 4.231-7.361 4.745-12.659l-1.99-.193c-.724 7.46-4.039 13.03-7.856 13.87V35.168l-.007-.117a1 1 0 0 0-1.993.117v13.724c-1.063-.232-2.101-.833-3.073-1.785l-.223-.226-1.25 1.194C19.788 45.775 15 39.447 15 32c0-7.238 4.524-13.42 10.898-15.872"
          fillRule="evenodd"
        />
        <path
          clipRule="evenodd"
          d="M32 28a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 11a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
          fillRule="evenodd"
        />
      </g>
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M32 14a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4M21 32a4 4 0 1 0-8 0 4 4 0 0 0 8 0m-6 0a2 2 0 1 1 4 0 2 2 0 0 1-4 0m31 0a4 4 0 1 0-8 0 4 4 0 0 0 8 0m-6 0a2 2 0 1 1 4 0 2 2 0 0 1-4 0"
        fill="#A365F6"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
