'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const CliProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Cli">
    <g className="CLI">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="CLI">
        <path
          className="fill"
          clipRule="evenodd"
          d="M16.87 15h30.26A5.87 5.87 0 0 1 53 20.87v23.26A5.87 5.87 0 0 1 47.13 50H16.87A5.87 5.87 0 0 1 11 44.13V20.87A5.87 5.87 0 0 1 16.87 15m30.26 2H16.87A3.87 3.87 0 0 0 13 20.87V23h38v-2.13A3.87 3.87 0 0 0 47.13 17M13 44.13V25h38v19.13A3.87 3.87 0 0 1 47.13 48H16.87A3.87 3.87 0 0 1 13 44.13M46.498 19H41l-.117.007A1 1 0 0 0 41 21h5.498l.116-.007A1 1 0 0 0 46.498 19"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="m20.669 29.257-.099-.078a1 1 0 0 0-1.313.152l-.078.099a1 1 0 0 0 .152 1.313l5.007 4.507-5.007 4.507-.088.09a1 1 0 0 0 1.426 1.396l5.833-5.25.088-.09a1 1 0 0 0-.088-1.396zM35 42.25a1 1 0 0 0-1-1h-5.833l-.117.007a1 1 0 0 0 .117 1.993H34l.117-.007A1 1 0 0 0 35 42.25"
          fill="#A365F6"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
