'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const CloudEssentialsProductIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <path
      fill="#f1eefc"
      className="fillWeak"
      d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
    />
    <path
      fill="#f1eefc"
      className="fillWeak"
      fillRule="evenodd"
      d="M48 2H16C8.268 2 2 8.268 2 16v32c0 7.732 6.268 14 14 14h32c7.732 0 14-6.268 14-14V16c0-7.732-6.268-14-14-14M16 0C7.163 0 0 7.163 0 16v32c0 8.837 7.163 16 16 16h32c8.837 0 16-7.163 16-16V16c0-8.837-7.163-16-16-16z"
      clipRule="evenodd"
    />
    <path
      fill="#521094"
      className="fill"
      fillRule="evenodd"
      d="m40.308 25.977.073.043 6.45 3.351-14.664 7.62-14.963-7.62 6.295-3.204a5 5 0 0 1-2.434-1.007l-6.52 3.32a1 1 0 0 0-.545.892v19.234c0 .382.218.731.56.899l17.172 8.393a1 1 0 0 0 .886-.004l16.828-8.393a1 1 0 0 0 .554-.895V29.372a1 1 0 0 0-.54-.888l-8.157-4.239-.094-.042-.043-.015zm-9.136 12.75v16.67L16 47.982V31.003zM48 47.988l-14.828 7.397V38.722L48 31.018z"
      clipRule="evenodd"
    />
    <path
      fill="#a060f6"
      className="fillStrong"
      d="M29.429 4.923a1.596 1.596 0 0 1 1.835-.877A1.62 1.62 0 0 1 32.5 5.644v9.14h6.264c1.719 0 2.706 1.834 2.005 3.294l-7.198 14.998a1.596 1.596 0 0 1-1.835.877 1.62 1.62 0 0 1-1.236-1.598v-9.14h-6.264c-1.719 0-2.706-1.834-2.006-3.294zM32.5 30.686l6.467-13.474a.32.32 0 0 0-.013-.308c-.052-.089-.122-.12-.19-.12h-6.338c-1.102 0-1.926-.92-1.926-1.965V7.312l-6.467 13.475a.32.32 0 0 0 .013.308c.052.089.122.12.19.12h6.338c1.102 0 1.926.92 1.926 1.965z"
    />
  </Icon>
)

CloudEssentialsProductIcon.displayName = 'CloudEssentialsProductIcon'
