'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const ConsoleProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ConsoleProductIcon">
    <g className="Console">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="Icon">
        <path
          className="fill"
          clipRule="evenodd"
          d="M16.87 13h30.26A5.87 5.87 0 0 1 53 18.87v27.26A5.87 5.87 0 0 1 47.13 52H16.87A5.87 5.87 0 0 1 11 46.13V18.87A5.87 5.87 0 0 1 16.87 13M13 46.13V23h38v23.13A3.87 3.87 0 0 1 47.13 50H16.87A3.87 3.87 0 0 1 13 46.13m38-27.26V21H13v-2.13A3.87 3.87 0 0 1 16.87 15h30.26A3.87 3.87 0 0 1 51 18.87M47.498 17H42l-.117.007A1 1 0 0 0 42 19h5.498l.116-.007A1 1 0 0 0 47.498 17"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M24 27a1 1 0 0 1 .993.883L25 28v6a1 1 0 0 1-.883.993L24 35h-6a1 1 0 0 1-.993-.883L17 34v-6a1 1 0 0 1 .883-.993L18 27zm.993 11.883A1 1 0 0 0 24 38h-6l-.117.007A1 1 0 0 0 17 39v6l.007.117A1 1 0 0 0 18 46h6l.117-.007A1 1 0 0 0 25 45v-6zm11 0A1 1 0 0 0 35 38h-6l-.117.007A1 1 0 0 0 28 39v6l.007.117A1 1 0 0 0 29 46h6l.117-.007A1 1 0 0 0 36 45v-6zM46 38a1 1 0 0 1 .993.883L47 39v6a1 1 0 0 1-.883.993L46 46h-6a1 1 0 0 1-.993-.883L39 45v-6a1 1 0 0 1 .883-.993L40 38zm-27 2h4v4h-4zm15 0h-4v4h4zm7 0h4v4h-4zm-5.007-12.117A1 1 0 0 0 35 27h-6l-.117.007A1 1 0 0 0 28 28v6l.007.117A1 1 0 0 0 29 35h6l.117-.007A1 1 0 0 0 36 34v-6zM46 27a1 1 0 0 1 .993.883L47 28v6a1 1 0 0 1-.883.993L46 35h-6a1 1 0 0 1-.993-.883L39 34v-6a1 1 0 0 1 .883-.993L40 27zm-27 2h4v4h-4zm15 0h-4v4h4zm7 0h4v4h-4z"
          fill="#A365F6"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
