'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ContainersProductIcon = ({ ...props }: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ContainersProductIcon">
    <g>
      <g>
        <path
          fill="#f1eefc"
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
        />
      </g>
      <path
        fill="#a060f6"
        className="fillStrong"
        d="M31.263 23.324a1 1 0 0 1 1.553 1.254l-.079.098-11 12a1 1 0 0 1-1.553-1.254l.079-.098z"
      />
      <path
        fill="#521094"
        className="fill"
        d="M31.969 7a1 1 0 0 1 .993.883l.007.117-.001 7.532.06.012a5 5 0 0 1 3.936 4.67l.005.217a5 5 0 0 1-10 0 1 1 0 1 1 2 0 3 3 0 1 0 3-3 1 1 0 0 1-.994-.883l-.006-.117V8a1 1 0 0 1 1-1"
      />
      <path
        fill="#a060f6"
        className="fillStrong"
        d="M31.354 22.237a1 1 0 0 1 1.322.026l.087.091 11 13a1 1 0 0 1-1.44 1.383l-.086-.091-11-13a1 1 0 0 1 .117-1.41Z"
      />
      <path
        fill="#521094"
        className="fill"
        d="M43 35a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H21a2 2 0 0 1-2-2V37a2 2 0 0 1 2-2zm0 2H21v16h22zm-4.007 2.883A1 1 0 0 0 37 40v10l.007.117A1 1 0 0 0 39 50V40zM32 39a1 1 0 0 1 .993.883L33 40v10a1 1 0 0 1-1.993.117L31 50V40a1 1 0 0 1 1-1m-5.007.883A1 1 0 0 0 25 40v10l.007.117A1 1 0 0 0 27 50V40z"
        clipRule="evenodd"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)

ContainersProductIcon.displayName = 'ContainersProductIcon'
