'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const DataWarehouseProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DataWarehouseProductIcon">
    <g className="Datawarehouse" clipPath="url(#a)">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#F1EEFC"
        />
      </g>
      <g className="Icon">
        <path
          className="fill"
          clipRule="evenodd"
          d="m31.5 12.75-.777.006c-7.853.114-14.014 1.969-14.014 4.925v25.1l.005.162C16.98 46.185 23.5 48.25 31.5 48.25c8.175 0 14.792-2.148 14.792-5.468V17.68c0-3.053-6.572-4.931-14.792-4.931Zm.77 9.855h.008c5.175-.075 9.615-.906 12.042-2.31V42.78c0 1.632-5.745 3.497-12.82 3.497-6.97 0-12.683-1.81-12.818-3.456l-.002-.08V20.294c2.548 1.474 7.314 2.316 12.82 2.316h.004q.386 0 .766-.006Zm12.05-4.939c-.026-.442-1.18-1.213-3.329-1.826-2.477-.708-5.866-1.118-9.49-1.118-3.626 0-7.014.41-9.492 1.118-2.172.62-3.328 1.401-3.328 1.84l.005.055c.085.429 1.145 1.13 3.071 1.713l.248.072.004.002c2.478.707 5.866 1.117 9.491 1.117 2.47 0 4.83-.19 6.867-.535a27 27 0 0 0 1.654-.331q.505-.12.97-.252l.046-.012a16 16 0 0 0 .893-.287c1.51-.537 2.332-1.128 2.387-1.502z"
          fill="#521094"
          fillRule="evenodd"
        />
        <g className="fillStrong" fill="#A060F6">
          <path d="M32.752 28.844a.986.986 0 0 0-1.973 0v9.593a.986.986 0 0 0 1.973 0zm-3.947 3.118a.986.986 0 0 0-1.972 0v6.475a.986.986 0 0 0 1.972 0zm7.674 3.118a.986.986 0 0 0-1.972 0v3.357a.986.986 0 0 0 1.972 0z" />
          <path
            clipRule="evenodd"
            d="M24.9 41.272a9.494 9.494 0 0 1 0-13.427 9.494 9.494 0 0 1 13.427 0c3.472 3.472 3.693 8.964.663 12.693l7.972 7.973a.986.986 0 0 1-1.394 1.394l-7.973-7.973c-3.729 3.032-9.222 2.812-12.694-.66Zm1.395-12.032a7.522 7.522 0 1 0 10.638 10.637A7.522 7.522 0 0 0 26.295 29.24"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
