'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const DdxProServersProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DdxProServersProductIcon">
    <g className="DDX-Pro-Servers">
      <g className="Pro-Servers-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="Icon" clipRule="evenodd" fillRule="evenodd">
          <path
            className="fill"
            d="M31.959 12h-.027a1 1 0 0 0-.447.105l-17.768 8.88a1 1 0 0 0-.553.904l.083 9.12.007.115a1 1 0 0 0 1.44.77l17.25-8.622 17.252 8.623a1 1 0 0 0 1.447-.886l.084-9.12a1 1 0 0 0-.553-.904l-17.768-8.88a1 1 0 0 0-.447-.105m-.013 2.111 16.775 8.383-.063 6.895-16.266-8.128-.123-.052a1 1 0 0 0-.771.052L15.232 29.39l-.063-6.896zm.06 26.82h-.013a1 1 0 0 0-.443.104l-8.993 4.44a1 1 0 0 0-.557.904l.042 5.56.007.114a1 1 0 0 0 1.436.775L32 48.623l8.515 4.205a1 1 0 0 0 1.443-.89l.042-5.56a1 1 0 0 0-.557-.904l-8.994-4.44a1 1 0 0 0-.442-.103ZM32 43.042l7.995 3.948-.025 3.338-7.528-3.716-.122-.05a1 1 0 0 0-.763.05l-7.527 3.716-.025-3.339z"
            fill="#521094"
          />
          <path
            className="fillStrong"
            d="M31.99 27.931h.02a1 1 0 0 1 .443.104l12.99 6.412a1 1 0 0 1 .557.906l-.06 6.587a1 1 0 0 1-1.444.888L32 36.658l-12.497 6.17a1 1 0 0 1-1.435-.774l-.007-.114L18 35.353a1 1 0 0 1 .557-.906l12.99-6.413a1 1 0 0 1 .443-.103m12.004 8.031L32 30.041l-11.994 5.921.04 4.367 11.511-5.682a1 1 0 0 1 .763-.051l.123.05 11.51 5.683.04-4.367Z"
            fill="#A060F6"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
