'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const DdxStartServersProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="DdxStartServers">
    <g className="DDX-Start-Servers">
      <g className="Start-Servers-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="Icon" clipRule="evenodd" fillRule="evenodd">
          <path
            className="fill"
            d="M31.928 16h.034a1 1 0 0 1 .447.105L54.73 27.26a1 1 0 0 1 .554.903l-.105 11.458a1 1 0 0 1-1.447.885L43 35.142l.001 11.79a1 1 0 0 1-.883.992l-.117.007H22a1 1 0 0 1-1-1V35.087l-10.84 5.42a1 1 0 0 1-1.44-.772l-.007-.114-.105-11.458a1 1 0 0 1 .553-.903l22.32-11.155a1 1 0 0 1 .447-.105m21.348 12.769-21.331-10.66-21.332 10.66.084 9.232 10.856-5.425a1 1 0 0 1 1.44.779l.007.115v12.461h18V33.525a1 1 0 0 1 1.341-.94l.106.045 10.746 5.371z"
            fill="#521094"
          />
          <path
            className="fillStrong"
            d="M32.186 24.931h-.481l-6.214 3.106-.102.058a1 1 0 0 0-.346 1.283l.058.102a1 1 0 0 0 1.284.346l5.56-2.78 5.561 2.78.107.046a1 1 0 0 0 .787-1.835zm4.814 9a1 1 0 0 1 .117 1.993l-.117.007H27a1 1 0 0 1-.116-1.993L27 33.93zm0 6a1 1 0 0 1 .117 1.993l-.117.007H27a1 1 0 0 1-.116-1.993L27 39.93z"
            fill="#A060F6"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
