'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ElasticMetalIridiumProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ElasticMetalIridiumProductIcon">
    <g className="Elasticmetal-Iridium">
      <g className="Elasticmetal-Iridium-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="Elasticmetal">
          <g className="Serveur">
            <path
              className="fillStrong"
              clipRule="evenodd"
              d="M24 35a3 3 0 1 0-6 0 3 3 0 0 0 6 0m-4 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0"
              fill="#A060F6"
              fillRule="evenodd"
            />
          </g>
          <path
            className="fillStrong"
            d="M17.063 20.717C18.079 15.088 22.47 11 27.578 11c3.6 0 6.829 2.019 8.792 5.19a1 1 0 0 0 1.54.198c.776-.739 1.78-1.174 2.868-1.174 2.135 0 3.664 1.147 4.529 2.79q1.126.03 2.191.256a1 1 0 0 0-.072-.44c-1.04-2.538-3.304-4.606-6.648-4.606a6.06 6.06 0 0 0-3.331 1C35.13 11.055 31.587 9 27.577 9c-5.984 0-10.896 4.553-12.315 10.559C11.09 19.899 8 23.87 8 28.437c0 3.862 2.184 7.25 5.367 8.449a1 1 0 1 0 .705-1.872C11.776 34.15 10 31.59 10 28.437c0-3.948 2.741-6.896 5.835-6.902l.224.005a1 1 0 0 0 1.004-.823"
            fill="#A060F6"
          />
          <g
            className="fill"
            clipRule="evenodd"
            fill="#521094"
            fillRule="evenodd"
          >
            <path d="M39.17 42.622H32v6.549A3 3 0 0 1 33.83 51h13.334a1 1 0 0 1 .117 1.993l-.117.007H33.83a3.001 3.001 0 0 1-5.658 0H14a1 1 0 0 1-.117-1.993L14 51h14.171A3 3 0 0 1 30 49.17v-6.548H17.822a5 5 0 0 1-5-5v-5a5 5 0 0 1 5-5h14.621a13 13 0 0 0-.37 2h-14.25a3 3 0 0 0-2.996 2.824l-.005.176v5a3 3 0 0 0 2.824 2.995l.176.005h18.436a13 13 0 0 0 2.911 2ZM32 52a1 1 0 1 0-2 0 1 1 0 0 0 2 0" />
            <path d="M45 19c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12M31 31c0-7.732 6.268-14 14-14s14 6.268 14 14-6.268 14-14 14-14-6.268-14-14" />
          </g>
          <path
            className="fillStrong"
            d="M44.18 27v8.376H42.5V27zm3.34 2.76q.324-.528.84-.828.528-.3 1.2-.3v1.764h-.444q-.792 0-1.2.372-.396.372-.396 1.296v3.312h-1.68v-6.648h1.68z"
            fill="#A060F6"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
