'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ElasticMetalBerylliumProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="ElasticMetalBeryllium">
    <g className="Elasticmetal-Beryllium">
      <g className="Elasticmetal-Beryllium-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="Elasticmetal">
          <g className="Serveur">
            <path
              className="fillStrong"
              clipRule="evenodd"
              d="M24 35a3 3 0 1 0-6 0 3 3 0 0 0 6 0m-4 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0"
              fill="#A060F6"
              fillRule="evenodd"
            />
          </g>
          <path
            className="fillStrong"
            d="M17.063 20.717C18.079 15.088 22.47 11 27.578 11c3.6 0 6.829 2.019 8.792 5.19a1 1 0 0 0 1.54.198c.776-.739 1.78-1.174 2.868-1.174 2.135 0 3.664 1.147 4.529 2.79q1.126.03 2.191.256a1 1 0 0 0-.072-.44c-1.04-2.538-3.304-4.606-6.648-4.606a6.06 6.06 0 0 0-3.331 1C35.13 11.055 31.587 9 27.577 9c-5.984 0-10.896 4.553-12.315 10.559C11.09 19.899 8 23.87 8 28.437c0 3.862 2.184 7.25 5.367 8.449a1 1 0 1 0 .705-1.872C11.776 34.15 10 31.59 10 28.437c0-3.948 2.741-6.896 5.835-6.902l.224.005a1 1 0 0 0 1.004-.823"
            fill="#A060F6"
          />
          <g
            className="fill"
            clipRule="evenodd"
            fill="#521094"
            fillRule="evenodd"
          >
            <path d="M39.17 42.622H32v6.549A3 3 0 0 1 33.83 51h13.334a1 1 0 0 1 .117 1.993l-.117.007H33.83a3.001 3.001 0 0 1-5.658 0H14a1 1 0 0 1-.117-1.993L14 51h14.171A3 3 0 0 1 30 49.17v-6.548H17.822a5 5 0 0 1-5-5v-5a5 5 0 0 1 5-5h14.621a13 13 0 0 0-.37 2h-14.25a3 3 0 0 0-2.996 2.824l-.005.176v5a3 3 0 0 0 2.824 2.995l.176.005h18.436a13 13 0 0 0 2.911 2ZM32 52a1 1 0 1 0-2 0 1 1 0 0 0 2 0" />
            <path d="M45 19c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12M31 31c0-7.732 6.268-14 14-14s14 6.268 14 14-6.268 14-14 14-14-6.268-14-14" />
          </g>
          <path
            className="fillStrong"
            d="M43.752 30.704q.708.132 1.164.708t.456 1.32q0 .672-.336 1.188-.324.504-.948.792T42.612 35H39v-8.376h3.456q.852 0 1.464.276.624.276.936.768.324.492.324 1.116 0 .732-.396 1.224-.384.492-1.032.696m-3.072-.624h1.536q.6 0 .924-.264.324-.276.324-.78c0-.504-.108-.596-.324-.78q-.324-.276-.924-.276H40.68zm1.692 3.552q.612 0 .948-.288.348-.288.348-.816 0-.54-.36-.84-.36-.312-.972-.312H40.68v2.256zm10.518-2.1q0 .36-.047.648h-4.86q.06.72.504 1.128t1.092.408q.936 0 1.332-.804h1.812a3.06 3.06 0 0 1-1.104 1.584q-.816.612-2.004.612-.96 0-1.728-.42a3.1 3.1 0 0 1-1.188-1.212q-.42-.78-.42-1.8 0-1.032.42-1.812t1.176-1.2 1.74-.42q.948 0 1.692.408.756.408 1.164 1.164.42.744.42 1.716Zm-1.74-.48q-.01-.648-.467-1.032-.456-.396-1.116-.396-.624 0-1.056.384-.42.372-.516 1.044z"
            fill="#A060F6"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
