'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const FlexibleIpProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="FlexibleIpProductIcon">
    <g className="Flexible-Ip">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fill"
        clipRule="evenodd"
        d="M18 26c0-7.732 6.268-14 14-14s14 6.268 14 14c0 2.342-.576 4.602-1.662 6.62l-.035.078-11.432 20.284a1 1 0 0 1-1.742 0L19.696 32.685A13.94 13.94 0 0 1 18 26m26 0c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 2.03.504 3.987 1.45 5.723L32 50.454l10.526-18.678.292-.575a11.9 11.9 0 0 0 1.167-4.594z"
        fill="#4F0599"
        fillRule="evenodd"
      />
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M25.584 26a6.417 6.417 0 1 1 12.833 0 6.417 6.417 0 0 1-12.834 0Zm10.833 0a4.417 4.417 0 1 0-8.833 0 4.417 4.417 0 0 0 8.833 0"
        fill="#A365F6"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
