'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

import type { IconProps } from '../Icon'

export const ForkProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  <Icon {...props} title="ForkProductIcon">
    <g
      className="sentiment=original, size=xlarge, disabled=false"
      clipPath="url(#a)"
    >
      <g className=".Square">
        <g className="fillWeak">
          <path
            fill="#521094"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48V16Z"
          />
          <path
            fill="#521094"
            fillRule="evenodd"
            d="M48 2H16C8.268 2 2 8.268 2 16v32c0 7.732 6.268 14 14 14h32c7.732 0 14-6.268 14-14V16c0-7.732-6.268-14-14-14ZM16 0C7.163 0 0 7.163 0 16v32c0 8.837 7.163 16 16 16h32c8.837 0 16-7.163 16-16V16c0-8.837-7.163-16-16-16H16Z"
            clipRule="evenodd"
          />
        </g>
      </g>
      <g>
        <path
          fill="#fff"
          d="M48.038 11.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 1 1-1.414-1.414l1.22-1.22H33.35a4 4 0 0 0-4 4v7a5.978 5.978 0 0 1-1.528 4h21.581l-1.365-1.366a1 1 0 0 1 1.414-1.414l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 1 1-1.414-1.414l1.22-1.22H27.823a5.978 5.978 0 0 1 1.528 4v7a4 4 0 0 0 4 4h16.053l-1.365-1.366a1 1 0 0 1 1.414-1.414l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 1 1-1.414-1.414l1.22-1.22H33.35a6 6 0 0 1-6-6v-7a4 4 0 0 0-4-4h-4.605a1 1 0 1 1 0-2h4.605a4 4 0 0 0 4-4v-7a6 6 0 0 1 6-6h16.053l-1.365-1.366a1 1 0 0 1 0-1.414Z"
          className="fill"
        />
        <path
          fill="#BF95F9"
          d="M16.745 32a2 2 0 1 0-2 2v2a4 4 0 1 1 0-8 4 4 0 0 1 0 8v-2a2 2 0 0 0 2-2Z"
          className="fillStrong"
        />
      </g>
    </g>
    <defs>
      <clipPath id="a" className="a">
        <path fill="#fff" d="M0 0h64v64H0z" className="fill" />
      </clipPath>
    </defs>
  </Icon>
)
