'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const FrontEndsProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="FrontEndsProductIcon">
    <g className="Frontends">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M31.182 4a1 1 0 0 1 .984.82l.016.18v15.297l3.384-3.948a1 1 0 0 1 1.623 1.155l-.104.147-5.143 6a1 1 0 0 1-1.39.126l-.002-.003a1 1 0 0 1-.127-.123l-5.143-6a1 1 0 0 1 1.39-1.428l.129.126 3.383 3.947V5a1 1 0 0 1 1-1"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="m19.114 47.581 10.683-18.794a1.941 1.941 0 0 1 3.375 0L43.855 47.58a1.94 1.94 0 0 1-1.687 2.9H20.8a1.94 1.94 0 0 1-1.687-2.9Zm22.95.9L31.483 29.866 20.902 48.482z"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
