'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const FunctionsProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="FunctionsProductIcon">
    <g className="Serverless-Functions">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fill"
        d="M44.63 32.825a1 1 0 0 0 .102-1.57l-.102-.08-6.565-4.5a1 1 0 0 0-1.23 1.573l.1.077 5.361 3.676-5.361 3.674a1 1 0 0 0-.324 1.283l.064.108a1 1 0 0 0 1.283.323l.107-.064zm-25.257 0a1 1 0 0 1-.102-1.57l.102-.08 6.562-4.5a1 1 0 0 1 1.23 1.572l-.1.078L21.706 32l5.36 3.675a1 1 0 0 1 .325 1.282l-.065.108a1 1 0 0 1-1.282.323l-.108-.064-6.562-4.5Z"
        fill="#4F0599"
      />
      <path
        className="fillStrong"
        d="M34.042 21.713a1 1 0 0 1 1.943.46l-.027.114-6 20a1 1 0 0 1-1.943-.46l.027-.114z"
        fill="#A365F6"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="M52 32c0-11.046-8.954-20-20-20s-20 8.954-20 20 8.954 20 20 20 20-8.954 20-20m-37.973 0c0-9.941 8.06-18 18-18 9.941 0 18 8.059 18 18s-8.059 18-18 18c-9.94 0-18-8.059-18-18"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
