'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const IamProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="IamProductIcon">
    <g className="IAM">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="icon">
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M45 51a8 8 0 1 0 0-16 8 8 0 0 0 0 16m0 2c5.523 0 10-4.477 10-10s-4.477-10-10-10-10 4.477-10 10 4.477 10 10 10"
          fill="#A365F6"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="m32 8-20 8.595v12.893c0 11.925 8.533 23.077 20 25.785 2.91-.688 5.632-1.919 8.073-3.569a10 10 0 0 1-1.741-1.252A22.4 22.4 0 0 1 32 53.212c-3.765-.977-7.183-2.958-10.005-5.609A1 1 0 0 0 22 47.5v-5.166a6 6 0 0 1 6-6h8q.726.001 1.402.164c.496-.579 1.057-1.1 1.671-1.553A8 8 0 0 0 36 34.334h-8a8 8 0 0 0-8 8V45.5c-3.727-4.404-6-10.105-6-16.013V17.912l18-7.735 18 7.735v11.576a23.6 23.6 0 0 1-.457 4.601c.64.327 1.24.721 1.792 1.173A25.6 25.6 0 0 0 52 29.488V16.595zm-.147 10a6.333 6.333 0 1 0 0 12.667 6.333 6.333 0 0 0 0-12.667m-8.333 6.333a8.333 8.333 0 1 1 16.667 0 8.333 8.333 0 0 1-16.667 0"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M49.774 39.661a1 1 0 0 1 0 1.414L43.9 46.95l-3.291-3.291a1 1 0 0 1 1.414-1.414L43.9 44.12l4.46-4.46a1 1 0 0 1 1.414 0Z"
          fill="#A365F6"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
