'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const InstanceProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="InstanceProductIcon">
    <g className="Instance">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fill"
        clipRule="evenodd"
        d="M25.493 12.883A1 1 0 0 0 23.5 13v5H23a5 5 0 0 0-5 5v.5h-5l-.117.007A1 1 0 0 0 13 25.5h5v3h-5l-.117.007A1 1 0 0 0 13 30.5h5v3h-5l-.117.007A1 1 0 0 0 13 35.5h5v3h-5l-.117.007A1 1 0 0 0 13 40.5h5v.5a5 5 0 0 0 5 5h.5v4.828l.007.117a1 1 0 0 0 1.993-.117V46h3v4.828l.007.117a1 1 0 0 0 1.993-.117V46h3v4.828l.007.117a1 1 0 0 0 1.993-.117V46h3v4.828l.007.117a1 1 0 0 0 1.993-.117V46h.5a5 5 0 0 0 5-5v-.5h4.828l.117-.007a1 1 0 0 0-.117-1.993H46v-3h4.828l.117-.007a1 1 0 0 0-.117-1.993H46v-3h4.828l.117-.007a1 1 0 0 0-.117-1.993H46v-3h4.828l.117-.007a1 1 0 0 0-.117-1.993H46V23a5 5 0 0 0-5-5h-.5v-5l-.007-.117A1 1 0 0 0 38.5 13v5h-3v-5l-.007-.117A1 1 0 0 0 33.5 13v5h-3v-5l-.007-.117A1 1 0 0 0 28.5 13v5h-3v-5zM44 24.5V23a3 3 0 0 0-2.824-2.995L41 20H23a3 3 0 0 0-2.995 2.824L20 23v18a3 3 0 0 0 2.824 2.995L23 44h18a3 3 0 0 0 2.995-2.824L44 41z"
        fill="#4F0599"
        fillRule="evenodd"
      />
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M40 26a2 2 0 0 0-2-2H26a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zm-14 0h12v12H26z"
        fill="#A365F6"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
