'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const InterlinkProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Interlink">
    <g className="Direct-Connect">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M31 26V12.135h2V26zm17.63-5.215-10.904 6.627 1.039 1.71 10.904-6.628-1.04-1.71ZM37.689 36.287l.954-1.758 11.166 6.058-.953 1.758zM31 51.88V38h2v13.881z"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="M28 9a4 4 0 0 1 4-4l.2.005a4 4 0 0 1 3.655 5.066l12.974 7.49A4 4 0 0 1 52 16l.2.005a4 4 0 0 1 .719 7.889v15.212A4.002 4.002 0 0 1 52 47l-.2-.005a4 4 0 0 1-2.351-.914l-13.594 7.848A4.003 4.003 0 0 1 32 59l-.2-.005A4 4 0 0 1 32 51l.2.005a4 4 0 0 1 2.654 1.192l13.417-7.746a4 4 0 0 1 2.647-5.303V23.852a4 4 0 0 1-2.876-4.435l-13.188-7.615A4 4 0 0 1 32 13l-.2-.005A4 4 0 0 1 28 9m4 44a2 2 0 1 1 0 4 2 2 0 0 1 0-4m20-12a2 2 0 1 1 0 4 2 2 0 0 1 0-4m0-23a2 2 0 1 1 0 4 2 2 0 0 1 0-4M32 7a2 2 0 1 1 0 4 2 2 0 0 1 0-4m-6 18a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V26a1 1 0 0 0-1-1zm1 12V27h10v10zm-17-9a4 4 0 1 0 3.874 5H20v8.968a1 1 0 0 0 .883.993l.117.007h5.072a1 1 0 0 0 .117-1.994l-.117-.006H22v-18h5a1 1 0 0 0 .993-.884l.007-.116a1 1 0 0 0-.883-.994L27 20.968h-6a1 1 0 0 0-.993.883l-.007.117V31h-6.126A4 4 0 0 0 10 28m0 6a2 2 0 1 0 0-4 2 2 0 0 0 0 4"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
