'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const MacMiniM2ProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="MacMiniM2ProductIcon">
    <g className="MacMini-M2">
      <g className=".Fill">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="MacMini-M2">
        <path
          className="fill"
          clipRule="evenodd"
          d="M40 8.5c5.523 0 10 4.477 10 10v16c0 5.523-4.477 10-10 10h-7v5.17a3 3 0 0 1 1.83 1.83h13.334a1 1 0 0 1 .117 1.993l-.117.007H34.83a3.001 3.001 0 0 1-5.658 0H15a1 1 0 0 1-.117-1.993L15 51.5h14.171A3 3 0 0 1 31 49.67V44.5h-7c-5.523 0-10-4.477-10-10v-16c0-5.523 4.477-10 10-10zm-8 34h-8l-.25-.004A8 8 0 0 1 16 34.5v-16l.004-.25A8 8 0 0 1 24 10.5h16l.25.004A8 8 0 0 1 48 18.5v16l-.004.25A8 8 0 0 1 40 42.5zm0 9a1 1 0 1 1 0 2 1 1 0 0 1 0-2"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M40 13.5a5 5 0 0 1 5 5v16a5 5 0 0 1-5 5H24a5 5 0 0 1-5-5v-16a5 5 0 0 1 5-5zm0 2H24a3 3 0 0 0-2.995 2.824L21 18.5v16a3 3 0 0 0 2.824 2.995L24 37.5h16a3 3 0 0 0 2.995-2.824L43 34.5v-16a3 3 0 0 0-2.824-2.995zm-3.696 11.84q-.57.53-1.53 1.33l-.52.44v1.04h4.94v-1.16h-2.95a31 31 0 0 0 1.41-1.26q.54-.53.96-1.24t.42-1.49q0-.99-.61-1.59-.61-.61-1.75-.61-1.04 0-1.72.62-.67.62-.71 1.82h1.36q.01-.58.28-.91.27-.34.77-.34c.5 0 .58.097.74.29q.24.29.24.8 0 .56-.38 1.14t-.95 1.12m-3.194 2.91v-6.98h-1.58l-2.22 5.19-2.22-5.19H25.5v6.98h1.4v-4.54l1.88 4.54h1.06l1.87-4.54v4.54z"
          fill="#A365F6"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
