'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ManagedKafkaProductIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <path
      fill="#f1eefc"
      className="fillWeak"
      d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
    />
    <path
      fill="#f1eefc"
      className="fillWeak"
      fillRule="evenodd"
      d="M48 2H16C8.268 2 2 8.268 2 16v32c0 7.732 6.268 14 14 14h32c7.732 0 14-6.268 14-14V16c0-7.732-6.268-14-14-14M16 0C7.163 0 0 7.163 0 16v32c0 8.837 7.163 16 16 16h32c8.837 0 16-7.163 16-16V16c0-8.837-7.163-16-16-16z"
      clipRule="evenodd"
    />
    <path
      fill="#a060f6"
      className="fillStrong"
      d="M37.793 49.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L39.086 54H23a1 1 0 0 1 0-2h16.086l-1.293-1.293a1 1 0 0 1 0-1.414M27 30.5a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 27 30.5m5 0a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 32 30.5m5.793-23.207a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L39.086 12H23a1 1 0 0 1 0-2h16.086l-1.293-1.293a1 1 0 0 1 0-1.414"
    />
    <path
      fill="#521094"
      className="fill"
      d="M27 37.5a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 27 37.5m5 0a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 32 37.5m5 0a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 37 37.5m-10-14a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 27 23.5m5 0a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 32 23.5m5 0a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 37 23.5"
    />
    <path
      fill="#521094"
      className="fill"
      fillRule="evenodd"
      d="M40 18.5a3 3 0 0 1 3 3v21a3 3 0 0 1-3 3H24a3 3 0 0 1-3-3v-21a3 3 0 0 1 3-3zm-16 2a1 1 0 0 0-1 1v21a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-21a1 1 0 0 0-1-1zM16 23a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V24a1 1 0 0 1 1-1zM9 39h6V25H9z"
      clipRule="evenodd"
    />
    <path
      fill="#521094"
      className="fill"
      d="M56 23a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-8a1 1 0 1 1 0-2h7V25h-7a1 1 0 1 1 0-2z"
    />
  </Icon>
)

ManagedKafkaProductIcon.displayName = 'ManagedKafkaProductIcon'
