'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const MultiUserProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="MultiUserProductIcon">
    <g className="Multi-Users">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="Multi-Users">
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M43 14a7 7 0 1 0 0 14 7 7 0 0 0 0-14m0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10m9.996 20.75A8 8 0 0 0 45 29h-4l-.334.007a7.96 7.96 0 0 0-4.006 1.272 1 1 0 1 0 1.086 1.679A5.97 5.97 0 0 1 41 31h4l.225.004A6 6 0 0 1 51 37v2.325l-.467.179Q46.758 40.893 43 40.892q-1.056 0-2.112-.11a1 1 0 1 0-.206 1.99q1.159.12 2.318.12 4.706-.001 9.387-1.97A1 1 0 0 0 53 40v-3zM23 29c1.551 0 3.04.443 4.318 1.264a1 1 0 0 1-1.081 1.683 5.96 5.96 0 0 0-2.947-.94L23 31h-4a6 6 0 0 0-5.996 5.775L13 37v2.326l.467.178q3.505 1.29 6.996 1.38l.537.008q1.057 0 2.115-.11a1 1 0 0 1 .206 1.99q-1.16.12-2.321.12-4.706-.001-9.387-1.97a1 1 0 0 1-.606-.803L11 40v-3a8 8 0 0 1 7.75-7.996L19 29zm-2-15a7 7 0 1 0 0 14 7 7 0 0 0 0-14m0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10"
          fill="#A365F6"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="M32 21a7 7 0 1 1 0 14 7 7 0 0 1 0-14m9.996 22.75A8 8 0 0 0 34 36h-4l-.25.004A8 8 0 0 0 22 44v3l.007.12a1 1 0 0 0 .605.802q4.682 1.969 9.388 1.97c4.706.001 6.267-.658 9.388-1.97A1 1 0 0 0 42 47v-3zM34 38l.225.004.223.013A6 6 0 0 1 40 44v2.325l-.467.179-.54.191Q35.49 47.893 32 47.892l-.537-.007-.537-.021q-3.224-.17-6.459-1.36L24 46.326V44l.004-.225A6 6 0 0 1 30 38zm-7-10a5 5 0 1 1 10 0 5 5 0 0 1-10 0"
          fill="#4F0599"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
