'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const NetworkAclsProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="NetworkAclsProductIcon">
    <g className="sentiment=primary, disabled=false, size=xlarge">
      <g className="icon">
        <g className=".Square">
          <g className="fillWeak" fill="#F1EEFC">
            <path d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z" />
            <path
              clipRule="evenodd"
              d="M48 2H16C8.268 2 2 8.268 2 16v32c0 7.732 6.268 14 14 14h32c7.732 0 14-6.268 14-14V16c0-7.732-6.268-14-14-14M16 0C7.163 0 0 7.163 0 16v32c0 8.837 7.163 16 16 16h32c8.837 0 16-7.163 16-16V16c0-8.837-7.163-16-16-16z"
              fillRule="evenodd"
            />
          </g>
        </g>
        <path
          className="fill"
          clipRule="evenodd"
          d="M33 13.874A4.002 4.002 0 0 0 32 6a4 4 0 0 0-1 7.874v10.188a8 8 0 0 0-6.247 11.332l-9.013 5.692a4 4 0 1 0 1.069 1.69l9.014-5.692A8 8 0 0 0 31 39.938v10.188A4.002 4.002 0 0 0 32 58a4 4 0 0 0 1-7.874V39.938a8.001 8.001 0 0 0 0-15.876zM32 12a2 2 0 1 0 0-4 2 2 0 0 0 0 4m0 26a6 6 0 1 0 0-12 6 6 0 0 0 0 12m0 18a2 2 0 1 0 0-4 2 2 0 0 0 0 4M15 44a2 2 0 1 1-4 0 2 2 0 0 1 4 0"
          fill="#521094"
          fillRule="evenodd"
        />
        <g className="fillStrong" fill="#A060F6">
          <path
            clipRule="evenodd"
            d="M17 20c0 .463-.079.907-.223 1.32l3.42 2.356a1 1 0 1 1-1.135 1.647l-3.397-2.34A4 4 0 1 1 17 20m-2 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0"
            fillRule="evenodd"
          />
          <path d="M22.913 25.828a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
          <path
            clipRule="evenodd"
            d="M51 24a4 4 0 1 0-3.794-2.728l-3.49 2.404a1 1 0 0 0 1.135 1.647l3.447-2.374A4 4 0 0 0 51 24m0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4m0 26a4 4 0 1 0-2.593-7.046l-3.467-2.389a1 1 0 0 0-1.135 1.647l3.45 2.377A4 4 0 0 0 51 48m0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4"
            fillRule="evenodd"
          />
          <path d="M42 37a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1-11.172a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
        </g>
      </g>
    </g>
  </Icon>
)
