'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const OriginsResourcesProductIcon = ({ ...props }: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <path
      fill="#521094"
      className="fillWeak"
      d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
    />
    <path
      fill="#521094"
      className="fillWeak"
      fillRule="evenodd"
      d="M48 2H16C8.268 2 2 8.268 2 16v32c0 7.732 6.268 14 14 14h32c7.732 0 14-6.268 14-14V16c0-7.732-6.268-14-14-14M16 0C7.163 0 0 7.163 0 16v32c0 8.837 7.163 16 16 16h32c8.837 0 16-7.163 16-16V16c0-8.837-7.163-16-16-16z"
      clipRule="evenodd"
    />
    <path
      fill="#bf95f9"
      className="fillStrong"
      d="M28 49v2H15v-2zm0-13H15v15l-.204-.01A2 2 0 0 1 13 49V36a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2zm21-8v2H36v-2zm0-13H36v15a2 2 0 0 1-2-2V15a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2z"
    />
    <path
      fill="#fff"
      className="fill"
      d="M49 49v2H36v-2zm0-13H36v15a2 2 0 0 1-2-2V36a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2zm-21-8v2H15v-2zm0-13H15v15l-.204-.01A2 2 0 0 1 13 28V15a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2z"
    />
  </Icon>
)

OriginsResourcesProductIcon.displayName = 'OriginsResourcesProductIcon'
