'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const OsProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="OsProductIcon">
    <g className="OS">
      <g className="OS-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="Icon">
          <path
            className="fillStrong"
            clipRule="evenodd"
            d="m45.483 19.918-.104-.054-.107-.042a1 1 0 0 0-.82 1.81l7.033 4.225.104.054a1 1 0 0 0 .926-1.768zm-26.9 2.296a1 1 0 0 0-1.125-1.65l-5.972 3.578-.097.066a1 1 0 0 0 1.125 1.65l5.972-3.579.096-.066Z"
            fill="#4F0599"
            fillRule="evenodd"
          />
          <path
            className="fillStrong"
            clipRule="evenodd"
            d="M46 23.5C46 15.492 39.508 9 31.5 9S17 15.492 17 23.5c0 1.843.345 3.64 1.006 5.317l.81.441 1.299-.59-.163-.374A12.5 12.5 0 0 1 19 23.5C19 16.596 24.596 11 31.5 11S44 16.596 44 23.5c0 2.007-.473 3.945-1.367 5.69l2.777-1.584c.389-1.319.59-2.698.59-4.106"
            fill="#A060F6"
            fillRule="evenodd"
          />
          <g
            className="fill"
            clipRule="evenodd"
            fill="#521094"
            fillRule="evenodd"
          >
            <path d="M11 41.596V25a1 1 0 0 1 1.495-.869l20 11.404a1 1 0 0 1 .505.87V53a1 1 0 0 1-1.495.869l-20-11.404a1 1 0 0 1-.505-.87Zm20-4.61L13 26.72v14.294l18 10.264z" />
            <path d="M53 41.596V25a1 1 0 0 0-1.495-.869l-20 11.404a1 1 0 0 0-.505.87V53a1 1 0 0 0 1.495.869l20-11.404a1 1 0 0 0 .505-.87Zm-20-4.61L51 26.72v14.293L33 51.278z" />
          </g>
          <path
            className="fillStrong"
            d="M28.58 27.15a3.6 3.6 0 0 1-1.8-.46 3.45 3.45 0 0 1-1.3-1.27 3.6 3.6 0 0 1-.48-1.85q0-1.02.48-1.83.48-.82 1.3-1.28a3.6 3.6 0 0 1 1.8-.46q.99 0 1.8.46.82.46 1.29 1.28.48.81.48 1.83 0 1.03-.48 1.85a3.37 3.37 0 0 1-1.29 1.27 3.6 3.6 0 0 1-1.8.46m0-1.25q.63 0 1.11-.28.48-.29.75-.82t.27-1.23-.27-1.22a1.9 1.9 0 0 0-.75-.81 2.16 2.16 0 0 0-1.11-.28q-.63 0-1.12.28-.48.28-.75.81-.27.52-.27 1.22t.27 1.23.75.82q.49.28 1.12.28m7.022 1.25q-.73 0-1.32-.25a2.16 2.16 0 0 1-.92-.72 1.9 1.9 0 0 1-.35-1.11h1.5q.03.43.3.68.28.25.76.25.49 0 .77-.23a.78.78 0 0 0 .28-.62.7.7 0 0 0-.19-.51 1.3 1.3 0 0 0-.48-.31 7 7 0 0 0-.78-.26 9 9 0 0 1-1.11-.39 2.06 2.06 0 0 1-.73-.59q-.3-.4-.3-1.06 0-.62.31-1.08a1.93 1.93 0 0 1 .87-.7q.56-.25 1.28-.25 1.08 0 1.75.53.68.52.75 1.46h-1.54a.78.78 0 0 0-.31-.59q-.28-.24-.75-.24-.411 0-.66.21-.24.21-.24.61 0 .28.18.47.19.18.46.3.279.11.78.26.68.2 1.11.4t.74.6.31 1.05q0 .56-.29 1.04a2.1 2.1 0 0 1-.85.77q-.56.28-1.33.28"
            fill="#A060F6"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
