'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const QueueingProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="QueueingProductIcon">
    <g className="Queuing">
      <g className="icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#EEF"
          />
        </g>
        <g className="icon">
          <path
            className="fillStrong"
            d="M33 19a1 1 0 0 0-1 1v24a1 1 0 1 0 2 0V20a1 1 0 0 0-1-1m-19 4a1 1 0 1 1 2 0 1 1 0 0 1-2 0m14 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0m-3 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2m3 1a1 1 0 1 1 2 0 1 1 0 0 1-2 0m-13 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2m3 1a1 1 0 1 1 2 0 1 1 0 0 1-2 0"
            fill="#A365F6"
          />
          <path
            className="fill"
            d="M18 23a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1m4 18a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1m-7-10a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2zm22-12a1 1 0 0 0-1 1v24a1 1 0 1 0 2 0V33h8.9l-2.593 2.593a1 1 0 0 0 1.414 1.414l4.243-4.243a1 1 0 0 0 .275-.898 1 1 0 0 0-.29-.616l-4.242-4.243a1 1 0 0 0-1.414 1.414L46.872 31H38V20a1 1 0 0 0-1-1"
            fill="#4F0599"
          />
        </g>
      </g>
    </g>
  </Icon>
)
