'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const RabbitMqProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="RabbitMq">
    <g className="Managed-RabbitMQ">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#F1EEFC"
        />
      </g>
      <g className="icon">
        <g className="fill" fill="#521094">
          <path
            clipRule="evenodd"
            d="M7 24a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1V25a1 1 0 0 0-1-1zm1 14V26h3v12z"
            fillRule="evenodd"
          />
          <path d="M52 24a1 1 0 1 0 0 2h4v12h-4a1 1 0 1 0 0 2h5a1 1 0 0 0 1-1V25a1 1 0 0 0-1-1zM17 39.5a1 1 0 0 1-1-1v-12a1 1 0 1 1 2 0v12a1 1 0 0 1-1 1m3 0a1 1 0 0 1-1-1v-12a1 1 0 1 1 2 0v12a1 1 0 0 1-1 1m27-1a1 1 0 1 0 2 0v-12a1 1 0 1 0-2 0zm-4 1a1 1 0 0 1-1-1v-12a1 1 0 1 1 2 0v12a1 1 0 0 1-1 1" />
        </g>
        <g className="fillStrong" fill="#A060F6">
          <path d="M37.293 13.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L38.586 18H22.5a1 1 0 1 1 0-2h16.086l-1.293-1.293a1 1 0 0 1 0-1.414m0 30a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L38.586 48H22.5a1 1 0 1 1 0-2h16.086l-1.293-1.293a1 1 0 0 1 0-1.414m-7.464-8.668c0 .621-.336 1.125-.75 1.125-.415 0-.75-.504-.75-1.125s.335-1.125.75-1.125c.414 0 .75.504.75 1.125m4.178 1.125c.414 0 .75-.504.75-1.125s-.336-1.125-.75-1.125-.75.504-.75 1.125.336 1.125.75 1.125" />
          <path
            clipRule="evenodd"
            d="M30.529 28.997v.002l-1 .001h1v1.143h1.942V29h1c-1 0-1-.002-1-.002v-.017l.001-.037a6.5 6.5 0 0 1 .303-1.762c.297-.885 1.044-2.182 2.71-2.182 1.668 0 2.414 1.297 2.711 2.182.156.464.23.914.266 1.238a6 6 0 0 1 .037.524v.037l.001.011v7.122a4 4 0 0 1-4 4h-6a4 4 0 0 1-4-4V29h1c-1 0-1-.002-1-.002v-.054l.005-.12a6.4 6.4 0 0 1 .299-1.642C25.1 26.297 25.847 25 27.514 25s2.414 1.297 2.71 2.182c.157.464.23.914.267 1.238a7 7 0 0 1 .037.524v.053ZM26.5 36.114V28.99a4 4 0 0 1 .025-.347 4 4 0 0 1 .175-.824c.206-.615.467-.818.814-.818s.608.203.815.818a4.5 4.5 0 0 1 .2 1.17v2.155a1 1 0 0 0 1 1h3.942a1 1 0 0 0 1-1V28.99l.003-.07a4.5 4.5 0 0 1 .197-1.1c.207-.616.468-.819.815-.819s.608.203.814.818a4.4 4.4 0 0 1 .2 1.17v7.126a2 2 0 0 1-2 2h-6a2 2 0 0 1-2-2Z"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
  </Icon>
)
