'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const RdbProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Rdb">
    <g className="Managed-Database">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M22.375 28.867C20.172 28.237 19 27.445 19 27h-2l.005.146c.2 2.913 6.374 4.734 14.206 4.848L32 32c8.335 0 15-1.904 15-5h-2l-.006.055c-.09.454-1.255 1.208-3.37 1.812C39.113 29.585 35.677 30 32 30s-7.112-.415-9.625-1.133m0 9C20.172 37.237 19 36.446 19 36h-2l.005.147c.2 2.912 6.374 4.733 14.206 4.847L32 41c8.335 0 15-1.904 15-5h-2l-.006.055c-.09.454-1.255 1.208-3.37 1.812C39.113 38.585 35.677 39 32 39s-7.112-.415-9.625-1.133"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="m32 14-.789.006C23.248 14.122 17 16.003 17 19v25.455l.006.163C17.274 47.906 23.886 50 32 50c8.29 0 15-2.179 15-5.545V19c0-3.096-6.665-5-15-5m.781 9.994h.008c5.247-.076 9.75-.92 12.211-2.343v22.804C45 46.109 39.174 48 32 48c-7.067 0-12.862-1.835-12.998-3.504l-.003-.082L19 21.65C21.583 23.146 26.417 24 32 24h.004q.39 0 .777-.006M45 18.985c-.026-.448-1.197-1.23-3.375-1.852C39.112 16.415 35.676 16 32 16s-7.112.415-9.625 1.133C20.172 17.763 19 18.555 19 19l.006.055c.086.435 1.16 1.146 3.114 1.737l.251.074h.004C24.888 21.586 28.324 22 32 22c2.505 0 4.898-.193 6.964-.543a28 28 0 0 0 1.677-.335q.512-.12.984-.255l.046-.013q.487-.141.906-.29c1.532-.545 2.364-1.145 2.42-1.524z"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
