'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const RocketProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Rocket">
    <g className="Rocket">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#F1EEFC"
        />
      </g>
      <g className="Rocket">
        <g className="icon">
          <path
            className="fill (Stroke)"
            clipRule="evenodd"
            d="M37.745 18.324c-3.605.939-7.656 2.91-10.62 5.874-3.206 3.206-5.22 6.867-5.886 10.053l7.817 7.817c3.186-.666 6.847-2.68 10.053-5.887 2.963-2.963 4.935-7.014 5.874-10.62.469-1.8.67-3.448.624-4.755-.047-1.366-.355-2.14-.66-2.446-.307-.305-1.08-.613-2.447-.66-1.307-.046-2.955.155-4.755.624M42.57 15.7c1.486.051 2.924.379 3.79 1.245s1.195 2.305 1.246 3.791c.054 1.546-.183 3.392-.688 5.329-1.007 3.867-3.126 8.261-6.395 11.53-3.602 3.602-7.842 5.905-11.636 6.539l-.508.084-9.292-9.291.085-.508c.634-3.795 2.937-8.035 6.54-11.637 3.268-3.268 7.661-5.387 11.53-6.395 1.936-.504 3.782-.741 5.328-.687"
            fill="#521094"
            fillRule="evenodd"
          />
          <path
            className="fill (Stroke)"
            clipRule="evenodd"
            d="M24.4 26.007c-3.951-1.796-8.607.06-10.245 4.081a.88.88 0 0 0 .468 1.143l6.295 2.698 8.832 8.832 2.698 6.295c.188.44.697.65 1.143.468 4.02-1.638 5.877-6.294 4.081-10.244a1 1 0 1 1 1.821-.828c2.267 4.987-.077 10.858-5.147 12.924a2.88 2.88 0 0 1-3.737-1.532l-2.546-5.941-8.287-8.287-5.94-2.546a2.88 2.88 0 0 1-1.533-3.737c2.066-5.07 7.937-7.414 12.924-5.147a1 1 0 0 1-.828 1.82Z"
            fill="#521094"
            fillRule="evenodd"
          />
          <path
            className="fillStrong (Stroke)"
            clipRule="evenodd"
            d="M35.73 27.007a2.158 2.158 0 1 0-3.052 3.052 2.158 2.158 0 0 0 3.051-3.052Zm-4.467-1.414a4.158 4.158 0 1 1 5.88 5.88 4.158 4.158 0 0 1-5.88-5.88M19.032 38.998a1 1 0 0 1 .81 1.159l-.593 3.365a1.105 1.105 0 0 0 1.28 1.28l3.365-.594a1 1 0 1 1 .348 1.97l-3.365.594c-2.123.374-3.973-1.475-3.598-3.598l.594-3.365a1 1 0 0 1 1.159-.81Z"
            fill="#A060F6"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
  </Icon>
)
