'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const SdkPythonProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="SdkPythonProductIcon">
    <g className="SDK-Python">
      <g className="SDK-Python-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="SDK-Python-icon">
          <g className="fill" fill="#521094">
            <path d="M31.498 9.134a1 1 0 0 1 .881-.059l.12.059 18.998 10.969a1 1 0 0 1 .11 1.658l-.11.074-8.785 5.072-1-1.733 7.284-4.206-16.998-9.813-16.999 9.813 7.343 4.24-1 1.732-8.842-5.105a1 1 0 0 1-.11-1.659l.11-.073z" />
            <path d="M12 20.969a1 1 0 0 1 1.399-.918l.101.052 8.943 5.163-1 1.732L14 22.7v19.629l16.999 9.813v-9.145h2v10.878a1 1 0 0 1-1.398.917l-.102-.051L12.5 43.772a1 1 0 0 1-.493-.748L12 42.906z" />
            <path d="M50.497 20.103a1 1 0 0 1 1.494.752l.006.114v21.937a1 1 0 0 1-.401.801l-.1.065-18.998 10.969a1 1 0 0 1-1.493-.753l-.007-.113V43.04h2v9.102l16.998-9.813V22.7l-7.32 4.227-1-1.732 8.82-5.092Z" />
          </g>
          <path
            className="fillStrong"
            clipRule="evenodd"
            d="m21.54 24.884 9.96-5.75a1 1 0 0 1 1 0l9.96 5.75a1 1 0 0 1 .5.866v11.5a1 1 0 0 1-.5.866l-9.96 5.75a1 1 0 0 1-1 0l-9.96-5.75a1 1 0 0 1-.5-.866v-11.5a1 1 0 0 1 .5-.866m19.419 1.443-8.96-5.172-8.96 5.172v10.345L32 41.844l8.96-5.172z"
            fill="#A060F6"
            fillRule="evenodd"
          />
          <path
            className="fillStrong"
            d="M31.813 30.166q0 .563-.256 1.053a1.86 1.86 0 0 1-.784.792q-.53.301-1.343.301h-1.106V35H27v-7h2.43q.765 0 1.305.28.539.282.803.773.275.492.275 1.113m-2.44 1.013q.549 0 .813-.26.265-.271.265-.753 0-1.023-1.078-1.023h-1.05v2.036zM38 28l-2.231 4.563V35h-1.324v-2.437L32.204 28h1.494l1.418 3.2 1.409-3.2z"
            fill="#A060F6"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
