'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const SecretManagerProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="SecretManagerProductIcon">
    <g className="IoT-Edge">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="Icon">
        <path
          className="fillStrong"
          d="m23.433 43.545.124-1.924-1.61 1.08-.667-1.174 1.735-.845-1.735-.845.666-1.174 1.611 1.08-.124-1.925h1.337l-.13 1.924 1.612-1.079.666 1.174-1.73.845 1.73.845-.666 1.173-1.611-1.079.13 1.924zm7.902 0 .124-1.924-1.61 1.08-.667-1.174 1.736-.845-1.736-.845.667-1.174 1.61 1.08-.124-1.925h1.337l-.129 1.924 1.611-1.079.666 1.174-1.73.845 1.73.845-.666 1.173-1.61-1.079.128 1.924zm7.902 0 .125-1.924-1.611 1.08-.666-1.174 1.735-.845-1.735-.845.666-1.174 1.61 1.08-.124-1.925h1.338l-.13 1.924 1.611-1.079.666 1.174-1.73.845 1.73.845-.666 1.173-1.61-1.079.129 1.924z"
          fill="#A365F6"
        />
        <path
          className="fill"
          d="M22 30a6 6 0 0 0-6 6v10a6 6 0 0 0 6 6h20a6 6 0 0 0 6-6V36a6 6 0 0 0-6-6zm-8 6a8 8 0 0 1 8-8h20a8 8 0 0 1 8 8v10a8 8 0 0 1-8 8H22a8 8 0 0 1-8-8z"
          fill="#4F0599"
        />
        <path
          className="fill"
          d="M32 17a4 4 0 0 0-4 4v8a1 1 0 1 1-2 0v-8a6 6 0 0 1 12 0v8a1 1 0 1 1-2 0v-8a4 4 0 0 0-4-4"
          fill="#4F0599"
        />
        <path
          className="fill"
          d="M32 13a8 8 0 0 0-8 8v8a1 1 0 1 1-2 0v-8c0-5.523 4.477-10 10-10s10 4.477 10 10v8a1 1 0 1 1-2 0v-8a8 8 0 0 0-8-8"
          fill="#4F0599"
        />
      </g>
    </g>
  </Icon>
)
