'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'
import type { IconProps } from '../Icon'

export const ServerlessJobsProductIcon = (props: Omit<IconProps, 'children'>) => (
  <Icon {...props}>
    <g>
      <g clipPath="url(#a)">
        <g>
          <path
            fill="#f1eefc"
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          />
        </g>
        <g>
          <path
            fill="#a060f6"
            className="fillStrong"
            d="M45 15a1 1 0 0 1 1-1h9a1 1 0 1 1 0 2h-9a1 1 0 0 1-1-1m-1 16.928a1 1 0 0 1 1-1h10a1 1 0 1 1 0 2H45a1 1 0 0 1-1-1M44 49a1 1 0 0 1 1-1h10a1 1 0 1 1 0 2H45a1 1 0 0 1-1-1M24.605 16a4 4 0 0 0-4 4v7a6 6 0 0 1-6 6H9a1 1 0 1 1 0-2h5.605a4 4 0 0 0 4-4v-7a6 6 0 0 1 6-6H28a1 1 0 1 1 0 2z"
            clipRule="evenodd"
            fillRule="evenodd"
          />
          <path
            fill="#a060f6"
            className="fillStrong"
            d="M8 32a1 1 0 0 1 1-1h19a1 1 0 1 1 0 2H9a1 1 0 0 1-1-1"
            clipRule="evenodd"
            fillRule="evenodd"
          />
          <path
            fill="#a060f6"
            className="fillStrong"
            d="M8 32a1 1 0 0 1 1-1h5.605a6 6 0 0 1 6 6v7a4 4 0 0 0 4 4H28a1 1 0 1 1 0 2h-3.395a6 6 0 0 1-6-6v-7a4 4 0 0 0-4-4H9a1 1 0 0 1-1-1"
            clipRule="evenodd"
            fillRule="evenodd"
          />
          <g fill="#521094" className="fill">
            <path
              d="M27.427 11a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3h-12a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-8a1 1 0 0 0-1-1z"
              clipRule="evenodd"
              fillRule="evenodd"
            />
            <path
              d="M32 11a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1m4.5 0a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1m4.5 0a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1"
              clipRule="evenodd"
              fillRule="evenodd"
            />
          </g>
          <g fill="#521094" className="fill" clipRule="evenodd" fillRule="evenodd">
            <path d="M27.427 28a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3h-12a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-8a1 1 0 0 0-1-1z" />
            <g>
              <path d="M32 27.924a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1" />
              <path d="M36.5 27.924a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1" />
              <path d="M41 27.924a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0v-6a1 1 0 0 1 1-1" />
            </g>
          </g>
          <g fill="#521094" className="fill">
            <path
              d="M27.427 45a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3h-12a3 3 0 0 1-3-3zm3-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-8a1 1 0 0 0-1-1z"
              clipRule="evenodd"
              fillRule="evenodd"
            />
            <path
              d="M32 44.849a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0v-6a1 1 0 0 1 1-1m4.5 0a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0v-6a1 1 0 0 1 1-1m4.5 0a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0v-6a1 1 0 0 1 1-1"
              clipRule="evenodd"
              fillRule="evenodd"
            />
          </g>
          <path
            fill="#a060f6"
            className="fillStrong"
            d="M51.293 45.22a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.415l-3 3a1 1 0 1 1-1.414-1.414l2.293-2.293-2.293-2.293a1 1 0 0 1 0-1.414Zm0-17a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.415l-3 3a1 1 0 1 1-1.414-1.414l2.293-2.293-2.293-2.293a1 1 0 0 1 0-1.414Zm0-17a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.415l-3 3a1 1 0 1 1-1.414-1.414l2.293-2.293-2.293-2.293a1 1 0 0 1 0-1.414Z"
            clipRule="evenodd"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
  </Icon>
)

ServerlessJobsProductIcon.displayName = 'ServerlessJobsProductIcon'
