'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const ServerProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Server">
    <g className="Server">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="Server-icon">
        <g className="Icon">
          <path
            className="fill"
            clipRule="evenodd"
            d="M48.554 22h-31.34A7.214 7.214 0 0 0 10 29.214v7.025a7.214 7.214 0 0 0 7.214 7.214h31.34a7.214 7.214 0 0 0 7.214-7.214v-7.025A7.214 7.214 0 0 0 48.554 22m-31.34 2h31.34a5.214 5.214 0 0 1 5.214 5.214v7.025a5.214 5.214 0 0 1-5.214 5.214h-31.34A5.214 5.214 0 0 1 12 36.239v-7.025A5.214 5.214 0 0 1 17.214 24m30.865 8.727a1 1 0 0 0-1-1H30.453l-.18.016a1 1 0 0 0 .18 1.984h16.626l.18-.016a1 1 0 0 0 .82-.984"
            fill="#4F0599"
            fillRule="evenodd"
          />
          <path
            className="fillStrong"
            clipRule="evenodd"
            d="M25.59 32.726a4.863 4.863 0 1 0-9.727 0 4.863 4.863 0 0 0 9.727 0m-7.727 0a2.863 2.863 0 1 1 5.727 0 2.863 2.863 0 0 1-5.727 0"
            fill="#A365F6"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
  </Icon>
)
