'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const SmtpProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="SmtpProductIcon">
    <g className="SMTP">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M.512 16c0-8.837 7.163-16 16-16h32c8.836 0 16 7.163 16 16v32c0 8.837-7.164 16-16 16h-32c-8.837 0-16-7.163-16-16z"
          fill="#EEF"
        />
      </g>
      <g className="SMTP">
        <path
          className="fill"
          clipRule="evenodd"
          d="m48.55 26.521-3.345-2.801a1 1 0 0 1 1.285-1.533l3.344 2.801a1 1 0 0 1-1.284 1.534Zm-7.334-6.144L34.44 14.7a3 3 0 0 0-3.7-.12l-.155.121-6.699 5.62a1 1 0 0 1-1.376-1.445l.09-.086 6.7-5.621a5 5 0 0 1 6.425-.002l6.775 5.676a1 1 0 0 1-1.285 1.533Zm-25.923 4.556a1 1 0 0 0 1.377 1.445l3.113-2.612.09-.086a1 1 0 0 0-1.376-1.446l-3.113 2.612z"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          clipRule="evenodd"
          d="M45.512 18.78a1 1 0 0 1 .993.884l.007.116v13a1 1 0 0 1-1.994.117l-.006-.117v-12h-24v12a1 1 0 0 1-.884.993l-.116.007a1 1 0 0 1-.994-.883l-.006-.117v-13a1 1 0 0 1 .883-.993l.117-.007zm-6 12a1 1 0 0 1 .116 1.993l-.116.007h-14a1 1 0 0 1-.117-1.993l.117-.007zm1-5a1 1 0 0 0-1-1h-14l-.117.007a1 1 0 0 0 .117 1.993h14l.116-.007a1 1 0 0 0 .884-.993"
          fill="#A365F6"
          fillRule="evenodd"
        />
        <path
          className="fill"
          clipRule="evenodd"
          d="m38.389 39.895 11.123 8.178V30.841zm10.067 9.885L34.288 39.362a3 3 0 0 0-3.385-.116l-.17.117L16.567 49.78zm-32.944-1.707V30.866l11.117 9.032zm33.627-19.507L36.724 38.672l-1.252-.92-.198-.14a5 5 0 0 0-5.726.14l-1.254.922L15.883 28.59a1 1 0 0 1-.012-1.542l1.293-1.085.091-.087a1 1 0 0 0-1.376-1.445l-1.294 1.085-.141.127a3 3 0 0 0-.932 2.17V48.78l.005.176a3 3 0 0 0 2.995 2.824h32l.176-.005a3 3 0 0 0 2.824-2.995V27.812l-.005-.084a3 3 0 0 0-1.073-2.238l-1.239-1.037-.101-.075a1 1 0 0 0-1.183 1.608l1.239 1.038.07.064.063.07a1 1 0 0 1-.144 1.408"
          fill="#4F0599"
          fillRule="evenodd"
        />
      </g>
    </g>
  </Icon>
)
