'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const TransactionalEmailProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="TransactionalEmail">
    <g className="Transactional-Email" clipPath="url(#b)">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <path
        className="fillStrong"
        clipRule="evenodd"
        d="M22.538 23.752a.9.9 0 0 0-.9.9l.002 15.732a.9.9 0 0 0 .9.9h33.872l-1.657 1.657a.9.9 0 1 0 1.273 1.272l3.109-3.108a.9.9 0 0 0 0-1.273l-3.109-3.108a.9.9 0 1 0-1.273 1.272l1.488 1.488H23.44V28.695l9.711 6.338a.9.9 0 0 0 1.012-.02l8.519-6.034v7.249a.9.9 0 1 0 1.8 0V24.65a.9.9 0 0 0-.9-.9H22.538Zm11.085 9.439-10.184-6.645v-.994h19.243v1.221z"
        fill="#A365F6"
        fillRule="evenodd"
      />
      <path
        className="fill"
        clipRule="evenodd"
        d="M14.876 21a5 5 0 0 1 5-5h26.242a5 5 0 0 1 5 5v15.898a1 1 0 0 1-2 0V21a3 3 0 0 0-3-3H19.876a3 3 0 0 0-3 3v22.54a3 3 0 0 0 3 3h26.242a3 3 0 0 0 3-3v-.072a1 1 0 0 1 2 0v.072a5 5 0 0 1-5 5H19.876a5 5 0 0 1-5-5v-1.578h-3.907a.9.9 0 0 1 0-1.8h3.907V36.41H7.267a.9.9 0 0 1 0-1.8h7.609v-3.752H8.193a.9.9 0 1 1 0-1.8h6.683v-3.753H4a.9.9 0 1 1 0-1.8h10.876zM7.267 40.162a.9.9 0 0 0 0 1.8h.926a.9.9 0 1 0 0-1.8zM4.491 29.057a.9.9 0 0 0 0 1.8h.925a.9.9 0 1 0 0-1.8z"
        fill="#4F0599"
        fillRule="evenodd"
      />
    </g>
  </Icon>
)
