'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const TutorialProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="Tutorial">
    <g className="Tutorial">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M.512 16c0-8.837 7.163-16 16-16h32c8.836 0 16 7.163 16 16v32c0 8.837-7.164 16-16 16h-32c-8.837 0-16-7.163-16-16z"
          fill="#EEF"
        />
      </g>
      <g className="Tutorial">
        <g className="Icon">
          <path
            className="fill"
            d="M50.166 15.006c.598-.223 1.227.175 1.328.793l.014.174.004 24.86c0 .349-.172.67-.45.858l-.148.083-18.05 8.169a.97.97 0 0 1-.65.055l-.157-.056L14.11 41.78a1.02 1.02 0 0 1-.582-.769l-.014-.172-.003-24.86c0-.652.577-1.124 1.175-1.012l.163.045 6.476 2.395c.52.192.79.781.603 1.316a1 1 0 0 1-1.105.667l-.174-.047-5.14-1.902.004 22.727 16.948 7.708 17.05-7.716-.004-22.721-5.08 1.902a.99.99 0 0 1-1.206-.447l-.076-.168a1.04 1.04 0 0 1 .434-1.24l.164-.078 6.422-2.402Z"
            fill="#4F0599"
          />
          <path
            className="fill"
            clipRule="evenodd"
            d="M44.704 21.547a.99.99 0 0 0-1.3-.571l-11.22 4.634-.16.084c-.402.26-.578.785-.395 1.254a.99.99 0 0 0 1.3.57l11.219-4.633.16-.085c.402-.26.578-.785.395-1.253Zm0 6.499a.99.99 0 0 0-1.3-.571l-11.219 4.634-.16.084c-.402.26-.578.785-.395 1.254a.99.99 0 0 0 1.3.57l11.219-4.633.16-.085c.402-.26.578-.784.395-1.253"
            fill="#4F0599"
            fillRule="evenodd"
          />
          <path
            className="fillStrong"
            clipRule="evenodd"
            d="m31.513 20.032-9.525-4.413.002 19.566 9.523 4.542zm.41 22.16-11.352-5.415a1.03 1.03 0 0 1-.58-.933l-.003-21.814c0-.747.75-1.245 1.41-.938l11.141 5.16 11.133-5.16c.661-.307 1.41.191 1.41.938l.003 21.81c0 .4-.226.765-.579.933l-11.36 5.419a1 1 0 0 1-.61.198 1 1 0 0 1-.612-.198Zm1.635-2.465 9.526-4.544-.002-19.564-9.524 4.414z"
            fill="#A365F6"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
  </Icon>
)
