'use client'

/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import type { JSX } from 'react'
import type { IconProps } from '../Icon'
import { Icon } from '../Icon'

type IconType = (props: Omit<IconProps, 'children' | 'title'>) => JSX.Element

export const VerifyCardProductIcon: IconType = ({ ...props }) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="VerifyCardProductIcon">
    <g className="Verify-card">
      <g className=".Square">
        <path
          className="fillWeak"
          d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
          fill="#EEF"
        />
      </g>
      <g className="Icon">
        <path
          className="fill"
          clipRule="evenodd"
          d="M31.621 12.074a1 1 0 0 1 .758 0l17 6.954a1 1 0 0 1 .621.926v10.49c0 5.034-1.889 9.886-5.037 13.748-3.12 3.83-7.496 6.71-12.524 7.84a1 1 0 0 1-.415.005 22.35 22.35 0 0 1-12.988-7.846C15.888 40.329 14 35.478 14 30.444v-10.49a1 1 0 0 1 .621-.926zM16 20.625v9.819c0 4.534 1.703 8.946 4.587 12.484l.002.002a20.35 20.35 0 0 0 11.619 7.103c4.474-1.058 8.392-3.651 11.205-7.105C46.297 39.39 48 34.978 48 30.444v-9.819L32 14.08z"
          fill="#4F0599"
          fillRule="evenodd"
        />
        <path
          className="fillStrong"
          d="M32 22.08a5 5 0 1 1 0 10 5 5 0 0 1 0-10"
          fill="#A365F6"
        />
        <path
          className="fill"
          d="M40.728 40.26c-2.118 3.03-5.286 5.304-8.978 6.416-3.692-1.112-6.86-3.386-8.978-6.414a16.4 16.4 0 0 1-1.522-2.504c0-2.7 4.742-4.908 10.5-4.908s10.5 2.16 10.5 4.908a16.4 16.4 0 0 1-1.522 2.502"
          fill="#4F0599"
        />
      </g>
    </g>
  </Icon>
)
