'use client'

import type { IconProps } from '../Icon'
/**
 * Provide the icon component for the icon name.
 * This file is automatically generated from /utils/scripts/generate-icons-file.tsx.
 * PLEASE DO NOT EDIT HERE
 */
import { Icon } from '../Icon'

export const VpsStartServersProductIcon = ({
  ...props
}: Omit<IconProps, 'children' | 'title'>) => (
  // eslint-disable-next-line react/jsx-props-no-spreading
  <Icon {...props} title="VpsStartServersProductIcon">
    <g className="VPS-start-servers">
      <g className="VPS-start-servers" clipPath="url(#a)">
        <g className=".Square">
          <path
            className="fillWeak"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            fill="#F1EEFC"
          />
        </g>
        <g className="icon VPS-start">
          <g className="fillStrong" fill="#A060F6">
            <path d="M32.097 16.932h.481l6.215 3.105a1 1 0 0 1-.787 1.835l-.107-.046-5.561-2.78-5.56 2.78a1 1 0 0 1-1.284-.346l-.058-.101a1 1 0 0 1 .346-1.284l.101-.058zm6.296 10a1 1 0 0 0-1-1h-10l-.117.006a1 1 0 0 0 .117 1.994h10l.116-.007a1 1 0 0 0 .884-.993m-2.893 6a1 1 0 0 0-1-1h-7.107l-.117.006a1 1 0 0 0 .117 1.994H34.5l.116-.007a1 1 0 0 0 .884-.993M49.794 47.07q-.73 0-1.32-.25a2.16 2.16 0 0 1-.92-.72 1.9 1.9 0 0 1-.35-1.11h1.5q.03.43.3.68.28.25.76.25.49 0 .77-.23a.78.78 0 0 0 .28-.62.7.7 0 0 0-.19-.51 1.3 1.3 0 0 0-.48-.31 7 7 0 0 0-.78-.26 9 9 0 0 1-1.11-.39 2.06 2.06 0 0 1-.73-.59q-.3-.4-.3-1.06 0-.62.31-1.08a1.94 1.94 0 0 1 .87-.7q.56-.25 1.28-.25 1.08 0 1.75.53.68.52.75 1.46h-1.54a.78.78 0 0 0-.31-.59q-.28-.24-.75-.24-.41 0-.66.21-.24.21-.24.61 0 .28.18.47.19.18.46.3.28.11.78.26.68.2 1.11.4.43.201.74.6.31.4.31 1.05 0 .56-.29 1.04a2.1 2.1 0 0 1-.85.77q-.56.28-1.33.28" />
            <path
              clipRule="evenodd"
              d="M46.39 42.18q0 .561-.27 1.05-.26.49-.83.79-.56.3-1.42.3H42.7V47h-1.4v-6.98h2.57q.81 0 1.38.28t.85.77q.29.49.29 1.11m-2.58 1.01q.58 0 .86-.26.28-.27.28-.75 0-1.02-1.14-1.02H42.7v2.03z"
              fillRule="evenodd"
            />
            <path d="m37.9 47 2.56-6.98h-1.49l-1.91 5.55-1.92-5.55h-1.5L36.2 47z" />
          </g>
          <path
            className="fill"
            clipRule="evenodd"
            d="M32.32 8h.034a1 1 0 0 1 .447.105l22.32 11.155a1 1 0 0 1 .554.903l-.105 11.458a1 1 0 0 1-1.447.885l-10.732-5.364v1.863C50.942 29.212 57 35.4 57 43c0 7.732-6.268 14-14 14-7.053 0-12.888-5.215-13.858-12h-6.75a1 1 0 0 1-1-1V27.087l-10.84 5.42a1 1 0 0 1-1.44-.772l-.007-.114L9 20.164a1 1 0 0 1 .553-.904l22.32-11.155A1 1 0 0 1 32.32 8M29 43c0-7.188 5.417-13.111 12.392-13.909v-3.566a1 1 0 0 1 1.341-.94l.106.046L53.585 30l.083-9.232-21.331-10.66-21.332 10.66.084 9.232 10.856-5.425a1 1 0 0 1 1.44.779l.007.115V43zm2 0c0-6.627 5.373-12 12-12s12 5.373 12 12-5.373 12-12 12-12-5.373-12-12"
            fill="#521094"
            fillRule="evenodd"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath className="a" id="a">
        <path d="M0 0h64v64H0z" fill="#fff" />
      </clipPath>
    </defs>
  </Icon>
)
