/**
 * This file is automatically generated from /utils/illustrations/uploadIllustrations.js
 * PLEASE DO NOT EDIT HERE
 */

const BASE_URL = 'https://ultraviolet.s3.fr-par.scw.cloud/illustrations'

const redisContent = `${BASE_URL}/products/redis/redis-content.webp`
const redisKeyvisual = `${BASE_URL}/products/redis/redis-keyvisual.webp`
const redisOriginal = `${BASE_URL}/products/redis/redis-original.webp`
const redisWire = `${BASE_URL}/products/redis/redis-wire.svg`

export { redisContent, redisKeyvisual, redisOriginal, redisWire }
